brimdata/zui

- itest/lib/app.js
- src/js/components/PacketPostProgress.js
- src/js/test/integration.js
Wait for the ingest progress indicator not to exist as a clue that ingest is complete. This helps reduce test races in cases where we want ingest to succeed.
> test fix: wait on ingest to stop

- CHANGELOG.md
- README-Windows.md
From a supportability perspective, it's great we have our Windows release, but I want to make sure we've written down that its "beta quality" limitations are known. In a discussion with @alfred-landrum we agreed on an approach like we've done for `zq` where we'll have a `CHANGELOG.md` that we'll update and commit with each release, then copy those same notes into the GitHub Releases tab alongside the artifacts.
Here I've backfilled the notes from our first public Releases into a new `CHANEGLOG.md`, along with my draft proposal for describing the Windows limitations. Once the wording is approved and this PR is merged, I'll backfill those Windows limitations into the notes for those two existing releases.
> Initial changelog, including Windows limitations

- scripts/download-zdeps/index.js
This zeek artifact uses a WinPCAP variant that includes pcapng support.
> windows: use zeek-20200624 artifact for pcapng support

- src/js/services/BoomClient/adapters/download.js
- src/js/services/BoomClient/client/Packets.js
- src/js/state/Packets/flows.js
Instead of reading the response from the server, we were just returning the StatusMessage. 
The pr reads the response and rejects the promise if its an error.
The reason for throwing the error again is so that we don't try to open anything when the promise resolves.
UPDATE:
Wrapped packets.get in a try catch and return a rejected promise if theres an error. This way we always see the error string in the app rather than the console.
The example below is the result of me hard coding a "null" value for the duration field.
Added some debug info: (space, destDir, log)
> PROD-1687 Surface download errors in the app

- package-lock.json
- package.json
- scripts/release/install.js
- src/js/electron/autoUpdater.js
- src/js/electron/main.js
The ultimate aim of this PR is to add an autoUpdater to the Brim app such that when a new release is out, the app will automatically update itself. There are a couple of details worth mentioning here which the code might not indicate:
* Using electron's `autoUpdater` along with https://github.com/electron/update.electronjs.org, an update server, which is maintained by GitHub and free for open-source projects.
* Since we are using the above server and framework, there is a dependency for macOS builds to include a `*{darwin}*.zip` asset for each release we would like to auto-update. So I have extended the `release` script to also produce that required zip asset. The autoUpdater will also fail to initialize if the running version is not code signed (i.e. you must run the release script with …
> PROD-1627 add autoUpdater

- scripts/download-zdeps/index.js
- src/js/services/BoomClient/adapters/BrowserFetchAdapter.js
- src/js/services/BoomClient/lib/BoomRequest.js
- src/js/services/zealot/fetcher.js
This is meant to be a quick fix reusing the parse function that now exists in the zealot client. When we go through here again to refactor/consolidate the two clients into one then we can cleanup some of the assumptions that the boom client is still making w.r.t. expecting json encoded errors.
> PROD-1566 Boom client inspect content-type

- .github/workflows/macos-release.yml
We are already producing a .zip in the release script, this adds an explicit step to upload it as part of the assets. Name of the zip is further coupled to this workflow now (just like the `Brim.app` already is), but I don't expect these to change much, if ever, anyway.
> PROD-1706 adjust github action

- .github/workflows/ci.yml
- itest/lib/app.js
- itest/lib/env.js
Build the dmg using our tools, simulate installation, and point Spectron to the installed application path.
> test feat: integration tests with macOS dmg

- src/js/services/BoomClient/adapters/download.js
- src/js/services/BoomClient/client/Packets.js
First I caught an exception that was not being handled so that if an error occurs in the same place, it will at least be shown in the UI.
Then I fixed the error that was throwing that exception. It turns out that the node http module does not encode the URI components that we pass to it. This must be done ourselves. By contrast, the browser fetch API encodes for us.
**SIDE DISCOVERY**
I also discovered some code on stack overflow that will allow us to use the browser fetch API and stream the response to the node fs module which writes to the file system. When we implement the packet download api call in zealot, I recommend doing this. 
https://stackoverflow.com/a/44695617/3499804
> PROD-1698 Download Errors with Spaces in Spaces

- src/js/state/Tabs/reducer.js
- src/js/state/Tabs/selectors.js
- src/js/state/Tabs/test.js
The first fix is to throw a `new Error()` rather than a `"string"` so that the error page gets populated.
The second fix is to make sure that you can never activate a tab that has been deleted. I added some console logs to debug this and found that every now and then, the timing of the dispatch calls led to "DELETE tab x" followed by an "ACTIVATE tab x".
You can now bang away at activating and removing tabs and you'll never hit this error.
> PROD-1638 Never activate a tab that does not exist

- .github/workflows/win-release.yml
- README-Windows.md
- scripts/release/index.js
- scripts/release/install.js
Assuming a PFX base64-encoded password-protected certificate secret pair, sign a Windows installer release asset.
Usage is: `node scripts/release --win32 [--windowsCertificateFile <file> --windowsCertificatePassword <password>]`
The stack for signing is as follows, and you can read more about the stack at the links provided.
- `scripts/release`
-  [electron/windows-installer](https://github.com/electron/windows-installer)
- [Squirrel](https://github.com/Squirrel/Squirrel.Windows)
- [signtool](https://docs.microsoft.com/en-us/windows/win32/seccrypto/signtool)
The basic electron-winstaller method of signing requires file and password parameters. I've taken care to ensure the password is not printed upon either success or failure.
The release CI will produced a signed executable. Interested …
> Windows installer signing

- src/js/zqd/zqd.js
Change logging config to use the waterfall logger added to zqd in
brimsec/zq#492. Logs named http.access will be logged in zqd-access.log,
every other log will go to zqd-core.log.
> Use zqd waterfall logger

- src/js/components/useSearchShortcuts.js
- src/js/flows/adjustSelectedLogIndex.js
Can use arrow keys to select logs from viewer if one has already been selected (and is currently in the search results).
**Note**: While playing around with this I discovered that the existing arrow behavior for scrolling has a bug where it will begin to scroll but then breaks, so this feature also acts as a bit of a bandaid for that since will now preventDafault() on either event. Ideally, IMO, we should track if the currently selected log is not only among the current search results, but is also within the current results view, and if it is not then we will adjust the scroll view to be in sight of it. Then if no result is selected then the up/down arrows will scroll the viewer properly (this is the part that is broken atm), though it looks like there is also some existing functionality …
> PROD-1538 use arrow keys to select logs

- .github/workflows/ci.yml
- itest/tests/externalApis.test.js
- ci: control xvfb where needed
The screen size provided by xvfb-action isn't adequate for our tests. This sets the screen size for when we need XVFB. The tradeoff is a YAML "fork" depending on OS. It's likely that down the road OS-wise integration tests will vary anyway, so I think some sort of fork is going to happen sooner or later. It is a reasonable tradeoff.
- test fix: deflake external API tests
- Ensure jest won't time out a test.
- Use retry() for the zeek.org tests.
> test improvements

- itest/lib/data.js
- itest/tests/__snapshots__/histogram.test.js.snap
- itest/tests/histogram.test.js
It's basically the same histogram test as before, except with a different ingest flow and different data set.
The code was already sitting around but blocked on the problem fixed in #561. That can go in first, and then this will be rebased and go green. But it can be reviewed at any time.
> Revive histogram test (fixes #544)

- src/js/initializers/index.js
- src/js/initializers/initPersistance.js
- src/js/state/createGlobalStore.js
- src/js/state/globalReducer.js
Drop the previously saved state if the version is different
This is a crude way to handle state migrations. I'd like to
think this through more, but at least there are no startup
errors when you upgrade versions now.
Going forward, we'll need to increment this VERSION string each time we mess with the shape of the state. 
I think it would be good to write a test that does some of the common operations on the redux store, the saves the resulting state in a snapshot. Then each time we make changes to the state shape, hopefully that test will fail with a message like "update the state version".
Depending on how critical it is for users to save state, like their history and in the future, their saved queries. We may want to write more code to migrate data and what not.
fixes #584
> Check the version of the state object

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
After seeing how the templates actually looked when opening a new issue, I realized it was a mistake to use markdown notation to point at the troubleshooting doc. The user first sees the template as raw text, not rendered markdown. Therefore it seems more user-friendly to offer them a full URL they could easily cut & paste into a browser window.
> Use troubleshooting URL in issue templates

- .github/workflows/ci.yml
- .github/workflows/macos-release.yml
- .github/workflows/win-release.yml
- Use `npm config get cache` to derive the npm cache directory and use it in the cache step. This fixes the cache misses on Windows.
- Clear the 1G of cache that is on the base macOS runner. Note that `npm cache clear --force` was only able to clear about 250M, so the more direct `rm -rf` approach was needed. This reduces the macOS cache  to about 78M, inline with Windows and Linux cache sizes.
- Change the cache name to prevent reuse of bad caches.
`npm install --no-audit` is still slower on macOS than other platforms, but the massive cache store/recall on mac goes away. It's difficult to compare cloud CI build times, but rough timing comparisons suggest this will generally speed up CI from ~30 to ~10 minutes during PDT mornings.
master: …
> ci: improve npm caching (fixes #589)

- CHANGELOG.md
Since I was updating the `zq` pointer at the same time I was creating the changelog for Brim `v0.6.0`, I'd forgotten to mention it in the changelog. I've already updated it in the ["live" release notes](https://github.com/brimsec/brim/releases/tag/v0.6.0), but circling back to take care of it here as well.
> Mention zq update to v0.9.0 in changelog for v0.6.0

- itest/lib/app.js
- itest/lib/jest.js
- itest/lib/log.js
If an integration test fails, the cleanup handler will now dump a screen shot into the same directory that log artifacts are stored.
I peeled off this work while debugging CI failures for a different branch. You can inspect artifacts at https://github.com/brimsec/brim/suites/589149338/artifacts/4195825
> test feat: screen shots on failure

- src/css/_toolbar-button.scss
- src/js/flows/openPacket.js
- src/js/flows/openPacket.test.js
fixes #607 
The UI will render the "Search" page when a space is selected and is "queryable". Queryable means that the `space.min_time` and `space.max_time` are both set to something other than zero.
The first time a "Search" page is rendered for a space, it will issue an initial search with the time span set to the min and max of the space.
So to fix the bug, wait until we receive the first PostPacketStatus with a snapshot_count > 0 before setting the min/max time of the space.
Side Fix:
The text was wrapping on some of the toolbar buttons. That is now fixed and they will not wrap.
> Ingest Queryability Bug

- src/js/flows/saveWindowState.js
- src/js/flows/saveWindowState.test.js
Fixes #600 
This caused a strange bug where `state.handlers` was undefined. Then the app tried to do something with it, and it threw an error. I traced it back to this state mutation.
It's now locked in with a unit test
> Do not mutate the window state object

- itest/lib/app.js
- itest/lib/data.js
- itest/tests/histogram.test.js
Ensure all tests do no deep verification until either refreshing the page or running a query. The only test that needed to be change is the histogram deep inspection test.
The initial histogram check will just ensure something is visible. Subsequent deep inspection counting is done after a page refresh, initiated by an explicit span setting of "Whole Space".
Fixes #609.
> Fix results assumptions

- .github/workflows/ci.yml
The artifact namespace is per-workflow run, not job run. This means artifacts need to be named with that in mind to avoid a collision should multiple jobs fail. Key on OS and node version, which is our current matrix.
> ci fix: key artifact name on build matrix

- itest/lib/control.js
The tests still have a 5m timeout, which so far is enough padding.
> test fix: increase default retryUntil to 60s

- itest/lib/app.js
This was originally employed to work around Spectron choosing a random port colliding with our back end. Spectron's choosing a random port was in turn used as an Electron workaround.
The workarounds haven't been needed since Electron 5. We moved past Electron 4 at https://github.com/brimsec/brim/pull/381 .
This effectively reverts https://github.com/brimsec/brim/pull/319
Other refs:
https://github.com/electron-userland/spectron/pull/361
https://github.com/electron-userland/spectron/pull/364
I temporarily enabled collection of artifacts upon success here: https://github.com/brimsec/brim/actions/runs/80214904
```sh
$ find {macos,ubuntu}/*chromedriver.log -exec grep -m1 devtoolsFrontendUrl {} \;
"devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:49530/devtools/page/46363801C6153D7D …
```
> test fix: remove explicit remote-debugging-port

- .github/workflows/ci.yml
- src/js/electron/ipc/windows/mainHandler.js
- src/js/electron/tron/windowManager.js
When Spectron launches Electron instances on Windows, empty command prompt windows are spawned along with the Electron instance window. (Spectron internally uses a `.bat` file to run chromedriver, and Windows apparently always shows a command prompt window when you run a batch file). 
These command prompt windows steal focus from the Electron window. So an individual test may succeed or fail, but Spectron can't shutdown the instance, because it can't close its test window, because it's not focused.
I verified this locally by running the integration tests w/o any changes, and verifying that despite test success or failure, the only way the Electron instances would go away is if I put in a brief sleep so that I could manually click on the Electron instances to make them focused.
@jameskerr …
> fix windows ci: dont rely on focus to destroy a window

- src/js/zqd/zqd.js
There is apparently a difference on trying to use "Path" vs "PATH" depending on whether you use cmd.com or powershell. Avoid needing to clone process.env and worry about that difference, and just modify it directly. Without this change, I would see occasional failures if I ran the integration tests locally in powershell, cmd.com, or git bash. With this change, I don't see any errors.
Fixes #556 .
> avoid Path vs PATH errors on windows

- itest/lib/app.js
- itest/tests/pcaps.test.js
Add integration tests for downloading packet captures. The tests are
accomplished by uploading data, running zql to find a deterministic
connection (can't use UID), clicking a cell, and downloading the packet
capture. In CI the files are put into a directory, where we can examine
the file's MD5.
In older times, there was a bug where a null-duration connection's pcap
could not be downloaded. That has since been fixed, so that test is
enabled.
> test fix: test download pcaps (fixes #543)

- .github/workflows/ci.yml
- .github/workflows/macos-release.yml
- .github/workflows/win-release.yml
Fixes #641 
Adjust how the npm cache directory is expanded. We need to quote it in
bash so that "\\" is not quashed. But it's not possible to directly quote
the Github action expression, because the running shell will attempt to
expand it using normal shell expansion rules. That means this doesn't
work:
```
- run: rm -rf "${{ foo.bar }}"
```
Also,
```
- run: rm -rf ${{ foo.bar }}
```
will not work in some cases, like if foo.bar is a Windows path. If
foo.bar is "c:\foo", the shell will turn that into "c:foo".
The fix is to assign an environment variable from the expression
directly, then quote the environment variable in the shell.
To force using a new, smaller cache, change the cache name.
> ci fix: properly handle windows paths in bash

- .github/workflows/docs-publish.yml
This is the first step in putting the Brim docs on a GitHub Wiki.
Our goal is to update the docs as part of Pull Requests on the main repo, potentially at the same time other code is being updated. To facilitate this, an Action is used that checks for changes to the `docs/` directory whenever there's pushes to `master`. Any adds/moves/deletions in that `docs/` directory are committed to the equivalent spot in the adjacent GitHub WIki repo.
As a prerequisite, I went looking for an existing Action that would do this for me. I couldn't find one that worked quite the way I wanted out-of-the-box, so I have our own fork at https://github.com/brimsec/github-wiki-publish-action and merged https://github.com/brimsec/github-wiki-publish-action/pull/1 with my minimal changes.
_This_ PR just gets …
> Add Actions workflow for publishing docs to wiki

- docs/Home.md
- docs/Microsoft-Windows-beta-limitations.md
- docs/Troubleshooting.md
- docs/_Footer.md
- docs/_Sidebar.md
This is the PR described in step #1 of https://github.com/brimsec/brim/pull/659.
> Populate "docs" directory with wiki-bound articles

- docs/Troubleshooting.md
I realized the tool I'd used to create the table of contents for the Troubleshooting doc did an imperfect job of creating links to the actual sections within the Markdown, so I've fixed them here. Clicks to these entires in the TOC weren't working before.
(This also gives me an excuse to trigger the Action workflow one more time to get the wiki deployment bootstrapped, as I'd made a mistake earlier when creating the empty wiki.)
> Fix links from Troubleshooting TOC

- src/js/brim/ingest/detectFileType.js
- src/js/brim/space.test.js
- src/js/flows/rightclick/cellMenu.test.js
- src/js/state/Spaces/actions.js
- src/js/state/Spaces/reducer.js
- src/js/state/Spaces/selectors.js
- src/js/state/Spaces/test.js
- src/js/state/Spaces/types.js
Fixes: #575 
Store the ingest warnings in the redux store under the space. This works fine since a space is only ever allowed to be ingested into once. We may have to refactor where we put these errors in the future.
> Save ingest warnings in space state

- itest/tests/query.test.js
As long as Whole Space is the default, we needn't set "Whole Space"
every time. This works around #668 until a better fix can be introduced.
> test workaround: do not set span for now

- src/js/components/useSearchShortcuts.js
fixes #591 
I also had noticed that `cmd+w` was closing the whole window instead of just the tab, so fixed that too (prevent default)
> Throttle key events

- .github/workflows/linux-release.yml
- package-lock.json
- package.json
- scripts/release/index.js
- scripts/release/install.js
Augment ./scripts/release --linux command to produce redhat release
package.
Update linux release github action to upload .rpm artifact.
Working on Fedora 30:
Icon works as well (gnome 3):
part of #618
> Redhat release artifact

- scripts/clean/index.js
Since `npm run start` runs `clean`, without this change, it's hard to locally test loading the same space between runs.
> dont remove the run directory on npm clean

- src/js/brim/field.js
- src/js/brim/field.test.js
#626 
In the repro steps for this issue, the log's contents have double quotes as part of the values which need to be escaped when we use that value as a search argument
> fix invalid filter

- src/js/components/RightPane.js
- src/js/components/RightPane.test.js
If there was no space, but the right pane was open, it would crash the app. Check for a space and bail early. A regression test has been added as well.
fixes: #652 
Video of Fix: https://recordit.co/6G8XkThihN
> Do not render RightPane with no space

- .github/workflows/ci.yml
- scripts/release/install.js
Add the build ci phase to build the linux release artifacts (.deb and
at the .rpm) at the end of the job then upload artifacts.
Add integration_test_centos which downloads the created rpm package
and runs the standard suite of integration tests against it.
Also:
- Have ubuntu integration tests download and run against the uploaded
deb package.
closes #618
> integration test for rpm package

- src/js/brim/ingest/detectFileType.js
- src/js/brim/ingest/detectFileTypes.test.js
- src/js/brim/ingest/fileList.js
- src/js/brim/ingest/getParams.js
- src/js/brim/ingest/test.js
- src/js/components/StatusBar.js
- src/js/flows/ingestFiles.js
- src/js/state/Spaces/reducer.js
fixes: #687
Previously we were checking each file to see if was a pcap, zeek, json, or unknown type. Now we just check if any one of them is a pcap. If there is 1 pcap, we send it over the /pcaps/ endpoint, else /logs/.
This makes it simple and lets the backend do the rest of the auto detection. I've been even able to ingest a json and a zeek tsv at the same time now.
> If its not a pcap, its a log

- src/css/_info-notice.scss
- src/css/_x-button.scss
- src/css/main.scss
- src/js/brim/space.js
- src/js/brim/space.test.js
- src/js/components/App.js
- src/js/components/InfoNotice.js
- src/js/components/IngestRefresh.js
- src/js/components/TabSearch.js
- src/js/components/TabWelcome.js
- src/js/components/XButton.js
- src/js/components/hooks/useThrottle.js
- src/js/flows/ingestFiles.js
- src/js/flows/ingestFiles.test.js
- src/js/flows/rightclick/cellMenu.test.js
- src/js/initializers/initDetail.js
- src/js/initializers/initPersistance.js
- src/js/initializers/initSearch.js
- src/js/initializers/initUserInputClasses.js
- src/js/state/History/selectors.js
- src/js/state/Search/selectors.js
- src/js/state/Spaces/actions.js
- src/js/state/Spaces/actionsFor.js
- src/js/state/Spaces/index.js
- src/js/state/Spaces/reducer.js
- src/js/state/Spaces/selectors.js
- src/js/state/Spaces/test.js
- src/js/state/Spaces/types.js
- src/js/test/fixtures/index.js
fixes #616 
If the tab history is empty, this component submits the current search. This
happens the first time this tab is rendered after a file is dragged in.
As the files are ingested the backend incrememnts a snapshot_counter to
indicate that more data is available to search.
Everytime space.ingest.snapshot is incremented, this component will effectively
hit the "Enter" key for the user if all these conditions are met:
* There is only 1 entry in the tab history
* The search bar inputs are in the same state as that first entry
* The current snapshot has not yet been acknowledged
If anyone of those is not true, then the component renders a message box to
allow the user to manually refresh if they want. This box appears when
* Any of the above conditions are not met
* The current …
> Ingest Auto Refresh

- src/js/services/BoomClient/client/Descriptors.js
- src/js/services/BoomClient/client/Spaces.js
- src/js/services/zealot/logsApi.js
- src/js/services/zealot/pcapsApi.js
- src/js/services/zealot/spacesApi.js
fixes #650 
uri encodes `space` when used as a uri path
> encode space name

- src/css/_notice-banner.scss
- src/js/components/ErrorNotice.js
The fix is allow wrapping and new lines.
The errors will now appear looking like this:
> Long Error Messages

- src/js/flows/ingestFiles.js
If the user clicks the "Choose files..." button, the will not be able to select a directory. However, they can drop a directory on the dropzone. If this happens, we present them with a better error message.
fixes: #725
> Add error message for importing a directory

- src/js/brim/ingest/getParams.js
- src/js/brim/ingest/test.js
- src/js/flows/ingestFiles.js
- src/js/flows/initSpace.js
- src/js/lib/file.js
fixes #673 
Our spaces are still named `.brim` but the internal folder we use is now stored within the app's data. I tested this in dev and also release.
> keep brim folders inside app data

- .github/workflows/ci.yml
- .github/workflows/linux-release.yml
- .github/workflows/macos-release.yml
- .github/workflows/win-release.yml
- package-lock.json
- package.json
- scripts/download-zdeps/index.js
It's possible to npm install zq from an arbitrary Github hash as long as you choose a zq hash that supports it. While npm's syntax for doing this is flexible, the only one that seems to use HTTPS is of this form:
`npm install https://github.com/brimsec/zq#086719e76d53ace254cc495b4cc21d2efe069e73`. The shorthand like `github:brimsec/zq#hash` use the `git://` URI scheme.
See https://github.com/brimsec/zq/pull/712 for the companion PR. It does the heavy lifting. Here, we need only copy into zdeps where needed and set up Go.
Fixes #699 #702
> Install zq hashes

- src/js/electron/main.js
- src/js/electron/tron/windowManager.js
- src/js/electron/userTasks.js
When the about page is the only window that is opened when quitting the app, the app would be in a state where a new search page was impossible to create on windows.
We fix this in two ways:
* Only re-open the previous session's "search" windows. If none exist, then open a new one.
* Provide a menu option in the taskbar on windows to create a new window.
fixes: #645
> Windows New Window

- src/js/components/TabWelcome.js
- src/js/errors/index.js
This would happen during ingest if someone closes their laptop
then re-opens it, or if the computer falls asleep.
If the computer sleeps before the first IngestStatus is returned,
the error message is "Failed to fetch". If it happens after the
first status is returned, the error message is "network error".
We now look for both of these and present the importInterupt error
message.
fixes #533
> Use a better error messages for ingest interrupt

- docs/Home.md
- docs/Supported-Platforms.md
- docs/_Sidebar.md
This article provides details on the platforms on which we expect to deliver consistent quality (since we run on them in CI) vs. "best effort".
I could definitely use close review on the sections where I call out to the Electron and Go docs. I figure it's worth going to that level of detail since some in the open source community may be able to make use of this information. Since Brim depends on both Electron and Go, I basically took the approach of saying that anything _older_ _than_ the the earliest platform supported by _both_ should _not_ be expected to work. For instance, this is why I set expectations that anything older than macOS 10.11 would not work, since that was the oldest one in in Go's platform statement, though Electron claims to be ok to 10.10.
Closes #642
> Brim wiki article about supported platforms

- docs/Supported-Platforms.md
Alas... one of the hazards of this CI-based wiki publishing workflow is that it's not always easy to spot rendering problems that'll show up in the final wiki location. I'd mistakenly been linking to the raw markdown instead of the rendered link inside the page.
> Fix typo in Support Platforms wiki section

- src/js/components/TabWelcome.js
This is to get master back to green since prettier wants a semi-colon but eslint does not.
The future fix is to have prettier do all the re-formatting rules, while eslint only has qualitative rules.
> Dis-ambiguate the regex literal

- docs/Supported-Platforms.md
@mattnibs pointed out that our integration test coverage is the same on CentOS 8 as it is for Ubuntu 18.04. This simplifies the support statement somewhat.
> Mention CentOS 8 in Support Platforms wiki article

- CHANGELOG.md
While copying the `v0.9.0` changelog into the notes in the Releases tab on GitHub, I saw that I'd mistakenly put in the Issue links for two items instead of the PR links. I fixed them on the Releases tab, but here I'm circling back to correct them in the changelog for consistency.
> Correct two refs that were to Issues, not PRs

- itest/lib/app.js
- itest/tests/__snapshots__/contextMenu.test.js.snap
- itest/tests/contextMenu.test.js
- src/css/_html-context-menu.scss
- src/css/main.scss
- src/js/components/App.js
- src/js/components/HTMLContextMenu.js
- src/js/components/hooks/useEventListener.js
- src/js/lib/System.js
- src/js/test/integration.js
We intercept the call to create the rightclick menu right before it gets sent to electron. Then we dispatch our own event to the dom, then build a simple html context menu that will only be used when `process.env.BRIM_ITEST === "true"`.
To test this locally, start the app normally, then open the console and type in the following:
Now the app will respond to right clicks by building an html version of the context menus.
@mikesbrown this should make those integration tests much easier to write.
> Render html menus in integration tests

- .github/workflows/advance-zq.yml
https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch says
> This event will only trigger a workflow run if the workflow file is on the master or default branch.
Start with this bare one in order to at least show zq can communicate to brim.
> bare repository_dispatch handler

- CONTRIBUTING.md
- package-lock.json
- package.json
- scripts/download-zdeps/index.js
- src/js/zqd/zqd.js
This is part of the brimsec/brim repo side work for brimsec/brim#731. 
Use the `-zeekrunner` cli option to zqd ( https://github.com/brimsec/zq/pull/718 ), defaulting to the value of environment variable `BRIM_ZEEK_RUNNER`, else to the zeekrunner included from the zdeps zeek artifact ( https://github.com/brimsec/zeek/pull/23 ).
> use zeekrunner scripts and zqd cli option

- src/css/_ingest-warnings-modal.scss
- src/css/_modal.scss
- src/css/_settings-modal.scss
- src/js/components/IngestWarningsModal.js
- src/js/components/Preferences/FileInput.js
- src/js/components/Preferences/JSONTypeConfig.js
- src/js/components/Preferences/Preferences.js
- src/js/components/Preferences/TimeFormat.js
- src/js/components/Preferences/ZeekRunner.js
- src/js/components/Preferences/usePreferencesForm.js
- src/js/components/common/Link.js
- src/js/electron/main.js
- src/js/state/Prefs/actions.js
- src/js/state/Prefs/reducer.js
- src/js/state/Prefs/selectors.js
- src/js/state/Prefs/test.js
- src/js/state/Prefs/types.js
- src/js/zqd/zqd.js
The ZQD class will now look in the global preferences for a user specified zeek runner. This means that if a user changes the value, it will not be in effect until the app is restarted. Because of this, whenever the value changes, we show a message "Restart required."
fixes: #741
> Zeek Runner User Preference

- src/js/flows/confirmUnload.js
- src/js/flows/deletePartialSpaces.js
- src/js/flows/ingestFiles.js
- src/js/flows/ingestFiles.test.js
- src/js/state/Handlers/selectors.js
- src/js/state/Handlers/types.js
fixes #778 
We save the names of all spaces that are currently ingesting. This way we can clean up the spaces if they decided to quit the app.
Instead of saving the names, save the ids.
> fix: Store spaceId in request handler state

- .github/workflows/advance-zq.yml
When a zq PR is merged, update zq locally, run unit and integration tests, and commit the change if the tests pass. If the tests fail, save artifacts and open a PR. The PR text will contain links to the failing auto-update attempt. Opening a PR lets us piggy-back on alert infrastructure already in place, and provides a branch on which further Brim adjustments could be made.
Testing
The zq-triggering portion was verified earlier and continues to work. See for example [this run](https://github.com/brimsec/brim/actions/runs/105690954), triggered after the merge of brimsec/zq#783 .
One difficulty is that the handling of repository_dispatch events only runs on the default branch, which is master in most cases. To test, I copied the JSON from events into files I temporarily checked in to a Git …
> feat: auto-update zq after successful testing (fixes #734)

- bin/generator/index.js
- bin/generator/migration.js
- src/js/electron/tron/index.js
- src/js/electron/tron/migration.js
- src/js/state/migrations/9_initMigrations.js
- src/js/test/helpers/getTestState.js
A command line tool to use whenever you're developing and need to change the state of the app and include a migration.
For example, if I wanted to change min_time and max_time to now be called span, I'd create the migration like this:
```bash
bin/gen migration changeMinMaxTimeToSpan
Created: src/js/state/migrations/202005141644_changeMinMaxTimeToSpan.js
Created: src/js/state/migrations/202005141644_changeMinMaxTimeToSpan.test.js
```
These files would be created and stubbed out like this:
```js
// 202005141644_changeMinMaxTimeToSpan.js
export default function changeMinMaxTimeToSpan(state: *) {
// Migrate state here
return state
}
```
```js
// 202005141644_changeMinMaxTimeToSpan.test.js
import getTestState from "../../test/helpers/getTestState"
import migrate from …
```
> Migrations 2: CLI

- .github/workflows/advance-zq.yml
I was passing in the wrong parameter name for depth. Since `actions/checkout@v2` was ignoring the wrong parameter name, the parameter isn't needed after all. Also, when creating the commit message, quote the here document delimiter to prevent substitution and expansions.
> Fix some zq auto update buglets

- src/js/brim/ingest/getParams.js
- src/js/brim/ingest/test.js
- src/js/components/Preferences/DataDirInput.js
- src/js/components/Preferences/FileInput.js
- src/js/components/Preferences/Preferences.js
- src/js/components/Preferences/usePreferencesForm.js
- src/js/electron/ipc/types.js
- src/js/electron/ipc/windows/mainHandler.js
- src/js/electron/ipc/windows/messages.js
- src/js/flows/ingestFiles.js
- src/js/lib/file.js
- src/js/services/zealot/spacesApi.js
- src/js/state/Prefs/actions.js
- src/js/state/Prefs/reducer.js
- src/js/state/Prefs/selectors.js
- src/js/state/Prefs/test.js
- src/js/state/Prefs/types.js
fixes #676 
Turns out html `input` forms **really** prefer files over directories. There is apparently a `webkitdirectory` option which I experimented with first. The result was that the selector dialog would behave correctly but the `onChange` handler was no longer being called internally inside react. That property also is not recommended in the [docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) (though I believe the primary reason for this is browser compatibility, which we are in control of in electron).
To fix this then, I added an ipc call so that the dialog that appears comes from electron and the main process. What's nice about this is that it will actually not allow users to select anything BUT a directory. Still, the form has validation in …
> User dataDir preference

- src/js/electron/menu/appMenu.js
- src/js/initializers/initShortcuts.js
- src/js/state/migrations/202005181133_addTimeFormatPref.js
- src/js/state/migrations/202005181133_addTimeFormatPref.test.js
- src/js/state/migrations/202005181140_searchStateSpaceId.js
- src/js/state/migrations/202005181140_searchStateSpaceId.test.js
- src/js/state/migrations/202005181158_spacesStateId.js
- src/js/state/migrations/202005181158_spacesStateId.test.js
Finally, we use the new migration framework to migrate the following.
```diff
src/js/state/Prefs/types.js
export type PrefsState = {
jsonTypeConfig: string
+  timeFormat: string,
+  zeekRunner: string
}
```
```diff
src/js/state/Search/types.js
@@ -7,7 +7,8 @@ export type SearchState = {
span: Span,
spanArgs: SpanArgs,
spanFocus: ?Span,
-  space: string,
+  spaceName: string,
+  spaceId: string,
clusterId: string,
ts: number
}
```
```diff
src/js/state/Spaces/types.js
export type SpacesState = {
// clusterId
[string]: {
-    // spaceName
+    // spaceId
[string]: Space
}
}
export type Space = {
name: string,
+  id: string,
min_time: Ts,
max_time: Ts,
-  packet_support: boolean,
+  pcap_support: boolean,
ingest: SpaceIngest
}
```
The command used to find these changes was this: 
```
git diff …
```
> Migrate state changes since v0.9.1

- src/js/components/Preferences/FileInput.js
- src/js/components/Preferences/ZeekRunner.js
fixes #777 
Looks like when onClick and onDrop occurs it doesn't end up propagating to an underlying onChange event. Since it's our own component, we can call the passed in `onChange` handler manually instead. I opted to directly pass in the changed value since it depends on the mechanism used and the caller will not have a way of knowing.
> show "restart required" for zeekRunner preference change

- package-lock.json
- src/js/components/Preferences/FileInput.js
It looks like the `onClick` event default behavior was causing a page refresh which triggered the windows:initialState message and, ultimately, the page break. This error would occur for all of the `Choose` buttons, in fact. Preventing that default seems to have done the trick. 
When I ran `npm install --no-audit` it looks like there are also a few packages locked in with an insecure url that it fixed for me. It's not related to this PR but I figure I'd check it in too since we want the secure urls.
> fix choose file bug

- src/js/components/App.js
- src/js/components/SavedSpacesList.js
- src/js/components/SpaceModal.js
- src/js/components/TabWelcome.js
- src/js/electron/menu/actions/index.js
- src/js/electron/menu/actions/spaceActions.js
- src/js/electron/menu/index.js
- src/js/electron/menu/spaceContextMenu.js
- src/js/flows/renameSpace.js
- src/js/initializers/initMenuActionListeners.js
- src/js/state/Clusters/selectors.js
- src/js/state/Modal/types.js
- src/js/state/Spaces/actions.js
- src/js/state/Spaces/reducer.js
- src/js/state/Spaces/test.js
- src/js/state/Spaces/types.js
fixes #674 
Uses a simple modal for the rename mechanism, after right clicking on a space.
> add rename right click

- docs/Supported-Platforms.md
As a side effect of the zeek work going in to improve windows support in https://github.com/brimsec/brim/issues/563 , we're upping the C++ features needed to build Zeek, and on macOS, that means the zeek binary will only work on macOS 10.14 and beyond.
@nwt : please confirm for accuracy!
> note that pcap import wont work on macOS versions prior to 10.14

- src/js/electron/tron/migrations.js
- src/js/electron/tron/session.js
- src/js/electron/tron/session.test.js
- src/js/test/helpers/disableLogger.js
If a user has a version prior to v0.9.1, we don't try to migrate their state.
If you open the app in v0.8.0, ingest some data, perform some searches, then quit, then open the app at master, you'll see a message in the logs that says:
```
[2020-05-27 14:45:59.759] [info] migrations: unsupported version, using fresh state
```
It will indeed clear the state and start fresh. However, the spaces that you ingested will remain. 
**Known Bug With Space Names**
Testing this revealed a bug in zqd. The spaces created in v0.8.0 (before space ids), are returned without a name after upgrading to the latest brim version. It results in the app looking like this when you load up the newest version. 
In this example, I ingested a file called `a.pcap` in v0.8.0, then quit, upgraded, and re-opened brim.
Work …
> Reset state if less than v0.9.1

- src/css/_space-modal.scss
- src/css/main.scss
- src/js/components/SpaceModal.js
fixes #674 
refactors the rename modal to use the existing buttons api that our own `<ModalBox />` already provides. 
> hit enter to rename

- docs/Microsoft-Windows-beta-limitations.md
Since our next Brim release will get our Windows support out of the Cygwin muck, I've realized we can improve our Windows support statement. I figure we can keep using the "beta" label until the upstreaming is complete & the Windows Defender spirits have become satisfied with our animal sacrifices. In the meantime, I've softened the language a bit since our Zeek performance on Windows is greatly improved.
If this PR is approved, I'll hold off on merging this until right when I'm prepping the release.
> Adjust Windows beta notice

- src/js/electron/appPathSetup.js
There is a case where `BRIM_ITEST=true` but `--user-data-dir` is not specified: manual runs of the app, via command like:
```
BRIM_ITEST=true npm run electron
```
Such cases are useful in order to observe app behavior with the mock context menu.
Before, this would use the default system user data directory. Now, this uses `run/`.
> fix: use the run/ dir if BRIM_ITEST=true

- scripts/download-zdeps/index.js
Testing with this branch shows the JA3 and HASSH fields are appearing where we expect them after importing a pcap.
> Point to new Zeek artifact that includes JA3/HASSH

- itest/lib/app.js
- itest/lib/env.js
- itest/tests/zar.test.js
Brim isn't fully ready to handle zar spaces yet, but this test
establishes a temporary workflow for getting zar data into a space and
making sure Brim starts. As Brim's functionality to read a Zar space
improves, this test can be modified. The purpose of this is to put
something in place that changes alongside the functionality as opposed
to having nothing until all the functionality is ready. As such, there's
not as much abstraction as there otherwise would be: much of this should
get thrown away once Brim supports Zar.
The test uses Brim as the driver for starting zqd so that the test don't
have to do zqd orchestration itself. It ingests sample.tsv as usual.
Then it uses zealot to create a second, empty space called sample.zar
and also get space metadata from space sample.tsv.brim. The …
> add a test that creates a zar space under brim

- .github/workflows/advance-zq.yml
- itest/config.json
Webdriver-style tests wait for elements to appear or to be set to a
specific state. This means a lot of test failures are timeout-driven.
An overall job timeout is already set here in case turnstyle hangs.
However, the current value is too short in cases where Zq and Brim are
so broken as to cause every integration test to fail. Locally under
these conditions, the integration tests took 63 minutes to fail. In CI,
assume that could take up to 90 minutes. Set that as the integration
test step timeout. Increase the job timeout to 120.
Other PRs will make other adjustments and hopefully allow for these
numbers to be reduced or removed.
> adjust advance zq ci timeouts

- .github/workflows/ci.yml
We got a forked pull request! This change will allow pull requests from forks to run CI. 
If you're a member of brimsec and want CI, the previous behavior of getting CI on any push is gone. You now must open a pull request to get a CI run. The convention in brimsec/zq is to open a draft if you're not ready for review but need a CI run.
The behavior from forked repos works. Since zq was already set up this way, I created a toy PR from a fork that shows CI runs on the initial pull_request and also an additional commit. https://github.com/brimsec/zq/pull/940
> fix: run ci on pull_request

- src/css/settings/_colors.scss
- src/js/components/SpaceModal.js
- src/js/components/common/forms/InputLabelError.js
- src/js/flows/renameSpace.js
- src/js/types/styled.js
Fixes #900 
If zqd responds with an error, we show it in the form next to the label.
Whatever zqd returns as the {error: "message goes here"} is forwarded to the UI.
> Add error message for space renames

- .github/workflows/advance-zq.yml
- itest/lib/control.js
- itest/lib/newAppInstance.js
It was discovered long ago that weak-powered CI-hosted instances can't
guarantee elements are ready within the default 5s for Spectron. At the
time I just set a very high timeout of 60s. But it has been shown that
there are pathological cases where all tests can fail (broken zqd), and
the test system spends too much time waiting (60s * number of tests).
After #888, the right side of that expression is improved, but the timeout
of 60s remained. This PR fixes that.
I've done some sanity testing on both CI systems and lower-powered cloud
instances and propose this 60s timeout be shifted to 15s. This seems
high enough to still get successful runs but it greatly reduces the time
spent waiting if zqd is broken.
Note that by changing the timeout values inside the integration tests,
we can change …
> tests: adjust element-based timeouts from 60s to 15s

- src/js/components/IngestRefresh.js
- src/js/components/hooks/useThrottle.js
fixes #904 
This turned out to be a little tricky since there ended up being a few culprits:
1. My change [here](https://github.com/brimsec/brim/blob/f5a37b2f786e913bb3d216e1ca56a90840964220/src/js/flows/initSpace.js#L35) prevented a new search to be saved to history every time we switch spaces. I did this because the history view would get diluted with a bunch of empty searches that didn't mean anything to the user, but by removing that this `<IngestRefresh />` component was no longer getting updated properly since the existing effects we have setup were depending on the `historyCount` changing to know when we have switched spaces. So when switching spaces after the change linked above, the `snapshotAck` would not get `ack()`ed like it had been before. The solution then was to add a new …
> clear snapshot on space change

- CONTRIBUTING.md
- docs/Code-Base-Walkthrough.md
- docs/Home.md
- docs/_Sidebar.md
@jameskerr wrote some great markdown to use as the "Code Base Walkthrough" for new developers. Here I'm staging it in the `docs/` directory such that our GitHub Actions will deploy it to the appropriate location in the wiki.
I've also added a link to the wiki doc from our `CONTRIBUTING.md` so hopefully more developers will find it. When the video archive from [tomorrow's webinar](https://brimsec.slack.com/archives/C010DR0HHMF/p1593975624467400) is posted, I'll circle back and add links to that as well.
> Stage "code base walkthrough" doc for wiki deployment

- src/js/electron/autoUpdater.js
fixes #902 
Wanted to get this one in for the next release, points to download page instead of github releases
> go to download page instead

- docs/Home.md
- docs/_Sidebar.md
Seeing https://github.com/brimsec/brim/pull/921 under review made me realize that we're probably due to split the wiki into a few sections so different audiences can more easily find the specific stuff they're looking for. Specifically, that PR will bring us to the point where we'll have multiple docs targeted at developers, which is definitely a targeted audience. While I was at it, I realized that Support-like stuff (general use info folks should know before filing bugs) is different from User docs (detail on how to effectively use certain features) so I've split those out while I'm at it.
If you want to see an example of what this looks like rendered in the wiki, check out https://github.com/philrz/scratchwiki/wiki.
> Split wiki into sections

- scripts/download-zdeps/index.js
> Use Zeek v3.2.0-dev-brim4 to enable geolocation support

- acknowledgments.txt
While this attribution is covered via https://github.com/brimsec/geoip-conn/blob/master/README.md, I figure it's good to avoid the level of indirection and also give the attribution up front in the Brim app itself.
> Mention MaxMind/GeoLite2 in acknowledgments

- .github/workflows/advance-zq.yml
- .github/workflows/linux-release.yml
- .github/workflows/macos-release.yml
- .github/workflows/win-release.yml
Deno is needed anywhere we `npm install` the Brim repo. I forgot to add it to the remaining workflows in github actions.
It seems that we duplicate a lot of the Brim setup across five of our workflows. It might be a good idea soon to create our own action that can be reused called `brimsec/setup-brim@v2`.
But for now this just adds the `setup-deno@v2` to each of the workflows.
> Add deno install to remaining workflows

- .flowconfig
- src/js/brim/flatRecordsBuffer/index.js
- src/js/brim/flatRecordsBuffer/nestedRecord.js
- src/js/brim/flatRecordsBuffer/test.js
Updated the code that "flattens" nested records to work with nests more than 1 level deep.
fixes #933
> Nested records more than one level deep

- scripts/download-zdeps/index.js
> Point to Zeek v3.2.0-dev-brim5

- docs/Troubleshooting.md
Of course, it was only _after_ I merged https://github.com/brimsec/brim/pull/939 that I noticed this typo. 😄
> Fix typo in Logs section of Troubleshooting doc

- itest/tests/zar.test.js
Multiple writing operations to a zar archive aren't supported yet, so
remove this unneeded concurrent index creation that caused a sporadic
test failure.
> remove unneeded and unsupported parallel index creation

- src/js/components/Investigation/FindingCard.js
- src/js/components/Investigation/FindingCard.test.js
- src/js/components/SearchPage.test.js
- src/js/test/helpers/provide.js
Now when you click the "x" on a history entry, it removes that entry and does not issue a search. Fixes #947 
The issue was that a nested click handler was not stopping the event propagation.
Unit tests have been added to ensure this doesn't regress.
> Fix deleting a history item issuing a search

- scripts/download-zdeps/index.js
> Point to Zeek v3.2.0-dev-brim6

- CHANGELOG.md
- package-lock.json
- package.json
https://github.com/brimsec/brim/compare/v0.13.1...d88d1d4a128b90e29edcc93d4fe3313974311f82
There also were some packages being accessed via `http://`, and when I did `npm install https://github.com/brimsec/zq#v0.18.0` to update the `zq` pointer, it corrected those to `https://` as well. Since I know we'd been standardizing on `https://` in the past for obvious reasons, I let those changes roll into here as well.
> Update zq to v0.18.0 and prep v0.14.0

- .eslintignore
- src/js/flows/__snapshots__/submitSearch.test.js.snap
- src/js/flows/submitSearch.js
fixes #841 
Don't update the table unless a different search has been submitted
> 841 remove blank record flash

- itest/tests/zar.test.js
- package-lock.json
- package.json
- src/js/zqd/zqd.js
From the merging of brimsec/zq#1072 where the -datadir flag was renamed -data
> Fix advance zq: change -datadir flag

- src/js/components/TabContent.js
We can now run zqd so that it stores all of its data (including spaces & their data) in S3, and we were using a zar archive. For dev/testing, it'd be convenient now to allow typical zql searches against an archivestore space.
> Temporarily enable normal searching of an archive space

- itest/tests/zar.test.js
- src/css/_saved-spaces-list.scss
- src/js/components/SavedSpacesList.js
The progress bar now will only ever take 33% of the width, it will always be on the right side. The text line height has been changed to an even number so that it centers vertically.
> Space List Item Alignment When Ingesting

- src/js/brim/ingest/getParams.js
- src/js/brim/ingest/test.js
- src/js/flows/ingestFiles.js
- src/js/lib/uniqName.js
- src/js/state/Spaces/selectors.js
It was a poor user experience to import a pcap with the same name and get a "there is already a space with this name" error. Now we add a numeric suffix to the name if it already exists. I've also removed the `.brim` suffix since "brim folders" are no longer a thing. This uniq function will also help when we are create subspaces.
It also works if you provide a custom data dir option to Brim.
> Uniqly Generate Space Names

- zealot/api/mod.ts
- zealot/api/subspaces.ts
- zealot/fetcher/fetcher.ts
- zealot/test/error_test.ts
- zealot/test/subspace_test.ts
- zealot/types.ts
- zealot/util/error.ts
- zealot/util/utils.ts
- zealot/zealot.ts
Relates to #926 
Hit the subspace create api with zealot. The endpoint was put in place through this PR https://github.com/brimsec/zq/pull/854
It looks like:
```
POST /space/{parent_space_id}/subspace
{
"name": "<name>",
"open_options": {
"log_filter": ["logid1", ...]
},
}
```
> Add subspace endpoint to zealot

- src/js/brim/field.js
- src/js/brim/field.test.js
Fixes #887 
We now turn all backslashes into escaped backslashes when manipulating the search input.
For example: 
```
CN=*.hs.llnwd.net,O=Limelight Networks\, Inc.,L=Tempe,ST=Arizona,C=US,serialNumber=nWN8nk7zDz13jhftc2SuuqMXZx2v8hZK
```
Becomes
```
CN=*.hs.llnwd.net,O=Limelight Networks\\, Inc.,L=Tempe,ST=Arizona,C=US,serialNumber=nWN8nk7zDz13jhftc2SuuqMXZx2v8hZK
```
> Escape backslashes in strings

- src/js/brim/field.js
My first attempt to verify #887 with just the fix in #993 was a failure because my repro case happened to be a field value containing _two_ backslashes. Only the first backslash was being escaped and so a parse error was still triggered. I'm not claiming JavaScript expertise, but following the info I found online and mimicking the working replacement that we already have in there, I was able to put up this one-character fix. 😅 
Fixes #887.
> Make sure backslash escape is global

- src/js/components/hooks/useDoubleClick.js
- src/js/components/useSearchShortcuts.js
Two small changes here:
1. Because of React's [Event Pooling](https://reactjs.org/docs/events.html#event-pooling) which actually will be removed in [Version 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling), anytime we save an event in an asycronous way, we need to call `event.persist()`.
2. The mousetrap bindings to switch tabs were not working consistently with the new constructor pattern, so I added them to the document Element. All seems to work well now.
> Persist event in useDoubleClick

- scripts/download-zdeps/index.js
> Point to Zeek v3.2.0-dev-brim7

- package.json
- src/js/components/SearchResults/ResultsTable.js
- src/js/flows/viewLogDetail.js
Fixes #1005 
We were opening the log detail window before we were saving the log to the state. This now makes sure we push that log detail into the state before opening the detail window.
It also prevents the log detail state from pushing a duplicate log entry.
> Double click bug

- .importjs.js
- src/css/_log-viewer.scss
- src/css/_toolbar-button.scss
- src/js/brim/interop.js
- src/js/brim/record.js
- src/js/flows/createSubspace.js
- src/js/flows/createSubspace.test.js
- src/js/flows/refreshSpaceNames.js
- src/js/initializers/initStore.js
- src/js/state/Spaces/types.js
- src/js/state/Tabs/flows.js
- src/js/state/Tabs/reducer.js
- src/js/state/Tabs/test.js
- src/js/state/Tabs/types.js
- src/js/state/Viewer/actions.js
- src/js/state/Viewer/selectors.js
- src/js/state/Viewer/types.js
- src/js/state/types.js
- src/js/test/initTestStore.js
- src/js/types/records.js
This PR adds a new thunk called `createSubspace()`. It grabs the selected records from the viewer and issues the api call to zqd with the expected parameters. It doesn't add any UI, just preps the app with the new function and corresponding tests.
This PR also puts the `globalDispatch` method in the third parameter of the Thunk function signature. This makes it much easier to stub out in tests. Thunks now look like:
```js
type Thunk = (dispatch, getState, {zealot, globalDispatch}) => any
```
In the tests, we mock `globalDispatch` with the normal `dispatch` function so that it does not make any ipc calls to electron. The testing framework doesn't know about the electron APIs.
> Create Subspace Flow

- src/js/electron/tron/window.js
- src/js/initializers/initCleanup.js
- src/js/search.js
closes #994 
Storing the "detail" window name in the search query params allows us conditionally decide if it is appropriate to delete partial spaces.
This was also occurring upon refresh of the detail page since the same event gets fired.
> No cancel on closing detail

- src/css/_column-chooser.scss
- src/js/components/ColumnChooserMenu.js
- src/js/components/SearchInput.js
This PR implements #949 and #975.
I think it still needs a few last touches and discussion. 
I wasn't sure what to do with the styling of the input field. I considered styling it like the main search field, but that takes up a lot of space. So input is appreciated on this.
Second part is the sorting of the column names. From Phil's issues I know there is some discussion on this. So maybe we can continue that discussion here and choose an approach. 
I also think that the top of the column chooser is taking up quite a lot of real estate due to white space as it is right now. 
Maybe we could replace the select all and deselect row with a checkbox above the other check-boxes and before the new search input field. I believe it's done more often that way and compresses the header a bit. …
> Column chooser sorting and searching

- src/js/flows/fetchNextPage.js
- src/js/flows/fetchNextPage.test.js
When fetching the next page, the time span was being mutated causing weird bugs like the packet button not lighting up when clicking on a record. This also explains why it was working fine in the detail view. The span was not mutated there I suppose.
Fixes #979
> Fix bug where span was mutating

- src/js/components/SearchInput.js
- src/js/electron/menu/__snapshots__/appMenu.test.js.snap
- src/js/electron/menu/appMenu.js
While verifying #982 I was confronted with how the wording of the current option "Syntax docs" in the "..." menu is a bit vague and also out of sync with the equivalent in the **Help** pull-down that said "Query Syntax Docs". Since we now have no shame in calling the query language by its official name "ZQL", here I'm proposing going ahead and changing both to say "ZQL Syntax Docs". To maintain style with what's already in each menu, I maintained the "all caps" appearance that was in the pull-down menu and the "capitalize first word" approach that was in the "..." menu.
Once I did _that_ I also noticed how the "Submit Issue..." link was going straight to open an issue on GitHub, but we now have a more helpful wiki article that would help a user gather info and better craft their issues, …
> ZQL docs links & better link for opening issues

- package-lock.json
- package.json
It looked like we had one of our timing issues yesterday where two zq PRs merged closed together and stepped on each other's automation to update the zq pointer in Brim. I had high hopes of verifying an issue in Brim `master` that's dependent on one of those merges, and nobody's yet merged other zq PRs, so I got impatient and and putting this one up to confirm if the CI will pass & if so merge this to unblock myself.
> zq update through "add warnings channel to pcap-ng reader and report through zqd api (#1178)"

- scripts/download-zdeps/index.js
> Point to Zeek v3.2.0-dev-brim8

- src/js/brim/ingest/detectFileType.js
Fixes #1068.
Now the (unzipped) [pings.pcapnano.zip](https://github.com/brimsec/brim/files/5209860/pings.pcapnano.zip) can be successfully imported.
[Success.zip](https://github.com/brimsec/brim/files/5209873/Success.zip)
I'll also look at adding an automated test in the zq repo that works with this file format.
> Add file signature for nanosecond pcap to accepted list

- scripts/download-zdeps/index.js
> Point to Zeek v3.2.0-dev-brim9

- .github/workflows/linux-release-candidate.yml
- .github/workflows/linux-release-promotion.yml
- .github/workflows/macos-release-candidate.yml
- .github/workflows/macos-release-promotion.yml
- .github/workflows/win-release-candidate.yml
- .github/workflows/win-release-promotion.yml
The changes here create the build artifacts in one Actions Workflow that finishes with putting them on a Google Cloud Storage bucket from which they could be downloaded and smoke tested. If/when a decision is made to "promote" them to GA, a separate Actions Workflow copies the artifacts from the bucket to the GitHub Releases page.
---
Today the only way I know of to make release artifacts come out of our build system is to create a tag named `v*`, which results in not only the creation of the artifacts but also uploads them to the GitHub Release page for the repo. However, we've made dud artifacts in the past, so we always perform smoke tests before wanting external users to start downloading and using them. Exposure from this is limited by marking it as "Pre-Release" when creating the …
> Separate release candidate creation from promotion to tagged downloadable releases

- docs/Troubleshooting.md
With the fixes in #1069 and https://github.com/brimsec/zq/pull/1243, we're now working around the fact that Zeek doesn't preserve the full precision of nanosecond timestamps when they appear in pcaps. Should users notice this when comparing their timestamps in Brim with the extracted flows in Wireshark, here I'm adding a link to the open Zeek issue so Brim users know that's the root cause of the truncation.
> Mention nanosecond timestamp issue in Troubleshooting wiki article

- CONTRIBUTING.md
- README.md
- docs/Code-Base-Walkthrough.md
- docs/Geolocation.md
- docs/Troubleshooting.md
- docs/Zeek-Customization.md
- docs/Zeek-JSON-Import.md
- docs/_Footer.md
- src/js/electron/menu/appMenu.ts
We recently added a redirect layer on the https://www.brimsecurity.com/ web site such that the `#` icon for joining Slack is attached to a permanent URL https://www.brimsecurity.com/join-slack/ which, in turn, redirects to the current "invite yourself" URL, which might change after 2000 users invite themselves or Slack expires it due to some glitch (it's happened before). Here I change all the Slack URL pointers such that if the "invite yourself" URL changes again in the future, we only have to update it in that one place on the web site.
> Better Slack URL

- scripts/download-zdeps/index.js
> Point to Zeek v3.2.0-dev-brim10

- src/js/flows/refreshConnectionsSpaceNames.ts
- src/js/flows/refreshSpacesForAllConnections.ts
- src/js/initializers/initIpcListeners.ts
- src/js/initializers/initZqdConnection.ts
- src/js/state/Clusters/reducer.ts
fixes #1079 
When loading up the app from a previously saved state, we have still been assuming that the connection will either default to localhost:9867, or that the app has just created a new connection, but it was not properly handling the case where it had already created a new connection from a previous session. This PR aims to fix that by checking for and using any previously set connectionIds and will also populate spaces for all known connections.
> refresh all connection spaces

- scripts/download-zdeps/index.js
This does increase the size of the Brim release artifact by 7-11%, but the times users have had to download `zq` separately to get these tools for debug/functionality it creates hassle as well as possible hazard, should they pick an incompatible version. Therefore I think it's worth the tradeoff.
Here's validation that the `zdeps/` gets populated in my local Dev environment after doing `npm install` with this branch:
```
$ ls -l brim/zdeps
total 225808
-rwxr-xr-x  1 phil  staff  18349360 Sep 27 11:11 pcap
-rwxr-xr-x  1 phil  staff  23451128 Sep 27 11:11 zapi
-rwxr-xr-x  1 phil  staff  21796624 Sep 27 11:11 zar
drwxr-xr-x  5 phil  staff       160 Sep 27 11:11 zeek
-rwxr-xr-x  1 phil  staff  21306408 Sep 27 11:11 zq
-rwxr-xr-x  1 phil  staff  30701240 Sep 27 11:11 zqd
```
Here's similar …
> Include pcap, zapi, and zar in zdeps/

- scripts/download-zdeps/index.js
To take advantage of Brim Zeek artifacts now being based on GA Zeek v3.2.1, and also to take advantage of updated [geoip-conn](https://github.com/brimsec/geoip-conn) that includes latest GeoLite2 database.
I started this out as a draft PR to make sure that the integration tests pass, and indeed they do. So if we trust our automation, I guess we're ready to merge and start getting some soak time with this in the days up to building the next GA release.
> Point to Zeek v3.2.1-brim1

- scripts/download-zdeps/index.js
To take advantage of Community ID now being added to Zeek `conn` events.
> Point to Zeek v3.2.1-brim2

- src/js/flows/ingestFiles.test.ts
- src/js/flows/ingestFiles.ts
Fixes #1028 
Based off #1108 (that must go in first, but you can look at the last commit here to see the changes)
The app will now respond to PcapPostWarning the same way that it responds to LogPostWarning. The warning will appear in the bottom right of the page after ingest has finished.
A unit test has been added to avoid regressions.
> Handle PcapPostWarning in Brim

- .github/workflows/ci.yml
- docs/Code-Base-Walkthrough.md
- zealot/test_api/subspace_test.ts
This Brim tests looks for an error message that changed in brimsec/zq#1461. 
While we should update this test to work differently, this change should allow tests to pass against the zq master after #1137 lands. I'll update this PR then to point zq at zq master.
> fixes for brim integration tests

- src/js/electron/menu/searchFieldContextMenu.ts
- src/js/flows/rightclick/cellMenu.test.ts
In the ZJSON changes, we retained the nested-ness of the data, but added a "flatten" method to convert all the nested field to be flat with "." separator like Zeek. We use this flatten method for the columns in the results table.
The "pivot to logs" field menu option is only enabled when the columns in the table match the columns in the right-clicked record's. This bug revealed that the records columns were still nested. The fix is to flatten first, then compare.
Bug example:
```
Table columns: ["count", "id.resp_h"]
Record columns: ["count", "id"]
```
Fixes #1141
> Flatten columns when comparing to table columns

- .github/workflows/ci.yml
- .github/workflows/linkcheck.yml
- docs/Microsoft-Windows-beta-limitations.md
The automation for the link checker has been doing its job insofar as it's noticed when external links go bad or act flaky. However, it's also been correctly noted that having it run as a Job in the same Action with the rest of `ci.yml` can be troublesome, since it makes it more difficult to debug when there's link problems at the same time as legit code breakages, or CI infra instability.
To address this, here we break out the link checker to its own separate Actions Workflow.
> Move link checker to separate Actions Workflow

- src/js/electron/window/dimens.test.ts
- src/js/electron/window/dimens.ts
In my math for position the windows on an external display, I didn't add the screen.x to the screen.width when determining what the "max" value an x can be. (Same with y).
Test added from @philrz debug logs. Thanks!
Fixes #1041
> Fix value of max X and max Y

- src/js/electron/window/dimens.test.ts
- src/js/electron/window/dimens.ts
Third try fix #1041 
If a screen had an x or y that was not zero, some parts of the code broke. So we subtract the screen.x from the desired window.x, to effectively make the screen x and y both 0. Then all the math is easier. Then we add back the screen.x at the end.
Added more tests to fix the bugs in the comments of the ticket.
> Stack windows correctly on non-zero x,y screens

- src/css/_tab-bar.scss
- src/css/_text-content.scss
- src/js/components/DebugModal.tsx
- src/js/components/ModalDialog/ModalDialog.tsx
- src/js/components/SearchPage.tsx
Here is an experiment for a new way to structure our modals. The goal is to give them more flexibility, while making it easy to still look consistent.
As part of the experiment, I re-did the "Debug Query" modal to use this new "ModalDialog" component. It has an enter and exit animation using CSSTransition, it pops down below the tab bar, it has a "Scrollable" container for content that can get very long, it has a footer component for the row of buttons, and it locks the rest of the screen using "pointer-events: none" on the body element when it's opened.
> A modal dialog experiment

- src/css/_info-notice.scss
- src/js/components/Notice.tsx
This a temporary fix to make two different ways of doing a "Notice" not overlap. I just moved one version below the other version.
In the future, I think we should change where the "Refresh" button is. I think it should be a different piece of UI with a progress bar and buttons to refresh or cancel or what not.
Fixes #1151
> No overlapping popups

- src/css/_notice-banner.scss
Fixes #1181 
The z-index of the tab bar changed from 1 to 2, so I've set the z-index of the yellow notice to 5.
> Make notice banner above tabs

- src/js/electron/brim.test.ts
- src/js/electron/brim.ts
- src/js/electron/main.ts
Fixes #1118 
Clicking the Brim icon on Mac now does nothing if there is already a window open (it focuses it). But if there are no open windows, it will create a new one when clicked.
The problem was some unnecessary parens that got added when we migrated to typescript. It tried to fix some where syntax. The first commit is the fix. The second commit is a small refactor and tests to ensure it doesn't appear again.
> Activate Bug

- scripts/download-zdeps/index.js
> Point to Zeek v3.2.1-brim3

- scripts/download-zdeps/index.js
To take advantage of fixed Community ID plugin and updated [geoip-conn](https://github.com/brimsec/geoip-conn) that includes latest GeoLite2 database.
> Point to Zeek v3.2.1-brim4

- CHANGELOG.md
- package-lock.json
- package.json
https://github.com/brimsec/brim/compare/v0.18.0...05e752f
The first attempt to make a `v0.19.0` release candidate yesterday (#1197) was a failure due to a late-found problem (https://github.com/brimsec/zeek/issues/46) with the Zeek artifact it was pointing at. The Zeek artifact has been repaired, so, giving this another go.
> Update zq to v0.23.0 and prep v0.19.0 (redux)

- src/js/electron/quitter.ts
- src/js/electron/tron/windowManager.test.ts
- src/js/electron/tron/windowManager.ts
fixes #1204 
When you close the last open Brim window, we automatically quit the app (unless you're on a Mac).
We are notified that the last window has closed using electron's event `app.on("window-all-closed")` [docs](https://www.electronjs.org/docs/api/app#event-window-all-closed).
When a window closes, it fires a "closed" event [docs](https://www.electronjs.org/docs/api/browser-window#event-closed). We use this event to dereference the window.
Strangely, electron fires these events in this order:
1. app => "window-all-closed"
2. browserWindow => "closed"
This led to calling a method on a browser window that was destroyed, but had not yet fired "closed" which would have caused us to dereference it.
To fix, I added a `windowManager.whenAllClosed()` method that will resolve when all …
> Wait For Windows to Close

- package-lock.json
- package.json
- zealot/src/api/logs.ts
In brimsec/zq#1336, the uri for posting paths for log ingest changes from
/space/:spaceid/logs to /space/:spaceid/logs/paths.
The previous uri will now serve and endpoint that allows for logs to streamed
over the network using http multipart forms.
> Update log post endpoint

- scripts/download-zdeps/index.js
(This is a companion PR to https://github.com/brimsec/zq/pull/1610, which would merge first once both are approved.)
Currently Brim's `scripts/download-zdeps` pulls down a specific Zeek artifact (and soon a Suricata one as well) to run tests and allows for the bundling of these artifacts with the app such that users can generate such logs on the desktop. zq similarly depends on the same artifacts during system tests to ensure pcaps posted to `zqd` produce expected log outputs.
Up until now, this all has meant updating the Zeek & Suricata tags in each repo separately, ideally keeping them always in sync. However, we already have linkage between the repos in the form of the [advance-zq.yml Action](https://github.com/brimsec/brim/blob/master/.github/workflows/advance-zq.yml) that gets …
> Use zq's Zeek tag as the downloaded dependency

- .github/workflows/advance-zq.yml
The automation that advances the Brim-side `zq` pointer in `package.json` whenever there's a merge to `master` in zq recently started experiencing errors, as shown in [this job output](https://github.com/brimsec/brim/runs/1408777023?check_suite_focus=true#step:21:35). The root cause is described in the article [GitHub Actions: Deprecating set-env and add-path commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).
It's a little tricky to tinker with this automation, since as the comments in [advance-zq.yml](https://github.com/brimsec/brim/blob/master/.github/workflows/advance-zq.yml) say:
> These events only trigger on the Github default branch (usually master).
Therefore I set up a quick personal scratch repo that does a very simple …
> Update create-pull-request pointer to @v3.4.1

- src/js/flows/ingestFiles.test.ts
- src/js/flows/ingestFiles.ts
- zealot/src/fetcher/fetcher.ts
- zealot/src/fetcher/iterator.ts
- zealot/src/zealot_mock.ts
If a pcap file is posted to a remote server the remote server will return 404
not found. The current error message was just name of the file. Update the
error message in this case to reflect that the server does not have to access
the file.
Related change:
- The zealot fetcher was not throwing an error if a stream request response was
a 404. Change so it does if the response is not ok.
Closes #1221
> Precise error message zqd pcap not found error

- src/js/brim/ingest/detectFileTypes.test.ts
- src/js/brim/ingest/detectFileTypes.ts
- src/js/brim/ingest/fileList.ts
- src/js/brim/ingest/getParams.ts
- src/js/brim/ingest/test.ts
- src/js/components/LoadFilesInput.tsx
- src/js/flows/exportResults.ts
- src/js/flows/getZealot.ts
- src/js/flows/ingestFiles.test.ts
- src/js/flows/ingestFiles.ts
- src/js/test/itestFile.ts
- zealot/package.json
- zealot/src/api/logs.ts
- zealot/src/enhancers/zngToZeek.ts
- zealot/src/fetcher/callbacks.ts
- zealot/src/fetcher/fetcher.test.ts
- zealot/src/fetcher/fetcher.ts
- zealot/src/fetcher/iterator.ts
- zealot/src/fetcher/pushable_iterator.ts
- zealot/src/fetcher/stream.ts
- zealot/src/ndjson/lines.ts
- zealot/src/ndjson/parse.ts
- zealot/src/ndjson/pipe_json.ts
- zealot/src/types.ts
- zealot/src/zealot.ts
- zealot/src/zealot_mock.ts
- zealot/test_api/ingest_test.ts
- zealot/test_api/search_test.ts
UPDATE:
I've added a new method to the fetcher called "upload". It uses XHR to make the request and track progress events. We still return an iterable stream of payloads which now include a message that looks like `{type: "UploadProgress", progress: number}`. This allows us to keep the progress bar unchanged as it was.
Fixes #1094 
This changes the log post method in the zealot client to make a multipart form file upload, instead of sending the paths of the files. The pcaps post endpoint has remained unchanged.
It is not easy to get a progress bar for this type of request (it's impossible ATM using the Fetch API, we'd have to rewrite that method with XHR). I think we didn't have progress for log uploads anyway.
@philrz when you verify this, upload a large log file (or set of log files) …
> Log endpoint uses multipart form

- src/js/components/ModalDialog/ModalDialog.tsx
- src/js/electron/main.ts
After disabling the hardware acceleration, the only issue revealed was the backdrop-filter css property. All the modals have a solid color background instead of the freakin-sweet background blur they used to have. Don't worry background blur, I will come back for you one day.
Fixes #1242 and #1218
🦜🦜 + 🪨 = ☠️☠️
> Disable gpu hardware acceleration

- docs/Home.md
- docs/_Sidebar.md
I made a mistake not realizing the backticks would mess up the linking. I've tested out the fix in a personal repo.
> Fix links in wiki for remote zqd article

- README.md
Now that we have the install guide in the wiki, we might as well link to it from the README.
> Mention install guide in README

- zealot/test_api/helper/test_api.ts
- zealot/test_api/search_test.ts
```
deno 1.6.0 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.2
```
Our CI is using a new version of Deno which requires explicit promise annotations. This PR adds those in.
> Add required promise annotations

- docs/Supported-Platforms.md
Up until now, our Supported Platforms statement has been primarily expressed in terms of where we run CI as well as the support statements from Go/Electron. However, the work on Suricata reminded us how there can be additional sensitivities in terms of shared libraries that may not be present in some platforms and hence will determine whether Brim can install and operate out-of-the-box on them.
I recently ran through a fairly extensive smoke testing exercise documented in #1263 that confirms where we stand on many platforms at this point-in-time as we're preparing to release Suricata. Therefore this PR attempts to make our support statement more current in line with the findings from #1263.
In terms of target audience and approach, I've tried to lead with a simple summary (e.g. a typical …
> Update Supported Platforms article

- docs/Supported-Platforms.md
Shortly after merging the improved Supported Platforms article, @mattnibs delivered the good news that we actually seem to run fine on M1-based Macs with the builds we currently produce. Obviously we don't have quite the level of confidence that we do about the Intel-based ones since we don't have access to M1-based Actions Runners and most of us are still running Intel-based ones on our desktops. But M1 is the way of the future, Apple seems committed to a seamless transition (thanks to Rosetta 2), and we probably don't want to give Brim users with M1 Macs the impression they can't play. Therefore, here I've revised the statement. Maybe it's a little ambitious, but if there's M1-specific bugs out there, I figure we're better off knowing than not knowing. I'm open to tweaking it if others …
> Adjust support statement for M1-based Macs

- package.json
- src/pkg/sectional/models/Controller.test.ts
- src/pkg/sectional/models/Controller.ts
Fixes #1256 
The "sectional" component distributes pixels evenly to all the sections on start up. It does this by adding 1 pixel to each section in a while loop. It stops when each section is at it's max, or when there is are more pixels left to distribute. `if (left === 0) break`
To check if each section is at it's max, it keep the leftover pixels from the previous iteration. If the current amount of pixels to distribute equals the amount from the previous loop, that means each section is at it's max, so break the loop. `while(prev !== left)`
What I didn't realize is that when you zoom in a window, you can have elements with a fractional height (421.365px). Because the distributor adds one whole pixel each loop, the remaining space variable never was exactly zero. Since the sections do …
> Round the pixels before distributing them

- src/js/electron/autoUpdater.ts
- src/js/electron/main.ts
fixes #1219 
Adds the same version check mechanism that we do for linux: if the latest version is *ahead* of the current version then don't update. This is not currently the default behavior of MacOS and Windows, and it is useful for building and sharing beta releases.
The other fix in here has to do with the autoupdate server: if the current version, which we encode in the server url, is the *same* as the latest version that we have in our github releases, then the server returns a 204 status. In my initial probing of the server I had mistakenly thought that the server still returned a body in this case (and contradicted its status) but the server actually does behaves restfully and does not return anything with that 204 code. This is why we were seeing the empty string in the error for …
> add autoupdate restrictions

- src/js/components/AddSpaceButton.tsx
- src/pkg/sectional/models/Section.test.ts
- src/pkg/sectional/models/Section.ts
If you pass `undefined` to a function with a default parameter, the default parameter will be used. However if you pass `null` to it, it will use `null` as the value.
The constructor of the Section model has a max parameter with a default value of `Infinity`. But when you serialize an object that contains `Infinity`, it gets converted to null.
```
> let myObject = {max: Infinity}
undefined
> JSON.stringify(myObject)
'{"max":null}'
>
```
So the next time we passed these serialized args to the constructor, the max value was set to `null` instead of `Infinity`. That caused an issue when "clamping" the size of the section, resulting in this bug.
I've added some tests.
fixes: #1281
> Set max to infinity if its null

- src/js/state/Spaces/actions.ts
- src/js/state/Spaces/reducer.ts
- src/js/state/Spaces/test.ts
- src/js/state/Spaces/types.ts
Fixes more of #1281 
The zqd spaces endpoint now returns partial `Space` objects for the list view, where it was previously returning full `Space` objects.
The code was replacing all the state with the returned Partial Space objects creating this NAN - UNDEFINED bug.
To fix, we now treat the spaces as partial, and merge them with whatever was there before.
> GET /space returns partial spaces

- CHANGELOG.md
- package-lock.json
- package.json
Our last attempt to bundle Brim GA release `v0.21.0` was aborted because of bugs found during smoke testing, which have since been addressed. This PR includes the CHANGELOG updates for the fixes to those bugs so we can make another attempt at tagging that GA release.
https://github.com/brimsec/brim/compare/v0.20.0...d81df63
> Update zq to v0.25.0 and prep v0.21.0 (redux)

- .github/workflows/markdown-link-check-config.json
- .github/workflows/markdown-link-check.yml
I don't know if GitHub has changed their website configs or if they've just been having a moment lately, but I've noticed some of the Markdown Link Check (MLC) jobs have failed occasionally with a flurry of HTTP 429 (Too Many Requests) errors https://github.com/brimsec links (example: https://github.com/brimsec/brim/actions/runs/430631383). I learned that the Action we use for MLC has a [setting](https://github.com/tcort/markdown-link-check#markdownlinkcheckmarkdown-opts-callback) that can make it react to this by retrying after the duration indicated by a `retry-after` header if one is provided, and if not, waits 60 seconds. This all seems like an improvement over being distracted by a failing job, so I've made the config here to enable that.
I tried to repro this in a personal repo so I …
> Retry link checks after HTTP 429

- zealot/config/json_types.ts
I compiled Zeek 4.0.0-rc1 and ran [print-types.zeek](https://github.com/brimsec/zeek/blob/master/brim/print-types.zeek) against it and found they've added one additional field beyond what we were covering in Zeek 3.x: A `source` field in `weird` events. While our current JSON typing system is hopefully not long for this earth, since users may start using Zeek 4.x before the new approach is complete, I've added the additional field here.
Incidentally, in the past I'd not really confronted the config duplication that appears to be in play here. I suppose if we were building this from scratch now, we'd extend the "zq as a dependency in `node_modules`" approach to have the contents of https://github.com/brimsec/zq/blob/master/zeek/types.json automatically reflected in the Brim-side config …
> Add "source" field to JSON typing config for Zeek "weird" events

- .github/workflows/linux-release-candidate.yml
- .github/workflows/linux-release-promotion.yml
- .github/workflows/macos-release-candidate.yml
- .github/workflows/macos-release-promotion.yml
- .github/workflows/win-release-candidate.yml
- .github/workflows/win-release-promotion.yml
I'm hoping to make some improvements to our build system in the near future. As a prerequisite to that, I've been wanting to address a mistake I made in a prior enhancement, hence this PR.
On the Google Cloud Storage bucket where release candidates first get staged, I chose a directory hierarchy `{platform}/{tag}/{artifact}`, e.g.:
```
$ gsutil ls -lR gs://brimsec-releases | grep "/rc-v0.22.0/"
gs://brimsec-releases/brim/linux/rc-v0.22.0/:
232745868  2021-01-07T00:08:16Z  gs://brimsec-releases/brim/linux/rc-v0.22.0/brim_amd64.deb
255494972  2021-01-07T00:08:14Z  gs://brimsec-releases/brim/linux/rc-v0.22.0/brim_x86_64.rpm
gs://brimsec-releases/brim/macos/rc-v0.22.0/:
373078075  2021-01-07T00:16:32Z  gs://brimsec-releases/brim/macos/rc-v0.22.0/Brim-darwin-autoupdater.zip
364312640 …
```
> Change bucket directory hierarchy for build artifacts

- itest/lib/appStep/api/ingestFile.ts
- itest/lib/appStep/api/waitForHook.ts
- src/js/lib/columnOrder.test.ts
- src/js/lib/columnOrder.ts
Actually fixes #1292 
Eventually, I'd like to display the events in the same order they come from the sever, then have a per-schema user preference to move the ordering around in the app. For now, we'll just continue with the less-optimal solution.
The logic is:
1. Gather all the unique columns from the schemas present in the results into an array
2. Grab the event_type column and force it to the front of the array
3. Do the same with the _path column
4. And finally do the same with the ts column
Unit tests have been added that show this is working now.
> Column order:  ts, _path, event_type

- CHANGELOG.md
- package-lock.json
- package.json
A previous attempt had been made to prepare a GA v0.22.0 release, but it was aborted during smoke testing due to a last-minute zq bug that has since been fixed.
The changes since that last attempt:
https://github.com/brimsec/brim/compare/2b45a97...af91d29
All changes since the last tagged GA release v0.21.1:
https://github.com/brimsec/brim/compare/v0.21.1...af91d29
> Update zq to v0.27.1 and prep v0.22.0 (redux)

- docs/Troubleshooting.md
In the past we had to advise users to drop to the filesystem and manually delete `appState.json` in order to clear app state to recover from a catastrophic bug. Thanks to work delivered in GA Brim tagged `v0.22.0`[🎉 ], there's now a user-friendly option to achieve this via **Window > Reset State** in the pull-down menu.
In this PR I've revised the Troubleshooting article to recommend this simpler approach instead.
---
> Revise Troubleshooting doc to mention Reset State

- src/js/electron/userTasks.ts
Since we changed the directory structure, the user tasks on windows were broken in dev mode. However they worked just fine on release builds.
> The proper appRoot in dev mode

- src/js/flows/search/handler.ts
- src/js/flows/search/response.ts
- src/js/flows/searches/viewerSearch.ts
Fixes: #1347
Thanks for catching this Phil. Geez, I think was with us since the big zjson update 3 months ago: https://github.com/brimsec/brim/pull/1108. The infinite scroll was mistakenly unfinished when the PR went in. Automated testing for this is a bit unclear to me at the moment. We could execute javascript within the spectron driver and set the scrollTop of the element to the max. Then wait until the fetch next page hook fires, then check the contents of the viewer. I want to write these tests now, but I'm feeling pulled to work on the security dashboard.
Thankfully, one of the bug was something typescript could have caught. I've restructured the SearchResponse class in away that typescript understands. After doing that, the compiler revealed the bug:
I think some better unit tests …
> Infinite fix

- itest/tests/contextMenu.test.ts
When using archive store by default, this test failed as it the data file it uses as the same timestamp for all its records.
> ensure contextMenu itest uses sorted data

- .github/workflows/linux-release-candidate.yml
- .github/workflows/macos-release-candidate.yml
- .github/workflows/win-release-candidate.yml
This PR allows for creation of "ad hoc builds" based on the current state of Brim `master`. These are signed and made available for all supported platforms just like our regular GA builds.
There's two ways these are currently triggered:
1. On-demand, by clicking the **Run workflow** pull-down on Actions (aka "workflow_dispatch" mode)
2. Automatically every night at 12:05 AM Pacific time (aka "schedule" mode)
Once the builds are created and available, a message is sent to a **#releases** channel on Slack where users are notified of the availability. Link text offered is of the format `gs://` to reflect that they're on a Google Cloud Storage bucket, but they're hyperlinked to point to the `https://` path which publicly-expose buckets.
I've tested this all out on a personal fork of the Brim …
> Enable creation of ad hoc builds (on-demand and nightly scheduled)

- src/css/_settings-modal.scss
fixes #1364
The restart required text was previously obscured. It now is a little smaller, positioned better, and always above it's file input.
> "Restart Required" text fix

- src/js/components/LogDetails/Md5Panel.tsx
- src/js/electron/tron/session.test.ts
- src/js/flows/ingestFiles.test.ts
fixes #1361 
The md5 correlation search was only being run when the component was mounted. It now will correctly run each time the md5 value changes.
I think the whole detail pane was unmounted and remounted with the "key" attribute. Now it stays mounted and only updates what it needs to. This Md5 component was not updated to account for that.
UPDATE
CI bumped into the bug where the appState.json file is missing in the unit tests. We see this failure occasionally. I've discover that two test files are both competing to delete a top level "tmp" directory. Now, each tests creates its own tmp dir using os.tmpdir(). 
fixes #1295
> Run the search each time the md5 changes

- src/js/components/ExportModal.tsx
fixes #1332 
I guess the Mac tags feature doesn't work with the current electron. So I'm disabling here.
https://www.electronjs.org/docs/api/dialog#dialogshowsavedialogbrowserwindow-options
Before
After
> Disable Mac Tags on Export

- app/core/Data.tsx
- app/detail/Fields.tsx
- ppl/detail/Correlation.tsx
- ppl/detail/RelatedAlerts.tsx
- ppl/detail/RelatedConns.tsx
- ppl/menus/detailFieldContextMenu.ts
- ppl/menus/searchFieldContextMenu.ts
Fixes #1304 
A simple but missing feature. 
Also added a "Copy" menu option to all the values in the detail pane.
There may be a better way to set a single context menu handler for all generic text, but this will do for now.
> Add right click "copy" to search and detail fields

- src/css/_field-cell.scss
fixes #1375 
Clicking right click then copy in the main viewer will now copy the whole value, instead of just a single word.
> Right Click => Copy Fix

- docs/Troubleshooting.md
A community user on public Slack [reported a problem](https://brimsec.slack.com/archives/C010DR0HHMF/p1611371926002900) with the **Packets** button not working as expected on Debian 10. While they figured out the problem themselves, they made the helpful suggestion that we could use their experience to improve the Troubleshooting article in the wiki. I've drafted those improvements here.
Since we now bundle the `pcap` tool with Brim (we didn't in the past) I was able to improve that part of the doc as well to save users the hassle of separately downloading the `zq` toolset.
> Improve docs for pcap open failures

- src/js/electron/tron/migrations.ts
- src/js/state/migrations/202101201109_moveQueriesStateToGlobal.test.ts
- src/js/state/migrations/202101201109_moveQueriesStateToGlobal.ts
fixes #1386
This edit's an existing migration. Since migrations don't go backwards, you'll need to clear you app state, open v0.22.0, then save the state with no windows, then upgrade to v0.23.0 and see that the query library is populated.
> Account for No Windows when Migrating Queries

- bin/generator/migration.js
- src/js/electron/tron/migrations.test.ts
- src/js/electron/tron/migrations.ts
- src/js/state/migrations/202007091803_forceLeftSidebarDefaultOpen.test.ts
- src/js/state/migrations/202007140829_defaultColumnHeadersToAuto.test.ts
- src/js/state/migrations/202007151457_addScrollPosToSearchRecord.test.ts
- src/js/state/migrations/202008031645_removeViewerSlice.test.ts
- src/js/state/migrations/202008121645_moveDataFromSearchToCurrent.test.ts
- src/js/state/migrations/202008191031_changeZqdClusterIdToHostPort.test.ts
- src/js/state/migrations/202008271352_addTargetToSearchRecord.test.ts
- src/js/state/migrations/202009121941_refactorInvestigations.test.ts
- src/js/state/migrations/202009231326_removeLogDetails.test.ts
- src/js/state/migrations/202010191355_addConnectionNameDefault.test.ts
- src/js/state/migrations/202010191355_addConnectionNameDefault.ts
- src/js/state/migrations/202011060944_removeClustersStatus.test.ts
- src/js/state/migrations/202011141515_addSuricataRunnerPref.test.ts
- src/js/state/migrations/202011141515_addSuricataUpdaterPref.test.ts
- src/js/state/migrations/202012011232_sidebarSections.test.ts
- src/js/state/migrations/202012021127_addQuerySection.test.ts
- src/js/state/migrations/202101051511_initQueryLibrary.test.ts
- src/js/state/migrations/202101151201_addMainView.test.ts
- src/js/state/migrations/202101201109_moveQueriesStateToGlobal.test.ts
- src/js/state/migrations/202101210823_renameToWorkspace.test.ts
- src/js/test/helpers/migrate.ts
While reviewing the diff between the last release and master, I found a migration test that should have failed but was passing. The reason was because this particular migration was dependent on the previous migration and tests only exercise a single migration function at a time, so they did not catch the bug. 
In reality, a "batch" of migrations get applied at a time. So I've added a helper function in the migration tests.
```js
const nextState = await migrate({state: "v0.22.0", to: "20210101000"})
```
This function will read the test state file called "v0.22.0.json", look at the version attached that that state, then run all migrations between the version and the "to:" parameter, returning the migrated state.
This is much closer to the way migrations are run in production and should add …
> Upgrade Migration Testing

- .github/workflows/notify-master-failure.yml
Add job that will notify HQ Slack should a failure occur on brim master.
> Notify slack on master branch ci failure

- src/pkg/sectional/components/Sectional.tsx
Fixes #1384 
They previously were not providing the default isOpen value. They were using the data passed in which omitted the isOpen value.
> Provide the correct data to the sidebar sections

- src/js/components/ExportModal.tsx
fixes #1346 
The `react-hot-toast` component we use to indicate the loading state during export has a default timeout of 30s, after which it will dismiss itself. This comes off as an indication to the user that the export is complete even though it may not be (and then when it finally does complete the "Export Complete" toast happens but the user would not expect it since the loading was already dismissed). Allowing the toast to persist indefinitely is not yet a feature of the toast lib, though this happened to have been requested a couple of days ago and there is already a PR to enable it in their pipeline (see https://github.com/timolins/react-hot-toast/pull/37 and https://github.com/timolins/react-hot-toast/issues/36). In the meantime, we can set the duration to int32 max which is the …
> Don't burn the toast 🔥 🍞 

- .github/workflows/notify-master-failure.yml
In #1427 I modified our Actions Workflows so failure notifications for the markdown link checker would go to a separate `#docs` channel on Slack. I neglected to exclude it from the "Notify master failure" Workflow, though, so notifications were still prone to leaking out. I tested this exclusion out in a personal repo and it seems to do the trick.
There's a companion PR in the zq repo https://github.com/brimsec/zq/pull/2078 that makes the same change, so if you're approving this one and can approve the other as well, that would be appreciated!
> Exclude markdown link check from Slack notify to #test

- ppl/summary/summary.tsx
- src/js/state/Boards/index.ts
- src/js/state/Boards/test.ts
- src/js/state/Tiles/index.ts
- src/js/state/Tiles/test.ts
- src/js/state/globalReducer.ts
- src/js/state/rootReducer.ts
- src/js/state/types.ts
Before we release, I'm backing out some changes we made to the state for the unfinished security summary feature. I'd rather avoid a migration when we ship the security summary.
This is all hidden behind a feature flag which still works. The tiles are now effectively hard-coded for the time being.
When the security summary ships:
> Remove Security Summary From State Until Shipped

- .github/workflows/advance-zq.yml
Only upload integration artifacts if the workflow has failed and the
integration test was the failure. The current logic was causing a "directory
not found" failure in the upload artifact step when the unit test failed and
the integration test step was not run.
> integration test: only upload artifact if fail

- package-lock.json
- package.json
The React DevTools are broken in version 8 - 11. The fix is in electron master. This helps us get up to speed when the fix is in.
> Upgrade eletron to 11.2.1

- src/js/components/IngestWarningsModal.tsx
- src/js/flows/deletePartialSpaces.ts
fixes #1070 
adjusts the ingest warning message and order, per the ticket's suggestion
> adjust ingest warning message

- src/js/flows/deletePartialSpaces.test.ts
- src/js/flows/deletePartialSpaces.ts
fixes #1337 (th3 m05t l337 t1ck3t 3v3r)
When closing brim and deleting partial spaces, check if the current spaceId is among those being cleaned up, if so then clear it's current spaceId.
> clear current spaceId if partial deleting

- docs/Troubleshooting.md
We've had a couple Windows users report that rebooting fixed the "Connection Error" problem. Assuming this might keep happening (sigh!) I figure it should be called out explicitly here with the link to #1490 rather than making them keep coming to Slack every time.
> Add paragraph pointing to Windows reboot workaround

- .github/workflows/linux-release-candidate.yml
- .github/workflows/macos-release-candidate.yml
- .github/workflows/win-release-candidate.yml
This is just a cosmetic thing, but I think it kind of matters. When I was last overhauling the build system in #1358, I put the word `master` in the version strings for the ad hoc builds. This is correct most of the time since typically the ad hoc builds are triggered nightly based on the latest commit in `master`. However, when I recently used the "Workflow Dispatch" approach to trigger an ad hoc build on a Dev branch, I confused myself when I saw `master` in the build string next to a commit hash for that branch.
Here I'm instead using the word `prerelease`. I figure in the rare cases that we hand these builds to users for test/debug purposes and they happen to look at the "About" info, that word more clearly communicates its non-official nature. For those of us using these builds …
> Say "prerelease" in version string, not "master"

- ppl/detail/Correlation.tsx
- ppl/detail/flows/fetch.ts
- ppl/detail/flows/get-correlation-query.test.ts
- ppl/detail/flows/get-correlation-query.ts
- src/css/_error-boundary.scss
- src/js/components/AppErrorBoundary.tsx
- src/js/components/RightPane.tsx
- src/js/detail.tsx
- src/js/search.tsx
- src/js/searches/programs.test.ts
- src/js/searches/programs.ts
Fixes #1475
This PR adds a check for the "ts" and "duration" fields before trying to access them. This is done when fetching data for the waterfall. We can't assume that data has a certain shape anymore, now that we can accept multiple sources.
I also added an error boundary around the log detail pane. If an error like this occurs again in the detail pane, the rest of the app will still be usable. Here is what it looks like:
> Robust Detail Pane

- itest/README.md
The nightly markdown link checker flagged that these jest links started failing. Closer inspection shows they've been moved to an "archive.jestjs.io" URL. Since these were pointing to a 24.x version and I see our own `package.json` has us pointing at jest 26.x, pointing to an older static release was probably not serving us well. The new links I'm proposing here apparently resolve to whatever's the "Current version (Stable)", which I assume we'll probably stay roughly in sync with anyway (it happens to match the 26.x we're using at the moment in `package.json`, so, seems as good a choice as any.)
> Fix links to jest docs

- src/js/brim/program.test.ts
- src/js/flows/submitSearch/__tests__/events.test.ts
- src/js/searches/histogramSearch.ts
- src/js/state/Search/test.ts
This commit fixes up brim with changes to deal with the changes
in zq for the new duration syntax used by "every".
> fixes for new "every" duration syntax

- docs/Code-Base-Walkthrough.md
The markdown link checker caught this as broken last night. It's still broken now and I clicked around and found what I think is a new home for the same page we used to link to.
> Fix link to immerjs.github.io

- app/workspaces/show.tsx
- itest/lib/createTestBrim.ts
- itest/tests/workspaces.test.ts
- src/js/@types/global.d.ts
- src/js/components/WorkspacePicker.tsx
- src/js/initializers/initGlobals.ts
Added a global function called `navTo(path)`. You can use this in the dev tools to go to a specific url. 
If you open the dev tools and type `navTo("/workspaces/does-not-exist")`, then you will reproduce the bug reported at #1529.
A simple null check fixed it. An integration test has been added to check for this now.
> Missing workspace bug

- .github/ISSUE_TEMPLATE/bug_report.md
I noticed that the issue template apparently pre-dated our addition of Linux support, so I've revised it along with some other formatting corrections.
> Revise issue template

- CHANGELOG.md
- docs/Remote-zqd.md
The changes in brimdata/zed#2563 caused the nightly Markdown link checker to see a breakage in the Brim changelog, so I've addressed that here by pointing to the new anchored section for `zapi` in the updated Zed README. While I was at it, I found a zapi reference in the wiki docs that wasn't broken, but I've updated to the same new link destination since it's now the home of the meaningful zapi content.
> Fix links to zapi description

- docs/Remote-zqd.md
The site for the pcap archive at [https://archive.wrccdc.org](https://archive.wrccdc.org/) has been unreachable for several days, which sets off failures in the nightly markdown link checker. I've emailed two different wrccdc email addresses to ask if the outage is temporary but neither has responded, so I feel like I should just change to a "live" link for now.
> Change wrccdc link

- ppl/zqd/zqd.ts
- scripts/download-zdeps/index.js
- src/js/electron/brim-boot.test.ts
- src/js/electron/brim-reset-state.test.ts
- src/js/electron/brim-start.test.ts
- src/js/electron/brim.ts
- test/api/helper/test_api.ts
brimdata/zed#2632 removes the `pcap` command and `zqd listen`'s `-suricatarunner`, `-suricataupdater`, and `-zeekrunner` flags.
> prepare for brimdata/zed#2632

- plugins/brimcap/brimcap-cli.ts
> fix quotes for brimcap cli args

- .github/workflows/docs-publish.yml
When setting up the Brimcap wiki in brimdata/brimcap#30, @mattnibs made the helpful suggestion that the Action only be triggered to run when the contents of the `docs/` directory changes. Having made the improvement there, I'm circling back to do the same here.
> Only publish wiki when docs/ directory changes

- docs/Home.md
- docs/Migration-of-Spaces.md
- docs/_Sidebar.md
Part of the plan for #1567 includes an article we can link to from our Space migration UX. While we're hopeful the migration tools should be seamless enough that users shouldn't need to read any supplemental materials to use it, some things I hope to accomplish by having an article:
1.  Educate the curious users on Zed Lakes & Data Pools to provide more detail (and links to even more detail) on why we've switched to this approach, how it benefits them, etc.
2.  We can continue change and/or add to the article if we notice user confusion or bugs as users start to upgrade & migrate
There's a bit of a chicken/egg snag where the article needs to exist before we can link to it from the tools, so here I've started a placeholder article with a stab at some minimal content. As the migration …
> Add initial doc regarding Space migration

- package-lock.json
- package.json
Brimcap now includes the `brimcap migrate` command for turning legacy Spaces into Pools, so let's use it.
> Advance Brimcap dependency to tag v0.0.3

- plugins/brimcap/brimcap-plugin.ts
fixes #1616 
Provides more information to users for two error cases:
**Attempting to launch wireshark on an any `conn` record that has no 5-tuple information**
**Attempting to launch wireshark when no pcaps are found in the search**
> notify on failures

- docs/Troubleshooting.md
The nightly markdown link checker flagged that the link we used for this was unreachable, and the site makes it seem like it may be gone for good. I found another place that has acceptable content that we can link to.
While I was in there I also recognized a second "5-tuple" reference where the link should be added, since these Troubleshooting sections are intended to be read independently from each other.
> Fix link to 5-tuple references

- package-lock.json
- package.json
I'm looking to do some end-to-end testing of Space migration on all the platforms and hence am looking to have Brim pointing at the latest Brimcap before I make some scratch builds.
> Advance Brimcap to 82f0140

- ppl/detail/models/BrimEvent.ts
Closes #1577
The original issue seems to have been solved with the zjson PR. However, I discovered that the detail pane did not render because some code expected a ts field to always be present.
> Don't expect a ts

- src/js/flows/exportResults.test.ts
- src/js/flows/exportResults.ts
Closes #1530 
When exporting results, if the format is csv, we will always add on a ` | fuse` to the end of the their query.
I just tested this with a query that already has `| fuse` at the end and saw no difference. It doesn't matter how many `| fuse`s get added.
> Add fuse if format is CSV

- src/js/electron/main.ts
- src/js/electron/windows-pre-25.ts
closes #1566
Here is the warning on Mac.
To determine if the old brim is on the system, it asks the electron app for the "appData" path, which according to the docs:
```
appData 
Per-user application data directory, which by default points to:
%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application Support on macOS
```
From there, it looks in `\Local\Brim`. This is where I saw brim on my windows 10 VM after installing it fresh from our website at version 0.24.
The next brim release was put at `\Local\Programs\Brim`. 
After the user clicks ok, the new app will immediately quit.
> Show warning when old brim exists on the system

- app/legacy/space-migration/space-migration.tsx
- src/js/lib/System.ts
Fixes #1639 
The electron context menu api failed to open when it got floats in the options instead of ints. The fix is to round the numbers before passing to the showContextMenu() function.
> Fix Notification Context Menu

- src/js/lib/MouseoverWatch.ts
- src/js/state/migrations/202104291255_dropSpaces.test.ts
- src/js/state/migrations/202104291255_dropSpaces.ts
Fixes #1638
The id of the sidebar section changed from "spaces" to "pools". But the persisted data from version 24 still has the id set to "spaces". This caused the sidebar to not render that section in version 25.
I've added to the migration that Matt wrote to include changing the section ids.
I wonder if there is a better way to save layout data like this. Seems odd to write migrations each time something small changes. I don't have an answer yet, but I will be thinking about it.
The screenshot below shows that the pools section is now visible.
I fixed a bug in the RightPaneExpander component that would always display an error in the console. Those who look in the devtools will be familiar with it. It was the result of not clearing a timeout when the component unmounted.
> Pool name bug

- itest/tests/__snapshots__/query.test.ts.snap
- itest/tests/contextMenu.test.ts
- itest/tests/ingest.test.ts
- itest/tests/lake.test.ts
- itest/tests/pcaps.test.ts
- itest/tests/query.test.ts
- package-lock.json
- package.json
- plugins/brimcap/brimcap-plugin.ts
- ppl/detail/flows/fetch.test.ts
- ppl/queries/initial.test.ts
- ppl/queries/initial.ts
- src/js/brim/ast.test.ts
- src/js/brim/program.test.ts
- src/js/brim/syntax.ts
- src/js/flows/submitSearch/__tests__/validate.test.ts
- src/js/searches/programs.test.ts
- src/js/searches/programs.ts
- src/js/state/SearchBar/test.ts
- src/js/state/migrations/202105141312_zedKeywordSearchUpdate.test.ts
- src/js/state/migrations/202105141312_zedKeywordSearchUpdate.ts
- test/api/search_test.ts
- zealot/zealot.ts
Fixes #1644 
Update the app with the new equality, assignment, and matches syntax. Based off the zed branch : 
https://github.com/brimdata/zed/pull/2692
|before | after|
|---| ---|
|`_path=conn` | `_path=="conn"`|
|`query=google*` | `query matches google*`|
|`put sum = a + b` | `put sum := a + b`|
* Updates all app queries
* Updates queries in the itest suite
* Migrates the query library
* Adds parse tests for the default queries in the query library
**Note:** It is likely that user's history entries will contain queries with wrong syntax now. This will be addressed prominently in the release notes, but that's it. No attempt to migrate old history queries will be made. The tooling to do so is not present and not easily built.
> Zed Lang Change

- package-lock.json
- package.json
Looking to make things current so I can do more end-to-end testing with the last wave of Zed language updates now in all systems.
> Advance Brimcap to a1f4486

- app/core/models/histories.test.ts
- app/core/models/histories.ts
Fixes #1648 
The app state may contain history with an empty entries array.
If this happens, the location property will be undefined on the
history object. This will crash the app.
The fix is to never create a history with an empty initial entries.
If there are no entries, pass in undefined.
If you pass initial entries as undefined, the library will push a
"/" entry on the stack. Thus the location property will always be
populated.
For example:
```
> var history = h.createMemoryHistory({initialEntries: []})
> history.location.pathname
Uncaught TypeError: Cannot read property 'pathname' of undefined
```
But this works,
```
> var history = h.createMemoryHistory({initialEntries: undefined})
> history.location.pathname
'/'
```
> Always populate location in tab history

- src/js/api/ui-apis.ts
- src/js/state/Configs/index.ts
- src/js/state/Configs/test.ts
- src/js/state/PluginStorage/index.ts
fixes #1653 
This is an issue we hadn't seen before because until recently we hadn't combined the redux toolkit entity adapters we've begun to use with our existing globally dispatched actions. It has a simple fix though.
Actions may have a `remote` key set if dispatched from another window. In such a case the `adapter.addOne()` and similar CRUD methods will not recognize the passed in action param to be of type `PayloadAction` and will instead interpret the value as an Entity (i.e. a Config type in this case). So instead, we will always pass in the entity/action.payload when using adapters for global reducers.
I also changed the method from `create` to `set` and used upsertOne, since it was already overwriting the existing value (semantically speaking, "set" indicates that overwriting …
> handle adapter bug for global dispatch

- app/legacy/space-migration/space-migration.tsx
- app/legacy/space-migration/space-migrator.ts
- package-lock.json
- package.json
If migrate fails because it was cancelled, the current pool it is
operating on will be deleted. As a result, refresh pools on failure so
things remain up to date.
Also:
- Use tee-1 package to tee migration logs into the brim process stderr.
Better to have some visibility than none.
> space migrate: refresh pool on fail

- test/api/ingest_test.ts
The `npm run test:api` test in the Brim CI recently started failing because the pool size after importing `itest/testdata/custom-sample.ndjson` had increased from 4546 to 4467 as a result of changes in Zed commit `dcce5c22`  (brimdata/zed#2729). At a team discussion today it was agreed that this change is expected, so I've modified the expected value so the CI will start passing again.
> Increase expected pool size due to Zed dcce5c22 change

- plugins/brimcap/brimcap-cli.ts
- plugins/brimcap/brimcap-plugin.ts
- src/js/flows/ingestFiles.ts
fixes #1652 
3 changes here:
* BrimcapCli handles boolean options better. With this, I'm including the `-json` option in load now, though the behavior did not change (stderr returns JSON with or without this option)
* On ingest failure, instead of redirecting users to the "Choose a workspace" page, we just redirect back the workspace they were on when they began ingest
* The main fix relating to the linked ticket: `brimcap` may send ndjson in it's stderr stream. In the error case described in the ticket, the stream was sending a status message AND an error message as json separated by a single new line but the prior parser was only expecting regular json. Now we always parse and process as ndjson.
> Improve brimcap load error handling

- .github/workflows/advance-zed.yml
We recently had an incident where a Zed change effectively broke Brim, but the workflow in `advance-zed.yml` passed ok because it was lacking the `npm run test:api` step that would have caught the failure. That step _is_ in `ci.yml`, so it eventually got caught, but only after Brim had advanced to a state where it was pointing to a Zed version that would fail CI every time.
Here I've copied over some of the steps in `ci.yml` that were previously missing from `advance-zed.yml`. @mattnibs correctly observed that the ideal solution would be to avoid any duplication of steps and instead have the Zed-advancing workflow call into the main CI workflow, similar to how the Brimcap CI is currently set up. However, in the interest of incremental improvement, for the moment I'm extending the …
> Add more test steps to "advance Zed" workflow

- docs/Importing-CSV,-JSON,-Parquet,-and-ZST.md
- docs/Joining-Data.md
As mentioned in brimdata/zed#2744, those changes to the docs  are expected to break some links we've been pointing to from the Brim side. Since the links on the Brim side are all pointing to Zed's "main" branch, it's a little tricky to see in advance what would break. I just did searches for things like "language" (which is in the URL of all the Zed language docs links) and references to "processor" (since I've changed over to saying "operator"), and then I found some spots where we'd briefly been saying "Z" in the brief period after we backed away from "ZQL" but before we started saying "Zed". I intentionally did _not_ go back and scrub every old reference to "ZQL" in the CHANGELOG to say Zed, as I figure we might as well be transparent about the history.
I intend to continue overhauling …
> Fix links and Zed references

- app/legacy/space-migration/space-migration.tsx
- app/legacy/space-migration/space-migrator.ts
- package-lock.json
- package.json
Due to issues with not being able to send a SIGINT signal in windows, if
a migrate is aborted have the brim app delete the current pool.
> legacy space migrate: delete pool

- CONTRIBUTING.md
The nightly markdown link checker informed me of this broken link after the changes in #1687. Based on those PR notes, this looks like the way to fix it.
> Update link for integration test README

- zealot/zealot.ts
On a stats request to an empty pool, the response is 204 No Content.  
Ensure this response is appropriately handled.
Fixes #1697
> zealot: handle empty stats response

- docs/Remote-zed-lake.md
I've been in contact with the wrccdc people during the long time their packet archive has been offline. It's confirmed to be back, hopefully for good, so I'm restoring this link that I'd taken out in #1586.
> Restore wrccdc link

- src/js/components/common/Link.tsx
fixes #1703 
I'm a little surprised typescript didn't help enforce this, but we needed to check if a value was null before attempting to access a property from it inside the `<Link />` component. This also created a more global error if attempting to logout of a non-default workspace. Both cases should be fixed now.
> fix <Link /> typeError

- plugins/brimcap/brimcap-plugin.ts
- src/js/brim/form.ts
- src/js/components/Preferences/Preferences.tsx
- src/js/components/Preferences/usePreferencesForm.ts
- src/js/state/Configs/index.ts
fixes #1704 
Extends the configs api exposed to plugins with ability to add a help link which the app styles to appear right after the label. Brimcap then uses this to add a "docs" link to accompany the yaml configuration's label in the preferences panel.
> brimcap yaml config docs link

- src/js/electron/tron/window.ts
fixes #1707 
I had initially used the `closable: false` option for the "hidden" window as an extra safeguard to prevent users from closing the window (and also as an inferred description that this window should always be open), but it turns out this also prevents us from programmatically closing the window. Given that the window is hidden anyway, I don't think this is actually necessary and am removing.
> fix hidden window close

- src/js/brim/interop.ts
- src/js/flows/ingestFiles.test.ts
- src/js/flows/ingestFiles.ts
- src/js/flows/initPool.ts
- src/js/flows/refreshPoolInfo.ts
- src/js/flows/refreshPoolNames.ts
- src/js/lib/is.ts
- src/js/state/Pools/actions.ts
- src/js/state/Pools/actionsFor.ts
- src/js/state/Pools/reducer.ts
- src/js/state/Pools/test.ts
- zealot/types.ts
- zealot/zed/values/int64.ts
The `span` received from zealot contains `bigint`s. This seems like an appropriate way to type the data and also for Zealot as a generic js client to zed lake serve. However, Brim struggles with this data type since it does not readily de/serialize to JSON which the app requires whenever sending data over ipc. Since our global dispatch is backed by ipc calls, we must always send plain js in our actions, so this PR converts the bigints from the `/stats` call right after receiving the data, instead of right before saving it in redux. I also added some more explicit typing here to help protect the logic and readability.
> Bigint serialize fix

- package-lock.json
- package.json
The ultimate motivation is to get the benefit of the fix in brimdata/brimcap#18.
> Advance Brimcap dependency to tag v0.0.5

- app/search/flows/histogram-search.ts
- src/js/components/charts/MainHistogram/format.ts
- src/js/components/charts/MainHistogram/useMainHistogram.tsx
fixes #1699 
When we issue the histogram search to collect time-grouped counts by path, the first group's timestamp can be rounded down from the included span's start time. When the histogram then renders each group as a bar, it will be skipped because it will fall just outside of the span. This behavior is more obvious in the case when logs are concentrated into two dense groups which are then separated by a relatively large amount of time (in this case the first bar will not be rendered). The fix proposed here is to use the smallest value between the specified span start and the oldest histogram chart timestamp so that the histogram's representation adjusts for the rounding that occurs.
There was also a bug with the way span's were used as you clicked forward and back in the history …
> Histogram span fix

- src/js/components/WorkspaceModals/ViewWorkspaceModal.tsx
While updating Brim docs, I noticed that there was still this "ZQD" reference in the "Get Info" modal for Workspaces. When fixed as it is in this branch, now it looks like:
> Change "ZQD" ref to "Zed"

- docs/Remote-Workspaces-(v0.25.0+).md
This PR is part of the non-code coverage for brimdata/brimcap#113.
This "Remote Workspaces" article was the one place in the Brim wiki docs where `brimcap load` was referenced. Since the "a la carte" combination of `brimcap analyze`, `brimcap index`, and `zapi load` already exist, the updates here can be merged right away to start setting user guidance in advance of the ultimate removal of `brimcap load` as part of the work planned for brimdata/brimcap#113.
I made a couple other small adjustments while I was at it.
> Update Brim docs for phase-out of "brimcap load"

- zealot/zed/types/base-primitive.ts
- zealot/zed/types/type-alias.ts
- zealot/zed/types/type-array.ts
- zealot/zed/types/type-bool.ts
- zealot/zed/types/type-bstring.ts
- zealot/zed/types/type-bytes.ts
- zealot/zed/types/type-duration.ts
- zealot/zed/types/type-error.ts
- zealot/zed/types/type-float64.ts
- zealot/zed/types/type-int16.ts
- zealot/zed/types/type-int32.ts
- zealot/zed/types/type-int64.ts
- zealot/zed/types/type-int8.ts
- zealot/zed/types/type-ip.ts
- zealot/zed/types/type-map.ts
- zealot/zed/types/type-net.ts
- zealot/zed/types/type-null.ts
- zealot/zed/types/type-record.ts
- zealot/zed/types/type-set.ts
- zealot/zed/types/type-string.ts
- zealot/zed/types/type-time.ts
- zealot/zed/types/type-type.ts
- zealot/zed/types/type-typename.ts
- zealot/zed/types/type-uint16.ts
- zealot/zed/types/type-uint32.ts
- zealot/zed/types/type-uint64.ts
- zealot/zed/types/type-uint8.ts
- zealot/zed/types/type-union.ts
- zealot/zed/types/types.ts
- zealot/zed/values/type.ts
This is a case where we are using a "type" as a "value". That means we need to visually represent a "type" in a cell in the viewer. I looked at what zq does for this and tried to copy.
```
{
_path: "ssl",
typeof: ({_path:string,ts:time,uid:bstring,id:{orig_h:ip,orig_p:port=(uint16),resp_h:ip,resp_p:port},version:bstring,cipher:bstring,curve:bstring,server_name:bstring,resumed:bool,last_alert:bstring,next_protocol:bstring,established:bool,cert_chain_fuids:[bstring],client_cert_chain_fuids:[bstring],subject:bstring,issuer:bstring,client_subject:bstring,client_issuer:bstring,validation_status:bstring,ja3:bstring,ja3s:bstring})
}
```
To implement this, I've added a `toString()` method to every zed type. I also created an abstract `BasePrimitive<T>` class to represent the expected interface of …
> Visualize a type value as a string

- src/js/components/CommitNotification.tsx
fixes #1728 
@jameskerr and I discussed this a bit and decided that an even better fix would be to add a new "empty pool" page which would not present any of the toolbar/searchbar/span-picker tools we currently show since those are not of any use on an empty pool anyway, and instead would assist users with how to ingest data into their empty pool. Much like github does for empty repositories.
In the meantime, however, here is a quick fix that simply checks if the last search's span is the empty span default that we set for empty pools (which is the first milisecond of unix time/1970), and if it is then we will use the fresh full span of the now-populated pool instead.   
> Refresh with new span

- package-lock.json
- package.json
The last step before cutting a new Brim beta release.
> Advance Brimcap dependency to tag v0.0.6

- CONTRIBUTING.md
- docs/Code-Base-Walkthrough.md
Fixed some outdated docs, but mostly wanted to create some guiding principles on where code goes in our codebase going forward.
This is the text I've added to the "Codebase Walkthrough" wiki page: 
```
├── app (renderer code)
│   ├── core (generic shared code)
│   ├── features (larger app features)
│   ├── initializers (code run on startup)
│   ├── plugins (plugin code)
│   ├── routes (entry points for each url)
│   ├── state (ui state)
│   ├── window-a.tsx (window entry points)
│   └── window-b.tsx
├── electron (main process code)
└── ppl (licensed code)
```
**Import Rule**: Only import modules from "core", "state", or your own descendants. 
Exceptions:
* Components in "routes" can import modules from "features".
**Bibliography** …
> Docs update & guide to where code lives

- src/js/api/ui-apis.ts
- src/js/components/Preferences/Preferences.tsx
- src/js/state/ConfigPropValues/index.ts
- src/js/state/ConfigPropValues/test.ts
I needed to adjust some of the way we get and set config values to implement #1724 .
1. When "getting" a config value, if the key is not set, return undefined instead of null. We were previously sometimes returning null, and other times undefined.
2. When adding config properties, loop through them at startup and set the value to the defaultValue, if there is no value already present.
> ConfigValueProp defaults

- src/js/electron/ipc/windows/mainHandler.ts
- src/js/search.tsx
It's been annoying to have the state revert back to how it was when brim started every time the page reloads. This PR fixes that. It updates the initial state of the window object in the main process right before the browser window unloads.
This should make development faster. 🎉
> Save window state during a reload

- app/pools/flows/show-pool-context-menu.ts
- plugins/brimcap/brimcap-cli.ts
- plugins/brimcap/brimcap-plugin.ts
- src/js/api/registries.ts
- src/js/flows/deletePool.ts
- src/js/flows/ingestFiles.test.ts
- src/js/flows/ingestFiles.ts
- zealot/api/pools.ts
- zealot/types.ts
- zealot/zealot.ts
fixes #1739 
Uses abort controllers and event emitters to coordinate between the `deletePool` thunk, the `ingestFiles` thunk, and the brimcap loader's `load` method. We send "SIGINT" to spawned processes so that they can gracefully terminate. This can sometimes take a little bit of time (not a lot but enough to make the UI seem like there is a short delay upon deleting a pool), so we also wrap this user action in a toast.promise which gives continuous "deleting..." feedback to the user in those cases.
> Loader abort

- plugins/log-loader/index.ts
fixes #1749 
When this logic got moved into a loader plugin, the error case handling didn't come with it. Putting it back now. When the zed service changes it's error message it should get passed through the app properly now instead of being swallowed.
> default loader: handle error status

- src/js/flows/initPool.ts
- src/js/flows/refreshPoolNames.ts
**What happened?**
Each time the app got an update from the migration process, it would call "refreshSpaceNames". This would ask zqd for all the names of the spaces, then it would request each of their "stats" from the stats endpoint. 
The stats endpoint for the wccdc pool was returning null with 204 No Content (see screenshot) @mattnibs is that a timing race? So when you clicked on it after the migration was complete (it actually didn't matter how quickly you clicked it), you got the default time span (1 second in 1970).
When you click on a pool in the side bar, it "should have" checked that stats are up to date, but it did not.
**The Fix**
Do not request pool stats in "refreshSpaceNames", but do request pool stats in "initPool". 
**History:** The `GET /pool/:id` endpoint used to include …
> Fetch stats when initializing a pool

- app/core/env.ts
- app/release-notes/maybe-show-release-notes.ts
- app/routes/app-wrapper.tsx
- plugins/brimcap/brimcap-cli.ts
- plugins/brimcap/brimcap-plugin.ts
- src/js/components/HTMLContextMenu.tsx
- src/js/electron/autoUpdater.ts
- src/js/electron/extensions.ts
- src/js/electron/main.ts
- src/js/electron/menu/appMenu.test.ts
- src/js/electron/menu/appMenu.ts
- src/js/electron/quitter.ts
- src/js/lib/System.ts
- src/js/lib/open.ts
- src/js/state/SystemTest/index.ts
- test/integration/helpers/env.ts
- test/integration/helpers/newAppInstance.ts
- test/integration/tests/detail-pane.test.ts
- test/unit/setup/after-env/index.ts
I made a module in `app/core/env.ts` that holds all the methods needed for inquiring about the environment.
```js
env.isCI
env.isDevelopment
env.isTest
env.isIntegrationTest
env.isMac
env.isLinux
env.isWindows
```
I also increased the @testing-library timeout setting from 1 second to 5 seconds.
This is to fix some CI flakiness.
> Increase Unit Test Wait Timeout

- search.html
This is causing an error in the console when the standalone react devs tools isn't running.
> Remove leftover react devtools script

- app/viewer/cell.tsx
- src/css/_tooltip.scss
- src/js/components/LogRow.tsx
This seems like an obvious place to highlight the type system. When you hover over a cell, you'll see the name of the cell along with the type.
> Add types to hover

- plugins/log-loader/index.ts
The corresponding Zed API routes are going away, so replace calls
with logs.add()/logs.commit().
> remove logs.post() and logs.postPaths() from Zealot

- app/search/flows/initial-viewer-search.ts
- app/search/utils/search-params.test.ts
- app/search/utils/search-params.ts
- src/js/@types/global.d.ts
- src/js/flows/ingestFiles.ts
- src/js/initializers/initDebugGlobals.ts
- src/js/initializers/initGlobals.ts
- src/js/initializers/initialize.ts
Fixes #1769 
The app won't crash if the user clicks "last 30 minutes". There is more work to be done than just this quick fix. We need to hide the span controls if the backend provides a null span for a pool. We also need to consider bad "from" and "to" values provided by the user. It's not handled very clearly right now.
> Reltime Error Fix

- package-lock.json
- package.json
To take advantage of the fix to brimdata/brimcap#131.
> Advance Brimcap dependency to tag v1.0.1

- src/js/components/LogDetailsWindow/test.tsx
- src/js/electron/brim-start.test.ts
- src/js/electron/brim.ts
- src/js/electron/ipc/globalStore/mainHandler.ts
- src/js/electron/tron/windowManager.test.ts
- src/js/electron/tron/windowManager.ts
fixes #1770 
Part of the activation handler was still conditional to there being zero windows rendered, which should ideally never exist since there should always be at least a hidden window. This adjusts the logic accordingly. I also found a way to render multiple hidden windows using this activation flow, so I've included some protection around that as well.
> activate fix

- app/core/format.test.ts
- app/core/format.ts
Large integers are no longer formatted with exponent notation. Fixes #1783
> Remove Scientific Notation By Default

- app/lakes/import.tsx
- src/css/_notice-banner.scss
- src/js/components/LeftPane/QueriesSection.tsx
- src/js/errors/index.ts
- src/js/errors/types.ts
- src/js/flows/deletePools.ts
- src/js/lib/transaction.ts
- src/js/models/AppError.ts
- src/js/state/Notice/actions.ts
- src/js/style-theme/index.ts
Closes #1775 
Before we switched to the "add/commit" endpoints to ingest data, we would send all the files to the "logs" endpoint. If one of the files was an unknown format, the rest of the files would be ingested fine, and the user would get a warning in the UI saying that some files did not make it. It was all one request and the backend returned "Warning" messages in the response for files that it could not parse.
Now, we loop through the files and call "and" them "commit" for each. If an unknown file is included in the files, the "add" endpoint will return a 500 with the error text seen in the issue. This aborts the whole ingest, the pool gets deleted, and even the good files are not added.
In the short term, I've just formatted this error correctly in the UI as shown below. In the …
> Format Ingest Error

- package-lock.json
- package.json
To take advantage of the fix to #1773.
> Advance Brimcap dependency to tag v1.0.2

- package-lock.json
- package.json
- plugins/brimcap/brimcap-plugin.ts
- plugins/log-loader/index.ts
- scripts/test/search.js
- src/js/flows/createPool.ts
- src/js/flows/ingestFiles.test.ts
- src/js/flows/ingestFiles.ts
- src/js/hidden.tsx
- test/api/tests/ingest.test.ts
- test/api/tests/pools.test.ts
- test/api/tests/search.test.ts
- zealot/api/pools.ts
- zealot/types.ts
- zealot/zealot.ts
brimdata/zed#2976 contains two Zed API changes.
1. For pool creation, the `POST /pool` response now describes both the pool and the default branch (called main).
2. For loading data, `POST /pool/{pool}/{branch}` replaces the combination of `POST /pool/{pool}/add` followed by `POST /pool/{pool}/staging/{commit}`.
> Zed update through brimdata/zed#2976

- package-lock.json
- package.json
To take advantage of recent Brimcap fixes before cutting another beta release.
> Advance Brimcap dependency to tag v1.0.3

- app/legacy/space-migration/space-migration.tsx
- docs/Joining-Data-(v0.25.0+).md
- docs/Migration-of-Spaces-(v0.25.0+).md
- docs/Remote-Workspaces-(v0.25.0+).md
- docs/Troubleshooting-(v0.25.0+).md
brimdata/zed#3034 moved the contents of the former "Zed lake design doc" `design.md` to `README.md`. This PR fixes the links in the app that were pointing to the old location.
> Fix links to Zed lake doc

- docs/Joining-Data-(v0.25.0+).md
- docs/Remote-Workspaces-(v0.25.0+).md
The recent Zed changes to add branching changed some of the `zapi` command lines we show in the Brim wiki articles for working outside the app. Here I've updated them after testing them all as a user and confirming everything works as expected with the new command lines.
> Update wiki articles with branch-related changes

- package-lock.json
- package.json
To take advantage of the fix to brimdata/brimcap#151 in the GA Brim release.
> Advance Brimcap dependency to tag v1.1.0

- app/core/context.tsx
- app/core/models/abortables.test.ts
- app/core/models/abortables.ts
- app/search/flows/histogram-search.test.ts
- app/search/flows/viewer-search.test.ts
- src/js/api/index.ts
- src/js/components/SearchBar/MenuAction.tsx
- src/js/detail.tsx
- src/js/flows/search/handler.ts
- src/js/flows/search/mod.ts
- src/js/initializers/initDetail.ts
- src/js/initializers/initialize.ts
- src/js/search.tsx
- test/unit/helpers/initTestStore.ts
So this was a few bugs...
The bug was that the "Kill Search" button would sometimes not work. This was because the main search function registers a handler for the search with an id. If an id is reused, that means cancel the previous search and run this fresh one. It also was because as soon as a request was aborted, that "handler id" was removed. Also, whenever the search ends (aborted succeeded or failed), the code removes the handler with that id as well. So the bug was in this sequence of events.
1. Click search button
2. Abort handler with id = "Table" (also removes the handler)
3. Search and register handler to id = "Table"
4. Before it completes....
5. Click search button again (before first finishes)
6. Abort handler with id = "Table" (removes the handler)
7. Search and register …
> Kill Search & Aborted Searches

- .github/workflows/linux-release-promotion.yml
- .github/workflows/macos-release-promotion.yml
- .github/workflows/win-release-promotion.yml
I've been doing some release testing in a Brim fork and bumped into some bit rot that needs to be addressed ([link](https://stackoverflow.com/questions/68516559/github-actions-failing)).
> Update reference to Google Cloud Action in release promotion workflow

- package-lock.json
- package.json
To take advantage of the fix to brimdata/brimcap#156 in the GA Brim release.
> Advance Brimcap dependency to tag v1.1.1

- CHANGELOG.md
- package-lock.json
- package.json
Along with the necessary version/dependency advancement, this PR includes the Brim release notes that were already reviewed/approved in a draft PR along. I've also added a tl;dr up top with some summary of the biggest changes and pointers to wiki articles about some "gotchas" of which we'd most like to make users aware.
https://github.com/brimdata/brim/compare/v0.24.0...34deddc
> Update zed to v0.30.0 and prep v0.25.0

- app/search/flows/histogram-search.test.ts
- app/search/flows/viewer-search.test.ts
- ppl/detail/flows/fetch.test.ts
- src/js/flows/search/mod.ts
fixes #1835
The problem with the missing `0`s we see in the indeterminate test is not the backend, it is the `dateToNanoTs` function. It's not entirely a problem so much as an inconsistency: 
The current default behavior is to not include trailing `0`s, which is an acceptable format for the timestamp as the backend parses it. In our tests, we use the date `.toISOString()` method to compare expected values, and that method always includes the full millisecond width, which revealed the formatting difference.
The fix I'm proposing here then is to ensure the decimal width returned by `dateToNanoTs` is at least the full ms, trailing zeros or not, while µs and ns widths may vary by trailing zeros.
Also proposed here is a temporary workaround for the query annotator, as discussed with @nwt: If a …
> query annotation and test fixes

- docs/Troubleshooting-(v0.25.0+).md
As discussed in a [thread on public Slack](https://brimsec.slack.com/archives/C010DR0HHMF/p1631036993069800), a user recently made us aware that our `suricata-update.exe` binary gets flagged as possible malware. Here's my attempt at writing an article to address the topic proactively or via link should it come up again with other users. In addition to pointing our own users at it, I expect I might also be able to reference it from:
1.  The "comments" area of the [Community](https://www.virustotal.com/gui/file/b184511d689d547fa5fd524c7ca120586fcffc60f338f932d41800c63961d723/community) tab for the VirusTotal entry, as was recommended to me by one community user in that Slack thread.
2.  Forms or emails with which we might contact the antivirus providers to make the case that it be …
> Add Troubleshooting section about antivirus false positive

- package-lock.json
- package.json
- src/js/electron/brim.ts
- src/js/electron/initializers/shortcuts.ts
- src/js/electron/main.ts
- src/js/electron/require-all.ts
- test/unit/__mocks__/electron.ts
- test/unit/helpers/setup-brim.ts
It is now possible to zoom the window with `CmdOrCtrl++` or `CmdOrCtrl+Shift++`. The same goes for zoom out. `CmdOrCtrl+-` and `CmdOrCtrl+Shift+-`
This was done by adding out own app wide shortcuts that re-implement the zoom in and out behavior for the currently focused window.
I also added a folder called `electron/initializers`. Any file in it will get required during the "start" phase of the brim app. We can put anything there that only needs to be set up in the main process once.
Fixes #1818
> Relax the shortcuts for Zoom In and Out

- src/js/components/ErrorNotice.test.tsx
- src/js/components/ErrorNotice.tsx
- src/js/components/NoticeBanner.tsx
fixes #1815 
Just adds some type inspection to the error notice renderer. Included a component test which forces the detail string input that caused the original error described in the ticket above for good measure.
> Safer object access in <ErrorNotice />

- plugins/brimcap/brimcap-plugin.ts
fixes #1820 
When we load a pool with the brimcap plugin, we pass each specific load operation the output stream from a forked `brimcap analyze` process. If the analyze process fails the load operation will fail too, but we have not been handling the load and/or analyze errors properly. This PR aims to fix that: now if load fails, we will check for an analyze error and report that if it exists, otherwise we report the load error.
I think this is also a bit cleaner to use a single error flag, `analyzeErr` that is a dedicated error bucket for the analyze operation, as opposed to a general error bucket for the analyze, load, and index operations.
> Improve brimcap analyze error handling

- zealot/zed/context.ts
- zealot/zed/types/type-primitives.ts
- zealot/zed/types/type-type.test.ts
- zealot/zed/types/type-type.ts
- zealot/zed/utils.ts
Fixes #1819
Check if the value of a type is one of the primitive keywords. If so, use the type for that primitive as the value. Here is the repro example now fixed.
> Fix bug with primitive type values

- app/search/flows/__snapshots__/viewer-search.test.ts.snap
- src/js/state/Columns/models/columnSet.ts
In the past we used the name and the type to determine if a column set was unique. Now we just use the the names. So if there is a schema with the same fields as another schema (regardless of order) we will display the data in a table with column headers.
Fixes #1826 
Fixes #1827
And the fix for 1827
> Use Column Names to Determine Unique Columnsets

- src/js/state/Viewer/reducer.ts
- src/js/state/Viewer/types.ts
The `Viewer.endStatus` enum is used to determine if we should fetch the next page of results. It used to default to "Incomplete" which was the signal to fetch the next page. Now it defaults to "INIT" so that we don't fetch the next page unnecessarily.
Fixes #1825
This was the source of the problem. isIncomplete was set to true every time we clear the viewer.
```js
// ResultsTable.tsx
function onLastChunk() {
if (props.isIncomplete && !props.isFetching) {
props.dispatch(nextPageViewerSearch())
}
}
```
> Prevent Next Page Search When Not Needed

- zealot/zed/types/type-array.ts
- zealot/zed/types/type-map.ts
- zealot/zed/values/union.ts
- zealot/zjson.test.ts
fixes #1855 
When encoding a union value back into zjson, we were calling value.toString() instead of value.serialize(). The resulted in the string representation of the value rather than the json value. 
In the original repro, the tags field was a union of "string", "string array", and "null". When we received the data the value was: `["CobaltStrike", "HKKFGL-AS-AP HK Kwaifong Group Limited"]`. When we encoded it back it became `"[CobaltStrike,HKKFGL-AS-AP HK Kwaifong Group Limited]"`. This resulted in bad zjson being saved. When it was read and decoded, it choked on that string value and caused the error.
A test has been added that replicated the error and confirmed that it was fixed.
> Fix Union Encoding

- src/js/electron/brim-start.test.ts
- src/js/electron/tron/window-manager.ts
We have a flaky test, as seen in https://github.com/brimdata/brim/actions/runs/1296027268 
I ran this 100 times in a loop on my machine and could not reproduce the issue, but my hypothesis is that either the lastFocused times are off due to a race condition in electron's window creation such that the search window is created first, OR (and more likely, I think) that when they are created with the same time timestamp then the sort function just preserves the nondeterministic order that `Object.values()` had provided in the `brim.windows.getAll()` method.
To handle this, I'm proposing we set the hidden window's lastFocused to `0` on creation, which should handle both possibilities.
As a side note, I also considered setting the `focusable: false` option to electron's window creator but the …
> Set hidden window lastFocused to 0

- src/js/components/SideBar/Item.tsx
fixes #1907 
Disables `Edit`, `Run Query`, and `Copy Query` if a given item is a group/folder
> Fix qlib folder context menu

- plugins/brimcap/brimcap-plugin.ts
- src/css/_finding-card.scss
- src/css/_saved-pools-list.scss
- src/js/components/SideBar/Item.tsx
* fixes #1925 Does not issue a query if we are multi-selecting.
* fixes #1926 Adds back active and hover states to sidebar items. 
* fixes #1916 Removes label from packet button on detail window.
https://user-images.githubusercontent.com/3460638/139960320-31fc2207-faa7-4873-af2b-33287d1fbf9e.mp4
> Make hover and active states consistent across the sidebar

- package-lock.json
- package.json
- src/js/components/LeftPane/QueriesSection.tsx
Fixes #1927 
There were some bugs around the readonly folders. You couldn't drag anything above or below the folders. 
I also changed the <Tree /> component props from isDraggable to disableDrag and disableDrop, inverting them. The disableDrop prop now only works on directories. If a directory matches the disableDrop function, you will not be able to drop an item in it or any of its children.
Here is a video of this branch. You see you can drag items around the readonly folders, but not on it or in it.
https://user-images.githubusercontent.com/3460638/140252498-701d323f-7f55-4c9f-8ea8-647e69cb11a1.mp4
> Polish Readonly Query Folders Drag & Drop

- src/js/flows/refreshPoolInfo.ts
- src/js/hidden.tsx
- test/integration/helpers/createTestBrim.ts
- test/integration/helpers/newAppInstance.ts
- test/integration/tests/zed-events.test.ts
- zealot/zealot.ts
fixes #1946 
adds integration tests to ensure #1921 is resolved but depends on https://github.com/brimdata/brim/pull/1945
The itest is not related to this specific format change other than how the commit-notification breakage (which it tests) encouraged us to re-examine the requested response format change that is included here. That changes consists of requesting and unpacking zjson into js pool config objects instead of unpacking json.
> Request zjson format from query endpoint 

- app/viewer/value.tsx
The the issue where array values were being placed on top of each other.
Fixes #1950
The images above show that the problem is gone. See the issue for an example of the bug.
> Fix the array overlaps

- src/js/components/WorkspaceModals/EditWorkspaceModal.tsx
- src/js/components/WorkspaceModals/NewWorkspaceModal.tsx
- src/js/components/WorkspacePicker.tsx
- src/js/flows/workspace/buildWorkspace.ts
- src/js/flows/workspace/getAuth0.ts
- src/js/models/Errors.ts
This is an incomplete fix for issue #1922 but we are getting this
small change in now to immediately improve the cloud onboarding
terminology.  This will create some inconsistency in the docs that
refer to Workspace instead of Lake and throughout the code until
issue #1922 is addressed, but that should happen soon.
> change "Add Workspace..." to "Add Lake..."

- test/integration/tests/zed-events.test.ts
Sometimes the update event does not get processed before this test checks for the containing text. The `hasText()` method will retry if it does not find what it's looking for and should fix this issue.
> Fix zed-events test

- src/js/brim/time.ts
The nanosecond calculation in dateToTs() sometimes returns a non-integer
value, leading to a RangeError when time().toBigInt() tries to convert
the value to a BigInt.  Fix by using Math.round() instead of
Number.prototype.toFixed() in the calculation.
Fixes CI failures like https://github.com/brimdata/brim/runs/4216942185?check_suite_focus=true#step:19:27.
> fix non-integer Ts.ns in dateToTs()

- docs/Code-Base-Walkthrough.md
- test/integration/README.md
- zealot/api/query.ts
- zealot/config/query-args.ts
- zealot/fetcher/fetcher.ts
- zealot/types.ts
While verifying the timeout work I added in #1956 I discovered that the query endpoint's streamed response does not get sent back to us as quickly as I'd thought. Below is a breakdown of the request (which you can see for yourself connecting to `Shasta`, the `zng` pool, and then issuing the `Unique Network Connections` query.
Note the 16.46 seconds for TTFB.
The workaround I give here is to just explicitly extend the timeout for all of our query requests until we can figure out a better solution. I've set the query timeout to 5min.
> Query timeout extension

- .github/workflows/advance-zed.yml
- .github/workflows/ci.yml
- .github/workflows/linux-release-candidate.yml
- .github/workflows/macos-release-candidate.yml
- .github/workflows/win-release-candidate.yml
The actions/setup-node@v2 action can save and restore the npm cache and
set up the exact Node version specified in .nvmrc.  Update workflows to
use these features.
> use fancy actions/setup-node@v2 features in CI

- .github/workflows/ci.yml
* Use a single job to eliminate repeated steps and uploading and
downloading Linux packages.
* Stop building the RPM package since it's unused.
* Use a single step for Playwright tests.
* Don't bother with the WORKSPACE environment variable.
This appears to shorten the workflow's running time by four minutes.
> simplify .github/workflows/ci.yml

- plugins/brimcap/brimcap-plugin.ts
- ppl/lake/lake.ts
As a side effect, this moves the Suricata user directory from
$userData/suricata/ to $userData/data/suricata/.
> set BRIM_SURICATA_USER_DIR in the brimcap plugin

- src/js/components/LeftPane/QueriesSection.tsx
- src/js/components/LeftPane/remote-queries.ts
- src/js/components/QueriesModals/EditQueryModal.tsx
- src/js/components/QueriesModals/NewQueryModal.tsx
- src/js/components/QueriesModals/QueryForm.tsx
- src/js/components/SavedPoolsList.tsx
- src/js/components/SideBar/Item.tsx
- src/js/hidden.tsx
- src/js/state/Pools/selectors.ts
- src/js/state/RemoteQueries/index.ts
- src/js/state/getPersistable.ts
- src/js/state/globalReducer.ts
- src/js/state/rootReducer.ts
- src/js/state/types.ts
Here is v0 of the remote-queries feature 🎉 
A remote query is simply a named and described zed value (the same as a query from our local query lib) except that it is persisted in a zed lake instead of on a local file system. This is all facilitated by the app by creating a `_remote-queries` pool, and loading query records in for each create/update/delete operation. We include a timestamp on each query record operation so that we know which record represents the most current state. When a query is deleted, a new query record will include a `tombstone: true` value and will be the most current record. We then filter those deleted records out when retrieving them from the lake.
NOTE: There are several aspects of this feature which we intend to improve but are constrained by the current …
> remote-queries v0

- src/js/components/LeftPane/QueriesSection.tsx
Show the query library even if no pool is selected. If you try to run a query you get a simple error saying no pool is selected. Closes #1954
> Always show queries

- src/js/state/migrations/202202170834_resetInvestigationsAndTabHistories.test.ts
- src/js/state/migrations/202202170834_resetInvestigationsAndTabHistories.ts
fixes #2171 
I found that the global `investigation` and window `tabHistories` state included references to poolIds which will not be the same after the lake migration occurs, so this PR resets them.
> Dont persist investigation or tabHistories state

- app/search/flows/viewer-search.ts
closes #2192 
This is not the most beautiful design, but it gets the job done for this release.
> Catch and display errors from the backend

- .github/workflows/advance-zed.yml
It looks like xvfb maybe updated and now the `yarn build && yarn e2e` doesn't work like it did.
https://github.com/brimdata/brim/runs/5365265103?check_suite_focus=true
> Fix advance zed workflow

- src/js/components/ExportModal.tsx
- src/js/flows/exportResults.ts
Fixes #2252  where an export always fails on a pool with no time span key.
> Don't assume there is a span

- src/app/features/inspector/views/container-view.ts
Add the type name (if there is one) in both expanded and collapsed containers. Shown here is the person type and the data type.
Fixes #2251
> Named Type Fix

- src/app/features/inspector/views/container-view.ts
- src/app/features/inspector/views/create.ts
- Add functions for opening and closing a value
- Handle type alias values
> Inspector fix for type containers

- src/app/query-home/flows/submit-search.ts
- src/js/electron/tron/window-manager.ts
- src/js/flows/openNewSearchWindow.ts
- src/js/initializers/initNewSearchTab.ts
fixes *most of #2242 
Most of the ctx menu items were already fixed with some of the more recent PRs, but the detail ctx menu had to be re-worked to open new draft queries instead of using the legacy search page flow.
*Additionally, there are still three ctx menu items ("Use as 'start' time", "Use as 'end' time", and "View in full context") which remain broken. All three relate to pins and the currently-non-existent span, and both of those topics are themselves being re-worked in separate tickets. Instead of hacking a fix for this now with our current string pins, I'd like to handle these last fixes as a part of how we [re-work the pins structure](https://github.com/brimdata/brim/issues/2217) in queries (which refactors query pins to be stored as typed pin objects) so that the values …
> Query-flow ctx menu fix

- src/js/components/SearchResults/ResultsTable.tsx
It previously looked like that.
fixes #2266
> Fix End of Results Message

- src/js/components/ExportModal.tsx
When this option is selected, you get all the records in a big json array.
fixes #2257
> Add a json export format

- src/app/features/inspector/hooks/scroll-position.ts
- src/app/features/inspector/hooks/scroll.ts
- src/app/features/inspector/inspector.tsx
- src/app/features/inspector/templates/container.tsx
- src/app/features/inspector/templates/space.tsx
- src/app/features/inspector/types.ts
- src/app/query-home/results/main-inspector.tsx
- src/app/query-home/results/results-table/index.tsx
- src/app/query-home/results/results-table/viewer/index.tsx
- src/app/routes/search/main-inspector.tsx
- src/css/settings/_fonts.scss
- src/js/components/SearchResults/ResultsTable.tsx
- src/js/components/Viewer/Viewer.tsx
- src/js/components/hooks/useEventListener.ts
- src/js/state/Inspector/index.ts
- src/js/state/Inspector/reducer.ts
The scroll position is now saved when you switch back and forth between the inspector and the viewer.
https://user-images.githubusercontent.com/3460638/157755960-2cb37e02-1015-4c9e-9240-550cf08885b7.mov
TODO: 
Closes #2218 
Closes #2270
> Save scroll position

- CHANGELOG.md
- docs/Filesystem-Paths.md
- docs/Importing-CSV,-Parquet,-and-ZST.md
- docs/Joining-Data.md
- docs/Microsoft-Windows-beta-limitations.md
- docs/Migration-of-Spaces.md
- docs/Remote-Workspaces.md
- docs/Troubleshooting.md
- src/app/core/links.test.ts
- src/app/core/links.ts
- src/app/lakes/import.tsx
- src/app/legacy/space-migration/space-migration.tsx
- src/js/components/SearchBar/MenuAction.tsx
- src/js/electron/menu/appMenu.ts
fixes #2209 
This also updates some docs paths which had changed. If those paths change again we will continue to need to make those changes explicitly. But now the docs will correspond to the appropriate version of zed.
NOTE: It may be simpler to wait until the zed docs have settled more before merging this. I'll leave the PR up since that may happen very soon and I can tie up the handful of remaining broken links at that time.
> Use tagged zed version in docs urls

- CONTRIBUTING.md
I tried running Brim in the Dev mode for the first time since `yarn` started being used. Based on what I experienced I figured it would make sense to call it out as an explicit dependency.
While I was in there I found a couple other small adjustments in the CONTRIBUTING file to improve clarity/consistency.
> Mention Yarn dependency and fix a couple typos

- .github/workflows/linux-release-candidate.yml
- .github/workflows/linux-release-promotion.yml
- .github/workflows/macos-release-candidate.yml
- .github/workflows/macos-release-promotion.yml
- .github/workflows/win-release-candidate.yml
- .github/workflows/win-release-promotion.yml
setup-gcloud will be updating the branch name from master to main in
a future release. Even though GitHub will establish redirects, this
will break any GitHub Actions workflows that pin to master. This PR
updates your GitHub Actions workflows to pin to v0, which is the
recommended best practice.
> Pin setup-gcloud to v0 instead of master

- src/js/electron/window/SearchWindow.ts
Fixes #2287 
This is likely because of this diff in our dependencies. Although I coundn't find a mention of it in the electron breaking changes page: https://www.electronjs.org/docs/latest/breaking-changes#removed-browserwindowconstructoroptions-inheriting-from-parent-windows
```diff
-    "electron": "^11.5.0",
+    "electron": "^14.2.2",
```
What it looks like now:
Windows:
Mac:
> Only hide menu bar on mac

- src/app/features/inspector/list.styled.tsx
- src/app/features/inspector/views/string-view.ts
Escape new lines in the inspector.
Fixes #2291
> Inspector Strings with New Lines

- package.json
- src/app/release-notes/release-notes.tsx
We've never used images in our release notes until today, so the styles need to be changed a bit. I also removed all margin from all elements, but in this case, we needed to add it back.
> Fix and test release notes style

- CHANGELOG.md
- docs/Filesystem-Paths.md
- docs/Joining-Data.md
- docs/Remote-Lakes.md
- docs/Troubleshooting.md
As pre-sold to @mason-fish and @nwt, this is the first of what I expect to be a few passes through the Brim docs. I'd initially envisioned doing it all in one big PR, but @mason-fish made a good argument to fix the broken links first so the link checker would stop freaking out.
In subsequent PRs, I expect to:
1.  Purge some docs coverage that are specific to older releases, similar in spirit to what @nwt did with #2321.
2.  Correct some of the Zed CLI invocations in the wiki articles to be in sync with newer command syntax.
> Fix broken links in Brim docs

- src/app/features/sidebar/flows/get-query-item-ctx-menu.ts
- src/app/features/sidebar/hooks/index.ts
- src/app/features/sidebar/queries-section/query-item.tsx
fixes #2242 
In addition to fixing the run/copy enabling and execution, this also includes a behavior change: moving forward, when you right click on an item the context menu's actions will refer to just that one item. The delete action (and in the future, any other action which can be applied to multiple items) will act solely on the right clicked item unless that item is "selected" (highlighted in blue) along with at least one other item. In that case, all selected/highlighted items will participate in the operation.
right click on an item that is NOT part of selection
right click on an item that IS part of a multi selection
right click on an item that is the only item selected
renaming, running, copying don't care about selection and just operate on whatever you clicked on
> fix query sidebar context menus

- src/app/core/components/brim-editor.tsx
- src/app/features/sidebar/flows/remote-queries.ts
- src/app/query-home/flows/initial-viewer-search.ts
- src/app/query-home/search-area/from-pin-picker.tsx
- src/app/query-home/utils/brim-query.ts
- src/js/components/ModalBox/useModalController.ts
- src/js/models/TableColumns.ts
- src/js/state/SearchBar/flows.ts
- src/js/state/SearchBar/reducer.ts
I spent some time clicking through the app and fixed a few issues as I encountered them, as well as some known ones:
* the head proc we append to queries had inverted logic from what it should have been
* queries' `isReadOnly` field in a zed lake needed to be quieted when it was missing otherwise we would hit an unmarshalling/`.js()` error.
* opening one query after the other would have strange behaviors where the searchbar would be empty every other tab (and be modified)
* searchbar disabling from query lock was not updating upon change of lock/isReadOnly status
* syntax errors in searchbar will be cleared upon searching once validation passes
* add a null check to `r.try()` (=> `r?.try()`) in `<TableColumn />`. It appears that elements in the records array might not always be Records?
* …
> Various Bug Fixes

- .github/workflows/advance-zed.yml
- .github/workflows/ci.yml
- .github/workflows/linux-release-candidate.yml
- .github/workflows/macos-release-candidate.yml
- .github/workflows/win-release-candidate.yml
This anticipates brimdata/zed#3833, which upgrades Zed to Go 1.18.
> upgrade to Go 1.18 in .github/workflows/

- src/app/query-home/flows/initial-viewer-search.ts
Instead of being a getter, this is actually a function.
> This is a function

- src/js/brim/program.test.ts
- src/js/brim/program.ts
There is a bug where the “pivot to logs” right click option does not create the correct query. The correct query must retain all the filters before the first aggregate clause, then add a new filter based on what the user clicked.
The AST used to have a dedicated section for “filters”. That’s gone now that the language has matured. So, there is not a reliable way to know when the filters start and stop.
Yesterday, I started to go down rabbit hole of building the AST manager that we’ve always dreamed of. Here is my draft PR that get’s started on that effort.  However, to build this correctly would take weeks and then more weeks to iron out all the bugs. Then we would need to maintain it in lock step with any language changes. There are some open questions on that draft PR that welcome …
> Fix pivot to logs

- .github/workflows/markdown-link-check-config.json
- docs/Supported-Platforms.md
See brimdata/zed#3871 for background.
In addition to putting back a link I'd removed in a docs review, I figure having the workaround in place could be helpful for future generations since someone who innocently adds a link to docs.github.com might otherwise be left scratching their head.
> Work around docs.github.com link checker problem

- .github/workflows/advance-zed.yml
The commit log is very noisy because of the level of detail in these
commits messages.
> simplify commit message in .github/workflows/advance-zed.yml

- .github/workflows/advance-zed.yml
The Slack notifications from .github/workflows/notify-main-failure.yaml
provide sufficient notification of failures, and the PRs aren't
particularaly useful outside of that.
> remove PR creation step in .github/workflows/advance-zed.yml

- src/app/viewer/value.tsx
- src/js/components/LogRow.tsx
While the new inspector handles large container types with ease, the old, busted table does not. This is a quick fix so that the app doesn't crash on large arrays and sets. I expect to re-write the table view to incorporate much of the code from the inspector view, so I don't want to spend to much time propping up the old code.
> Handle Big Arrays

- .github/workflows/ci.yml
- .yarn/plugins/@yarnpkg/plugin-github.cjs
- .yarnrc.yml
Both Brimcap and Zed must be built in a cloned Git repository to ensure
that "brimcap -version", "zed -version", and "zq -version" produce
meaningful output, but Yarn's @yarnpkg/plugin-github plugin fetches
tarballs for GitHub repositories instead of cloning them.  Add a dummy
plugin so Yarn will clone repositories instead.
Closes #2311.
> fix zdeps -version output with dummy @yarnpkg/plugin-github

- src/js/brim/program.test.ts
- src/js/brim/program.ts
This fixes the problem Steve encountered today with pivot to logs.
The problem was the "*" in the filter. There was a regex that looks for a star that clears the filter. But it should only look for a "lone" star, not a star that's within other stuff.
> Fix pivot to logs when it has a star

- package.json
- yarn.lock
This Brimcap release uses Zed at c68a120d0c9d696cdd55241fe4569f3fa112f866,
aka v1.1.0.
> upgrade Brimcap to v1.2.0

- src/app/ipc/first-run.ts
- src/app/ipc/meta.ts
- src/app/release-notes/maybe-show-release-notes.ts
If this is the first time ever opening the app, do not display the release notes. Otherwise, only show the release notes if it is the first time using this version.
I create a file called first-run after launching. If that file exists, it's not the first run ever.
First launch after nuking the "run" directory
Launching again after changing the version in package.json to v0.30.2.
> Skip Release Notes on First Launch

- src/app/query-home/results/results-error.tsx
- src/app/query-home/results/results.styled.tsx
- src/app/query-home/search-area/Input.tsx
- src/js/state/Editor/reducer.ts
- src/js/state/Editor/selectors.ts
- src/js/state/getPersistable.ts
fixes #2382 
stores the height of the editor in tab state under the existing `editor` slice.
there is currently a bug where we are not properly persisting tabs which needs to be fixed before we can see the app remember that height.
> Resize editor

- src/js/components/ModalDialog/ModalDialog.tsx
- src/js/state/Results/flows.ts
- src/js/state/Results/reducer.ts
fixes #2389 
when users issue a query while there is already one in progress, we abort the first request which returns an abortion "error". We then create our own error object out of that error and set it in redux for the viewer component to use. When the second request finishes, we set the data but we don't clear the error.
Unrelated, but I also saw that our modals needed a higher z-index because of the horizontal drag anchor for resizing the editor.
Each of the 4 line changes here fixes the above 4 issues. Now we clear any results error on success, we do not treat aborted requests as errors, when we do set an error we use the error message instead of the whole object, and when we show the lake info/export-results/etc. modal with a query page open then the editor's drag anchor will …
> fix viewer error

- src/app/core/utils/zed-type-class-name.ts
- src/app/features/inspector/list.styled.tsx
- src/app/features/inspector/templates/closing.ts
- src/app/features/inspector/templates/field.tsx
- src/app/features/inspector/templates/item.tsx
- src/app/features/inspector/templates/key.tsx
- src/app/features/inspector/templates/opening.ts
- src/app/features/inspector/types.ts
- src/app/features/inspector/views/array-view.ts
- src/app/features/inspector/views/container-view.ts
- src/app/features/inspector/views/error-view.ts
- src/app/features/inspector/views/map-view.ts
- src/app/features/inspector/views/record-view.ts
- src/app/features/inspector/views/set-view.ts
- src/app/features/inspector/views/type-record-view.ts
- src/app/features/inspector/views/view.ts
- src/css/shared/_type-colors.scss
A single value can be rendered in 4 ways depending on it's level of nesting and what is expanded.
1. Render Expanded
2. Render Collapsed
3. Render Peek
4. Render Single
Here are what screenshots of each of those look like:
**Expanded**
An expanded container shows all of its items on separate lines.
**Collapsed**
A collapsed container renders all of its items on a single line.
**Peek**
A "peek" render means the container shows the first two items, then an ellipsis with the tail count.
**Single**
A "single" render means we just show the container's syntax and the count of its items.
When any of these levels render their children, the children will be rendered and the next level down. Expanded shows children in collapsed mode, collapsed mode shows children in "peek" mode, and "peek" mode …
> Inspector Performance

- src/app/features/inspector/list.styled.tsx
- src/app/features/inspector/templates/container.tsx
- src/app/features/inspector/types.ts
- src/app/features/inspector/views/container-view.ts
- src/app/features/inspector/views/view.ts
- src/app/query-home/index.tsx
- src/app/query-home/results/main-inspector.tsx
- src/js/state/Inspector/index.ts
- src/js/state/Inspector/reducer.ts
The inspector was slow when a nested container value had a large number of children. For example, a record with an array field that had 10,000 items.
When the record was expanded, it would display the whole array on one line. All 10,000 items. Now this is limited to 15.
Now when you click that array to expand it, it was creating rows for all 10,000 items. This was also slow. Now it only will show the first 100 items, with a button to load the next 100.
To do this, we keep track of the "page" that the user has loaded in the inspector state. We store it in a map with the value index path as the key, and the page number as the value. Each time the button is clicked, the page number gets incremented and the next page is rendered.
This applies to all container values.
Here it is with a record …
> Inspector Limits

- docs/Supported-Platforms.md
- docs/Troubleshooting.md
The markdown link checker had failures last night because these wiki articles were pointing at the old release YAML workflows that no longer exist. Here I point a the newer YAML.
> Fix broken links in wiki

- src/js/flows/exportResults.ts
- src/js/state/Results/selectors.ts
We were generating the wrong query when exporting data. It was based on the old, pool-centric design. This PR updates it to use Results.getQuery. That returns the exact query that was used to generate the results in the table/inspector.
The annotateQuery function needs to be removed now. It is adding a time filter for a ts field to everything. That what caused this bug. The time filter removed all the results from the original query.
Fixes #2426
Note: The "Related Alerts" and "Related Conns" queries also need this treatment. They are currently broken. I did not include fixes in this PR since fixing the export is higher priority.
> Use Results.getQuery when exporting

- .github/workflows/build.yml
- .github/workflows/release.yml
I recently noticed that the platforms specified in the new build/release workflows were pointing at the `*-latest` GitHub Actions runners. However, the prior workflows that built release candidates pointed to specific versions `macos-10.15`, `ubuntu-18.04`, and `windows-2019`, and the CI workflow (which also builds the app) still pins to these versions as well.
We discussed this at team sync and there was disagreement about whether to keep pinning to specific versions or just always be testing on "latest" of all platforms. The former doesn't _necessarily_ guarantee forward compatibility with everything newer, and has the drawback of requiring manual intervention when GitHub drops support for older platforms in their Actions runners. The latter has the drawback that what's pointed to as …
> Pin platform versions in build/release workflows

- src/js/electron/window/SearchWindow.ts
We must be doing something that is taking longer than a second to clean up that the large JSON value is revealing.
> Increase timeout when closing

- docs/Remote-Lakes.md
This wrccdc link has been breaking in our automated link checker for a couple days. I happen to have a contact for someone that looks after the wrccdc site who said it was due to come back online shortly, but today they updated me to say it won't happen until early August. Therefore I'm just removing the link. In fact, since the URL for the pcap also appears in the `wget` command line in the fixed text right below here in the article, I don't even think it'll be necessary to put the hyperlink back when they're online again. 😛
> Remove link to offline wrccdc site

- src/js/electron/tron/window-manager.ts
I'm still thinking of how best to test, but the fix at least was simple:
Since we now await the `window.load()` on start, each window will be created and initialize itself before that load() resolves, and we proceed to assign the window to the manager's windows state.
The problem with this is that the window's initialization process depends on the window manager already knowing about the window so that it can send it it's initial state (which we load from persisted storage). So by storing the window in the manager first and _then_ awaiting the load, the initialization is properly synchronized and can succeed.
> Fix tab state persistence

- package.json
- packages/zealot/src/client/client.ts
- yarn.lock
This updates Zealot for brimdata/zed#4001 by adding the ctrl URL query
parameter to POST /query requests.
Closes #2444.
> upgrade Zed to 834a63338e3864510538f542c21000c0033b838c

- src/js/state/getPersistable.ts
The app was taking a long time to quit and to reload pages when the oliver.zng file was loaded. Some perf measurements revealed we were deep cloning the entire state when we did not need to.
> Fix Long Refresh

- src/app/features/sidebar/common.tsx
- src/app/features/sidebar/item.tsx
- src/js/components/DragAnchor.tsx
Fixes: #2457
Now there will be no flashing horizontal scrollbar, and no double vertical scroll bar as you resize or scale.
I made the choice for the sidebar not to be horizontally scrollable. That was a design choice that follows the pattern of other apps with sidebars. For example, here's a screenshot from slack with a long channel name. It also doesn't scroll horizontally.
I also tweeked the size of the drag anchors for the panes. And gave the section contents a min-width of 0 so that they will shrink as the window gets smaller.
I'd upload a video but I don't have good internet.
> Fix Double Scroll Bar

- src/js/state/get-persistable.test.ts
- src/js/state/getPersistable.ts
- src/test/shared/__mocks__/goober.ts
Fixes #2462 
Immer makes all these objects immutable. So we need to create shallow copies of anything we want to mutate. I was able to reproduce this bug by adding a auth0 lake to zui, then quitting the app.
I also was able to reproduce it in a unit test, which I've included in this PR.
Aside: I had to mock goober which is unfortunately a dependency of react-hot-toast, which we require for the api, which we require in unit tests. I wanted to run this test without the dom, but goober needs the dom. I mocked goober to not need the dom. Now the tests can run in the node env instead of the js-dom env. They run faster in node.
> Fix Persist Bug

- src/app/features/inspector/templates/container.tsx
- src/app/features/inspector/views/container-view.ts
Fixes #2464
If you hold down alt (or option on mac) then click on the expand/collapse button, it will expand or collapse that value and all its children.
I chose alt because that is what Google Chrome devtools chose when expanding/collapsing all nodes in the html inspector. https://umaar.com/dev-tips/181-expand-nodes/
> Alt-key will toggle recursively

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- docs/Supported-Platforms.md
As noted in #2463, GitHub is deprecating the `macos-10.15` platform in their hosted Actions Runners. @mason-fish recently made some Zui test binaries that were build with `macos-11` (artifacts are [here](https://github.com/brimdata/brim/actions/runs/2827034553), made from [this branch](https://github.com/brimdata/brim/compare/build/test-zui)), so this gave me an opportunity to smoke test on an older macOS release to check if they still run ok and, if not, update our support statement. Rather than run through the exhaustive set of tests described in #1263, I opted to just test on Mojave 10.14 since that was the oldest release Brim worked on the last time I went through this exercise, and assume if that's ok then newer releases would still be ok too. Thankfully the app still installed and …
> Use macos-11 runners and update Suported Platforms article

- src/app/core/pools/pool.test.ts
- src/app/core/pools/pool.ts
- src/app/features/sidebar/index.tsx
- src/app/pools/home.tsx
- src/app/query-home/results/index.tsx
- src/app/routes/app-wrapper/main-area.tsx
- src/js/components/AppErrorBoundary.tsx
fixes #2490 
Be able to render a pool with a null keys value:
I also added an error boundary that clears itself if it's parent re-renders. It now looks like this:
https://user-images.githubusercontent.com/3460638/184963748-1d6f7f6d-e9c8-4fc1-acec-bf5e96b88a6a.mp4
> Fix Null Pool Key

- packages/e2e-tests/tests/export.spec.ts
fixed #2432 
I was flirting with the idea of switching our export flow to use an html file input so that we can use the same pattern for testing save dialogs as we do for the ingest flow (where Playwright has visibility and control of the "filechooser" event), but I ended up finding a very simple way to mock it within playwright instead. It's worth taking note of this particular pattern because it can be used for other electron features that aren't supported by playwright yet:
```js
app.brim.evaluate(async ({dialog}, filePath) => {
dialog.showSaveDialog = () =>
Promise.resolve({canceled: false, filePath})
}, file)
```
The tests go through all 4 currently supported export formats and verifies success by checking that the size of the output file is correct, which seemed good enough for me.
> Export e2e test

- package.json
- yarn.lock
This Brimcap includes a new Suricata artifact that fixes https://github.com/brimdata/brimcap/issues/259, so I figure we might as well start using it. I'll plan to make a numbered Brimcap release and start pointing to that before we release Zui v1.0.0.
> Upgrade Brimcap to 2907d70

- packages/e2e-tests/tests/export.spec.ts
- src/js/components/ExportModal.tsx
I followed the Export fix & test PRs closely enough that I could see that adding this ZSON export feature might not be too hard. Indeed, it took just a few lines of code to make it work and add a test that passes.
https://user-images.githubusercontent.com/5934157/187553865-21ad0a17-1575-438e-8475-cdb3e7857d7c.mp4
```
$ yarn e2e
Running 14 tests using 1 worker
✓  export.spec.ts:36:5 › Export tests › Exporting in zng format succeeds (1s)
✓  …rt.spec.ts:36:5 › Export tests › Exporting in zson format succeeds (901ms)
✓  …rt.spec.ts:36:5 › Export tests › Exporting in json format succeeds (899ms)
...
```
Closes #1486
> Add ZSON export option

- src/app/query-home/results/index.tsx
This must have happened in a merge conflict.
Fixes #2492
> Overflow hidden on the results

- src/js/brim/program.ts
- src/js/flows/exportResults.ts
As shown in the attached video, we can avoid the `error(missing)` values if we use `quiet()` to wrap the field references in our `cut()` of columns.
https://user-images.githubusercontent.com/5934157/188040989-5436099e-edd3-47d7-bd33-3bbc6f89f5be.mp4
As for the code change, I couldn't find other things currently using the existing `cut`, so it may have been fair game to just do the `quiet()` wrapping in there. However, in the event something else wants to invoke Zed `cut()` one day and isn't expecting the errors to be silenced, I made a new function and called that instead. I also thought about putting an optional boolean `quiet` on the existing function, but that didn't play right with the fact that there's already a "rest parameter" `...fields`. So, bottom line, no offense taken if you …
> Use quiet() around cut() when exporting columns

- src/js/components/BrimToaster.tsx
- src/js/components/ExportModal.tsx
- src/test/system/index.ts
Fixes #2497
I tested this by exporting 3.4 gigs of ndjson. The export took over a minute, did not disappear, and then displayed the "export complete" 
message.
> Increase toast loading duration to biggest number

- src/js/state/Results/paginate.test.ts
- src/js/state/Results/paginate.ts
Fixes #2452 
Comments at the end of lines don't break queries anymore. Thanks for the rec @nwt
> Comments at the end of lines will work now

- search.html
I admittedly found this fix via grep-n-hack, but I made some test artifacts and it did make the symptom go away on macOS, Linux, and Windows, so it hits the spot for my immediate needs.
FWIW I did find some other lingering "Brim" references still out there, but I didn't fiddle with any of them because I wasn't sure if there could be undesirable side effects. Happy to bring them into the PR if they're deemed safe/desirable changes.
https://github.com/brimdata/brim/blob/8ac2379dd254ec6dcd265c2c770ebbca07e2aeb5/src/app/router/routes.ts#L12
https://github.com/brimdata/brim/blob/8ac2379dd254ec6dcd265c2c770ebbca07e2aeb5/src/js/brim/brimTab.ts#L26
https://github.com/brimdata/brim/blob/8ac2379dd254ec6dcd265c2c770ebbca07e2aeb5/src/js/electron/windows/search/app-menu.ts#L75
Fixes #2523
> Brim->Zui in window title

- package.json
- packages/e2e-tests/helpers/test-app.ts
- src/app/query-home/title-bar/query-actions.tsx
- yarn.lock
The button to run queries was moved in the changes in #2530 which meant the end-to-end tests could no longer locate it to click it. Since the advance of the Zed pointer requires a successful run of the e2e tests, we've been stalled on that for a few days. The fix here just gives the button a label that the e2e test can successfully find. Here's the proof of it succeeding locally:
```
$ yarn e2e
Running 16 tests using 1 worker
✓  …ort.spec.ts:36:5 › Export tests › Exporting in zng format succeeds (684ms)
✓  …rt.spec.ts:36:5 › Export tests › Exporting in zson format succeeds (875ms)
✓  …rt.spec.ts:36:5 › Export tests › Exporting in json format succeeds (883ms)
✓  ….spec.ts:36:5 › Export tests › Exporting in ndjson format succeeds (866ms)
✓  …ort.spec.ts:36:5 › Export tests › Exporting in …
```
> Locate moved Run button in e2e test

- src/js/components/LakeModals/ViewLakeModal.tsx
In my fix I mimicked this pattern:
https://github.com/brimdata/brim/blob/e17764cf31b094d2acbf4270780500ebf95a6724/src/js/components/LakeModals/LakeForm.tsx#L198
Fixes #2543
> Construct lake URL without trailing colon if port is empty

- .github/workflows/build.yml
- electron-builder-insiders.json
- electron-builder.json
It looks like windows pays attention to the appId property in the electron builder config. It was set to "com.electron.brim" for Brim v30, Zui v1, and Zui-Insiders. This looks like the reason they were overwriting the folders.
Each one now has a unique app id.
It'd be good to check the auto-update behavior again before releasing Zui Stable. I expect it would be fine, but who knows.
Actually, since I've changed the appId for zui-insiders as well,  we can see what happens when zui-insiders updates after this merges. If that works fine, then Zui will work fine as well. 
fixes #2459
> Unique App Ids for Zui

- src/app/core/links.ts
- src/js/electron/autoUpdater.ts
Fixes #2550
To test I first created a "regular" Zui build based on this branch and installed it on Linux (artifacts [here](https://github.com/brimdata/brim/actions/runs/3155040567)). Since the `version` in `package.json` is still set to `0.30.0`, we see the pop-up that redirects to the Download page on brimdata.io when clicked, just as before.
https://user-images.githubusercontent.com/5934157/193157427-1a7ce53b-f36f-4f87-8b53-2b878cd2cdfa.mp4
Then I created a Zui Insiders dev build with a locked in version string that's older than the latest one available in GitHub (artifacts [here](https://github.com/brimdata/zui-insiders/actions/runs/3155037662)). Now when we click the link in the pop up, it goes to the GitHub Releases page where the user should see the latest available version. …
> Alternate download URL for Zui Insiders

- packages/zealot/src/client/client.ts
Zealot's Client.load method sends a "Content-Type: application/json" request header even though we want the Zed lake service to perform format auto-detection for these requests.  Sending that header isn't a problem right now because the load endpoint ignores the Content-Type header and always does auto-detection, but brimdata/zed#4160 will change the load endpoint to respect that header and do auto-detection only if it's absent or empty.  In preparation for that, change Client.load to omit the Content-Type header so the service will continue to do auto-detection.
> zealot: don't include Content-Type header in load request

- src/js/electron/autoUpdater.ts
While writing the Release Note for the fix to #2459, I noticed something annoying with the GitHub Releases page that just started happening when we crossed over into the 100th Zui Insiders release: If you go to https://github.com/brimdata/zui-insiders/releases, the top entry shown appears to be based on an alphanumeric sort, whereas I was expecting a sort perhaps by creation date. Thankfully, the "find a release" tool still works there if someone knows the number of a newer release they were expecting to see, and the hyperlink behind **Releases > Latest** on https://github.com/brimdata/zui-insiders still goes to the most recent release. But the change I put up in #2566 to send Linux users to https://github.com/brimdata/zui-insiders/releases is no longer as helpful.
Thankfully, a URL …
> For Zui Insiders update notice on Linux, point to /releases/latest

- .github/workflows/advance-zed.yml
- .github/workflows/markdown-link-check.yml
It was recently [announced](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) that the `set-output` syntax is being deprecated in Actions. I tested out the replacement syntax in a personal repo to get a feel for it and it works as described, so here's changes to our own Workflows to adopt the new approach.
> Use replacement for deprecated set-output

- .github/workflows/advance-zed.yml
- .github/workflows/ci.yml
- .github/workflows/docs-publish.yml
- .github/workflows/markdown-link-check.yml
v2 is deprecated because it uses Node.js 12, which is no longer supported.
(inspired by https://github.com/brimdata/zed/pull/4185)
> Upgrade to actions/checkout@v3 in CI

- src/app/menus/new-pin-menu.ts
- src/app/query-home/search-area/pins/generic-pin/form.tsx
In a sync meeting some feedback was given that the terms "Generic Pin" and "Value" were maybe a bit too... generic. Here's a take at some of the alternatives we discussed to try on for size.
Closes #2532
> Improve on the term "Generic Pin"

- electron-builder-insiders.json
See https://github.com/brimdata/brim/issues/2459#issuecomment-1287473622 for the full details on this small change.
The tl;dr is that this setting of a unique `appId` for Zui Insiders is expected to resolve #2459 by allowing Zui Insiders and Brim/Zui to now be simultaneously installed on Windows. A smooth transition will require some care/steps on the part of Zui Insiders on Windows and macOS. Therefore, this PR will only be merged after communicating in advance to the existing Zui Insiders user base on Slack.
Below is a draft of the communications I'd plan to send on Slack before the change. Once this change is merged and a Zui Insiders release with the new `appId` is created, I'll put the same text as its Release Note on GitHub. Please comment in this issue with any questions or …
> Set unique appId for Zui Insiders & draft Release Note

- .github/actions/setup-zui/action.yml
- .github/workflows/advance-zed.yml
A recent Actions run produced the following warnings during a step that relied on `actions/setup-node@v2`:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
I can see that https://github.com/actions/setup-node/pull/587 appears to fix this, so if we move to `@v3` these should go away.
> Start using actions/setup-node@v3 due to deprecation warnings

- src/js/brim/ingest/detectFileTypes.test.ts
While working on #2596 I noticed that `sample.zng` wasn't actually being used by any of our current tests. However, I've used that specific file in bug repros all the time and link to it often from issues, so I didn't want to propose removing it.
At the same time I found this "detect file types" test where I could put it to work. 😉  I threw in ZSON as well for good measure.
> Add ZNG and ZSON to file detection test

- .eslintrc.yml
- packages/e2e-tests/helpers/test-app.ts
I was trying my hand at creating an e2e test by going off some existing tests and I was getting unexpected results. It turns out the example I was following may have had problems, as I found that if I replaced the `Import Complete.` in this diff with garbage text, the test still passed without complaint. I looked for other examples and found that changing to `expect(...).toBeVisible()` did what I think was intended, as now it chokes on garbage text but runs successfully when it sees the `Load Successful` pop-up. However, one snag remained in that the linter complained `error:  Expect must be inside of a test block`. I figured out how to adjust the linter rules to allow this, but if there's a better way to go about this, I'm all ears.
> Watch for "Load Successful" pop-up after pool creation

- packages/e2e-tests/helpers/test-app.ts
- packages/e2e-tests/tests/pool-loads.spec.ts
As observed in a failed test run at https://github.com/brimdata/brim/actions/runs/3586451129, the e2e test that was recently enhanced in #2600 could fail because the loads in quick succession may leave multiple "Load Successful" pop-ups on the screen at once. The failure looked like:
```
$ yarn e2e pool-loads
Running 4 tests using 1 worker
✓  1 pool-loads.spec.ts:17:3 › Pool Loads › load data into a pool (1s)
✓  2 …-loads.spec.ts:25:3 › Pool Loads › load more data into the pool (732ms)
✘  3 …s.spec.ts:38:3 › Pool Loads › create with bad data deletes pool (178ms)
✓  4 …ts:46:3 › Pool Loads › load data into pool does not delete pool (420ms)
1) pool-loads.spec.ts:38:3 › Pool Loads › create with bad data deletes pool ======================
locator.waitFor: Error: strict mode violation: …
```
> Check pool load results and wait for pop-ups to clear

- packages/e2e-tests/tests/export.spec.ts
- packages/zealot/src/client/types.ts
- packages/zealot/src/client/utils.ts
- src/js/components/ExportModal.tsx
Since https://github.com/brimdata/zed/pull/4246 enabled Zeek as an exportable format over the API, I've added it to the set of permitted export formats in the app.
Since ZJSON was already working in the API and #2601 has it lined up to be an explicit import format, I added that here as an export format as well for consistency.
I updated some of the locators in the e2e test to the improved syntax @jameskerr showed me, which was in one case necessary to make the updated tests pass. I'll point it out in a PR comment.
> Add Zeek and ZJSON as export formats

- package.json
- src/js/detail.tsx
- src/js/electron/appPathSetup.ts
- src/js/electron/brim.ts
- src/js/electron/extensions.ts
- src/js/electron/operations.ts
- src/js/electron/ops/open-about-window-op.ts
- src/js/electron/ops/open-detail-window-op.ts
- src/js/electron/ops/open-search-window-op.ts
- src/js/electron/ops/run-command-op.ts
- src/js/electron/ops/show-preferences-op.ts
- src/js/electron/ops/show-release-notes-op.ts
- src/js/electron/ops/window-initialized-op.ts
- src/js/electron/run-main/run-initializers.ts
- src/js/electron/run-main/run-main.ts
- src/js/electron/run-main/run-op-listeners.ts
- src/js/electron/session.ts
- src/js/electron/windows/about-window.ts
- src/js/electron/windows/create.ts
- src/js/electron/windows/window-manager.ts
- src/js/electron/windows/zui-window.ts
- src/js/initializers/initDetail.ts
- src/js/initializers/initIpcListeners.ts
- src/js/initializers/initialize.ts
- src/util/timed-promise.ts
- yarn.lock
The bug:
When creating a new window, the app took these steps:
1. Load the window
2. Setup a "closed" listener to delete the reference to the window
If you closed the window quickly before it finished loading, the first step would throw an error. The second step would never happen. This lead to us keep around a reference to a destroyed window. 
Any other places in the code that tried to access anything on that window would get the "Object is Destroyed" message.
The fix is to do this:
1. Setup the "closed" listener
2. Load the window
Now, no matter what, when the window is closed, we will remove the reference to it. Just like the electron docs instruct: https://www.electronjs.org/docs/latest/api/browser-window#event-closed
If the load fails, it will throw an error. I've gone to all the …
> Fix Those Buggy Windows

- packages/zealot/package.json
- packages/zealot/src/client/client.ts
- packages/zealot/src/client/types.ts
- src/js/flows/exportResults.ts
- yarn.lock
When exporting data, we don't get control messages. This means it could be a long time before the first byte is sent back. By default we have a 60 second timeout. A user recently hit this limit and could not export their data. This PR makes the timeout Infinity for exports.
> Extend timeout on exports

- CONTRIBUTING.md
- package.json
Community issue #2569 led me to revisit our user-facing docs for creating release artifacts. I thought they might be in some ways confusing or incomplete when viewed by an outsider. Specifically, the `yarn release` that was referenced previously was wired up to run on MacOS, which may have suited our internal needs but might confuse a user such as the one in #2569 running on a non-Mac OS. Since Electron Builder defaults to building for the detected OS, I've changed it over to that.
We also only had code signing details for MacOS (and the ones we had needed a little adjustment), so I've included the ones for Windows as well.
I fixed a couple typos, fixed some links, and improved some other wording while I was in there.
I'll add PR comments to further point out a couple specific changes.
> Improvements to CONTRIBUTING doc

- packages/zealot/src/lake/lake.ts
- src/app/features/sidebar/queries-section/query-item.tsx
1. Hide the zed process with windowsHide: true
2. Show the context menu by stoping propagation. There were two context menus that were both trying to show themselves. The one on top now wins and doesn't send the event it's ancestor.
Fixes #2617 
Fixes #2615
> Windows Hide Exe and Show Context Menu

- CHANGELOG.md
- docs/Home.md
- docs/Importing-Parquet-and-VNG.md
- docs/_Sidebar.md
- src/app/core/links.ts
https://github.com/brimdata/zed/pull/4256 handled the bulk of the format rename, so now we need to hit other repos. Right now a changed doc link causes a CI failure here in the app, so that's addressed here.
> Rename ZST to VNG

- package.json
- packages/e2e-tests/tests/export.spec.ts
- yarn.lock
The change to packages/e2e-tests/tests/export.spec.ts reflects a change in the size of ZNG output due to the LZ4 package change in brimdata/zed#4197.
> upgrade Zed to 1442bf8189f064e9bfea67e4adf71bc9a22651a8

- packages/e2e-tests/tests/export.spec.ts
- src/components/data-format-select.tsx
- src/js/components/ExportModal.tsx
As I've been working a lot lately with adding/testing formats for load & export, I've noticed how the Zed docs have been pretty tidy in how formats are typically referenced in alphabetical order and presented with capital letters where appropriate. The one exception is the CLI tooling where they're specified in lowercase, but that seems to be par for the course when it comes to CLI tools. Therefore I'm proposing we go the ordered/caps route in the app so it's consistent with what users see in the docs.
> Tidy the format selections for load and export

- packages/e2e-tests/README.md
https://github.com/brimdata/brim/actions/runs/3719174194/jobs/6307862383 was a recent failed link check run related to a URL pointing to Playwright docs about "Selectors". A little digging found this was an intentional change as described at https://github.com/microsoft/playwright/issues/18992 and https://github.com/microsoft/playwright/pull/19244 so here I've swapped over to the new link destination.
> Fix broken "Selectors" link

- packages/e2e-tests/tests/export.spec.ts
- packages/zealot/src/client/types.ts
- packages/zealot/src/client/utils.ts
- src/components/data-format-select.tsx
- src/js/components/ExportModal.tsx
- src/js/flows/exportResults.ts
https://github.com/brimdata/zed/pull/4252 added support for loading/querying in Arrow IPC Stream in Zed, so here we add support for it in the app as well.
> Add load/export support for Arrow IPC Stream

- src/pages/pools/new.tsx
This is a small change I should have included as part of #2625.
> Add link to Arrow IPC Stream as one of the auto-detectable formats

- .github/actions/build-zui/action.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- docs/Supported-Platforms.md
- package.json
- yarn.lock
I noticed our Zui Insiders builds have been failing for the past few days. The top-level symptom of the breakage looked like this:
```
Run maxim-lobanov/setup-xcode@v1
Switching Xcode to version '13.0'...
Available versions:
┌─────────┬──────────┬─────────────┬─────────────┬────────┬──────────────────────────────────┐
│ (index) │ version  │ buildNumber │ releaseType │ stable │               path               │
├─────────┼──────────┼─────────────┼─────────────┼────────┼──────────────────────────────────┤
│    0    │ '14.2.0' │   '14C18'   │    'GM'     │  true  │  '/Applications/Xcode_14.2.app'  │
│    1    │ '14.1.0' │  '14B47b'   │    'GM'     │  true  │  '/Applications/Xcode_14.1.app'  │
│    2    │ '14.0.1' │  '14A400'   │    'GM'     │  true  │ '/Applications/Xcode_14.0.1.app' │
│ …
```
> Start using macos-12 for builds

- package.json
- packages/e2e-tests/tests/export.spec.ts
- yarn.lock
The fixes in https://github.com/brimdata/zed/issues/4207 made the CSV output smaller, so this adjusts the test's expectations to the new size so it'll pass again. If it turns out anything can be done about https://github.com/brimdata/zed/issues/4342, we'll need to do a similar adjustment when that fix merges.
> Adjust expected CSV output size

- packages/e2e-tests/helpers/test-app.ts
- packages/e2e-tests/tests/table.spec.ts
- packages/zealot/src/zed/index.ts
- packages/zealot/src/zed/utils/typeunder.ts
- packages/zui-test-data/data/named-type.zson
- packages/zui-test-data/index.d.ts
- packages/zui-test-data/package.json
- src/components/zed-table/header-cell.tsx
- src/panes/results-pane/results-pane.tsx
- src/panes/results-pane/table-controller.tsx
- src/panes/results-pane/table.tsx
- src/zui-kit/react/table-view.tsx
When determining if values can be rendered as a table, we look at the shapes of data returned. If there is one shape, then we render it as a table. If that shape is a record, we render the record's fields as the columns of the table. The previous code did not take into account the fact that the record might be a TypeAlias instead of a TypeRecord. So now we use a new function called `typeunder` which returns the underlying type if the parameter happens to be a TypeAlias. It's recursive so it will keep going until it doesn't reach a TypeAlias class.
Fixes #2645
> Named Types Bug Fix

- src/js/auth0/index.ts
- src/js/components/Login.test.tsx
- src/js/flows/lake/buildLake.ts
- src/js/flows/lake/getAuth0.ts
- src/js/state/Lakes/types.ts
- src/js/state/stores/get-persistable.test.ts
Auth0Client uses a fixed audience value (https://lake.brimdata.io) in the authorization request it sends to Auth0, limiting Auth0Client to use with Auth0 APIs created with that value as their API identifier.  Change Auth0Client to use the audience supplied by the lake service in the GET /auth/methods response instead.  (The lake service's audience is configured with the -auth.audience flag to "zed serve", added in brimdata/zed#4356).
> Use server-supplied audience in Auth0Client

- src/js/api/pools/pools-api.ts
- src/js/components/IngestWarningsModal.tsx
- src/js/components/status-bar/ingest-progress.tsx
- src/js/electron/ops/global-dispatch-op.ts
- src/js/state/Loads/selectors.ts
- src/js/state/Loads/types.ts
- src/js/state/Pools/reducer.ts
- src/js/state/Pools/selectors.ts
- src/js/state/Pools/types.ts
- src/js/state/stores/ipc-redux-middleware.ts
- src/plugins/log-loader/index.ts
- src/test/unit/fixtures/index.ts
Ingest warnings have been broken for a while.  Fix them.
Included are fixes to some global dispatcher bugs that were causing the Pools.appendWarning reducer to run three times per dispatch.
The video below shows what ingest warnings look like now.
https://user-images.githubusercontent.com/2574448/217313236-44ebf753-2e5c-4545-abba-5af486c24bf0.mov
Closes #2554
Closes #2606
> fix ingest warnings

- src/js/electron/brim-start.test.ts
- src/js/electron/brim.ts
- src/js/electron/initializers/window-events.ts
- src/js/electron/ops/autosave-op.ts
- src/js/electron/ops/open-search-window-op.ts
- src/js/electron/session.ts
- src/js/electron/windows/window-manager.ts
- src/js/lib/file.ts
- src/test/shared/__mocks__/electron.ts
The logic for closing the last window of zui is now as follows:
1. If mac, hide the last window, don't close it. Upon activation, just shows that window again.
2. If not mac, abort the normal close window event and initiate an app quit event.
The app quit event saves the session, then closes all the windows and shuts down the main process.
This will fix much of the confusion people have had with their tab state being removed.
Closes #1817
> Quit the App in a Sane Way

- package.json
- yarn.lock
Since the e2e tests have been fussy lately, I went ahead and confirmed they're all passing locally with a recent Zed commit and am manually advancing the pointer.
> Advance Zed pointer to c770649

- .github/workflows/advance-zed.yml
Unlike the softprops/turnstyle action, which requires a runner, the concurrency group just queues the workflow.
> use concurrency group in .github/workflows/advance-zed.yml

- package.json
- yarn.lock
Pointing at a tagged Brimcap artifact in preparation for the Zui v1.0.0 release.
> Advance Brimcap dependency to tag v1.3.0

- .github/workflows/advance-zed.yml
This fixes breakage I introduced in #2665. Sad.
> fix typo in .github/workflows/advance-zed.yml

- src/js/electron/brim.ts
- src/js/electron/initializers/window-events.ts
When an update is downloaded, the app calls, autoUpdater.quitAndInstall(). This doesn't call "before-quit" but does call "before-quit-for-update".
See: https://www.electronjs.org/docs/latest/api/auto-updater#event-before-quit-for-update
Then it closes all windows and once all windows are closed calls app.quit().
Since we intercept the last window being closed on mac, and only "hide" the last window. The final quit wasn't being called after quitAndInstall() on mac.
We don't intercept the last window being closed if the "isQuitting" flag is true. 
We set this flag in the "before-quit" event.
This PR now does the same thing in the "before-quit-for-update" event which fixes the issue.
Fixes #2674
> Handle before-quit-for-update

- package.json
- yarn.lock
Since we're getting close to releasing Zui v1.0, I'd like to get the Zed dependency caught up so we're testing with something close to the next Zed release we'll tag & point at. I ran all tests locally with success at this combo.
> Advance Zed pointer to 3a2fb7829c7afc28376de608f21bfb54433cee7b

- src/js/electron/migrateBrimToZui.ts
The Zed lake storage format has recently gone through a change that's not backward compatible. Meanwhile, changes back in #2428 included a recursive copy of the lake storage as part of the Brim/Zui upgrade.
The attached video was taken with [this Dev Build](https://github.com/brimdata/brim/actions/runs/4247780001) that points at the newest Zed and shows the problem created: Upon first launch in Zui, `zed serve`'s inability to read the older storage format prevents the backend from starting up at all, so the user is confronted with a failure message.
https://user-images.githubusercontent.com/5934157/221018037-2de3ef7c-731d-4997-84f6-b08e7dfe0e79.mp4
If users want to migrate their data, the current plan of record is to point them at [migration …
> Don't migrate lake data in Brim/Zui transition

- electron-builder.json
https://github.com/brimdata/brim/issues/2459#issuecomment-1442316859 has detailed background.
tl;dr - By changing the `appId`, now when Windows and macOS users of [Brim v0.31.0](https://github.com/brimdata/brim/releases/tag/v0.31.0) auto-update or manually install Zui v1.0, their Brim install will _not_ disappear from their list of installed Programs/Applications and hence will need to be manually uninstalled. The benefit of this is that on Windows all users will have [Application Binaries](https://zui.brimdata.io/docs/support/Filesystem-Paths#application-binaries) directories with "zui" in the path and hence tools like ones planned for [Zed lake migration](https://github.com/brimdata/zed-lake-migration) can find tine CLI tools in the expected location.
Closes #2459
> Unique appId for Zui

- package.json
- src/js/electron/first-run.ts
- src/js/electron/migrateBrimToZui.ts
The changes in #2380 caused the launch of an upgraded Zui `v1.0.0` to meet the definition of a "first run" such that Release Notes were not being shown. This PR adds override logic in the Brim-to-Zui migration code so the Release Notes will still be shown in this case.
The following test results show it working in a [Dev build](https://github.com/brimdata/brim/actions/runs/4264930903) based on this branch with the one additional change of the `version` string in `package.json` being set to `1.0.0`.
In the first video we start from a GA install of Brim `v0.31.0` and upgrade to this Zui `v1.0.0` artifact. As we'd hope, the app _does_ attempt to fetch the `v1.0.0` release notes.
https://user-images.githubusercontent.com/5934157/221262767-5cd5a9e1-aeb0-46ed-af60-510aa8abdcad.mp4
The second …
> Zui v1.0.0 upgraded from Brim v0.31.0 is not "first run"

- electron-builder.json
https://www.electron.build/configuration/nsis describes the options being used here. Up until now we've always gone with the [electron-builder](https://www.electron.build/) default of a one-click, per-user install. With the combination I'm using in this PR, the user will be prompted as shown in the following video (made with a Dev build from [this Actions run](https://github.com/brimdata/brim/actions/runs/4298560382)), such that they can choose the per-machine install. After selecting that install option I logged out and logged in as a different user and confirmed I saw the Zui icon on its desktop and could launch the app ok. The app binaries in that case end up in `%ProgramFiles%\Zui` (i.e., `C:\Program Files\Zui`) rather than the `%USERPROFILE%\AppData\Local\Programs\Zui` that we're …
> Enable assisted installer so per-machine can be selected

- package.json
- yarn.lock
I've seen all the e2e tests run successfully with this pairing. I'll ultimately be making a tagged Zed release and point at that, but for now I just wanted to advance the pointer ASAP because I'd like to restart the Zui Insiders builds and see if any of those users on the public Slack channel are game to try the migration kit.
> Advance Zed pointer to 6d7b0a7

- packages/e2e-tests/helpers/test-app.ts
This fixes the following two e2e failures, which I often see.
$ yarn e2e pool-loads:17 pool-loads:26 --reporter=line
Running 2 tests using 1 worker
1) pool-loads.spec.ts:17:3 › Pool Loads › load data into a pool ==================================
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 4
+ Received  + 1
- Array [
-   "count",
-   "1",
- ]
+ Array []
20 |     await app.query("count()")
21 |     const results = await app.getViewerResults()
> 22 |     expect(results).toEqual(["count", "1"])
|                     ^
23 |     await app.mainWin.getByText("Load Successful").waitFor({state: "hidden"})
24 |   })
25 |
at /Users/noah/brimdata/brim/packages/e2e-tests/tests/pool-loads.spec.ts:22:21
2) pool-loads.spec.ts:26:3 › Pool Loads › load more data into the pool …
> fix e2e flakiness in pool-loads.spec.ts

- package.json
- yarn.lock
Pointing at a tagged Brimcap artifact in preparation for the Zui v1.0.0 release. I've confirmed locally that e2e tests are still passing.
> Advance Brimcap dependency to tag v1.4.0

- src/app/core/links.ts
- src/js/electron/windows/search/app-menu.ts
I just noticed we weren't yet linking to the new site in the Help menu, so adding that here. The URL is not yet rigged up with tags since we're still on our first Zui docs release, but I can enhance this when it's needed.
I also moved the "Show Welcome Page" entry down a hair so the most helpful docs would be up top.
> Add link to new Zui docs site in Help pull-down menu

- packages/e2e-tests/tests/table.spec.ts
This fixes the following e2e failure.
$ yarn e2e table.spec.ts:16:3 --reporter=line
Running 1 test using 1 worker
1) table.spec.ts:16:3 › Table Testing › named type shows columns =================================
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 4
+ Received  + 1
- Array [
-   "Id",
-   "IsDeleted",
- ]
+ Array []
20 |     await app.query("yield value.after") // This is a named type
21 |     const texts = await app.results.getByRole("columnheader").allInnerTexts()
> 22 |     expect(texts).toEqual(["Id", "IsDeleted"])
|                   ^
23 |   })
24 | })
25 |
at /Users/noah/brimdata/brim/packages/e2e-tests/tests/table.spec.ts:22:19
1 failed
table.spec.ts:16:3 › Table Testing › named type shows columns ==================================
> fix e2e flakiness in table.spec.ts

- src/core/menu/built-menu.ts
Fixes #2696
We were trying to send a circular object (the tree node), over IPC which resulted in an infinite loop.
Instead, only send objects that can be serialized. 
It was a mistake to send the "command" property, because that can't be easily serialized. Instead wrap it
> Fix IPC Serialization Loop

- package.json
- src/js/lib/date.ts
- yarn.lock
This version fixes CVE-2021-23371.
> upgrade chrono-node to 2.5.0

- packages/e2e-tests/helpers/test-app.ts
As noted in https://github.com/brimdata/brim/pull/2687#pullrequestreview-1320699701, now that we've added `await fields.waitFor()` in `getViewerResults()`, it seems we can remove this comment.
> Remove comment since getViewerResults waits for cells now

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/advance-zed.yml
- .github/workflows/ci.yml
- .github/workflows/notify-main-failure.yml
- CONTRIBUTING.md
- LICENSE.txt
- README.md
- docs/advanced/Remote-Zed-Lakes.md
- docs/developer/README.md
- docs/support/Brim-Zui-Transition.md
- docs/support/Supported-Platforms.md
- docs/support/Troubleshooting.md
- package.json
- scripts/lib/common.bash
- src/app/release-notes/test.tsx
- src/js/components/AboutWindow.tsx
- src/plugins/brimcap/brimcap-plugin.ts
Now that the repo has been renamed and the [old Brim wiki](https://github.com/brimdata/zui/wiki) has been replaced with a pointer to the new Zui docs site, here's more Brim-to-Zui renames throughout the repo.
@jameskerr: I know you already did a pass through the actual code with lots of renames. I found a few lingering references to "Brim" in variables names and such that I did _not_ change since I assume you left them where they were intentionally. But if you spot more and want to change them in this PR, please feel free to push to the branch. Thanks!
> More Brim/Zui renames

- yarn.lock
This version includes a fix for CVE-2021-42740.
> upgrade shell-quote to 1.8.0

- src/js/electron/windows/search/app-menu.ts
This link was still pointing an an article in the old Brim wiki that I missed when fixing all the others.
> Fix link for guidance on opening an issue

- package.json
- src/app/core/format.ts
- src/app/features/sidebar/pools-section/pool-item.tsx
- src/js/components/status-bar/ingest-progress.tsx
- src/js/state/Current/selectors.ts
- src/js/state/SessionHistories/reducer.ts
- src/js/state/SessionQueries/reducer.ts
- src/js/state/TabHistories/index.ts
- src/panes/results-pane/errors/missing-pool-error.tsx
- yarn.lock
This upgrades immer to 9.0.19, which fixes CVE-2021-3757 and CVE-2021-23436.
The changes to extraReducers functions silence the following warning.
The object notation for `createSlice.extraReducers` is deprecated,
and will be removed in RTK 2.0. Please use the 'builder callback'
notation instead: https://redux-toolkit.js.org/api/createSlice
All other changes below src are for "yarn lint".
> upgrade @reduxjs/tookit to 1.9.3

- yarn.lock
This version includes a fix for CVE-2022-39353.
> upgrade @xmldom/xmldom to 0.7.9

- yarn.lock
Upgrading the tar package removes the dependency on minimist 0.0.8, which is vulnerable to CVE-2021-44906.
> yarn up tar -R

- yarn.lock
This version includes a fix for CVE-2022-25881.
> upgrade http-cache-semantics to 4.1.1

- yarn.lock
This version includes a fix for CVE-2022-48285.
> upgrade jszip to 3.10.1

- src/js/lib/date.test.ts
This fixes the following test:unit failure, which first appeared when daylight saving time began.
$ yarn test:unit date.test.ts --noStackTrace
FAIL  src/js/lib/date.test.ts
parseInZone
✓ strict date in all zones (219 ms)
✕ reference date in all zones (4 ms)
✓ casual date in all zones (157 ms)
✓ relative expression remains (1 ms)
✓ relative with subtraction
✓ invalid relative expression
● parseInZone › reference date in all zones
expect(received).toBe(expected) // Object.is equality
Expected: "1969 12 31 15 55 00 000"
Received: "1969 12 31 16 55 00 000"
Test Suites: 1 failed, 1 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        0.797 s, estimated 1 s
Ran all test suites matching /date.test.ts/i.
Fixes #2724
> fix failure in date.test.ts

- .github/workflows/advance-zed.yml
The pw:api logs from Playwright are voluminous, and I've never found them to be useful in CI.
> disable Playwright logging in .github/workflows/advance-zed.yml

- packages/e2e-tests/tests/export.spec.ts
The intermittent failure in #2734 is a pattern that's been seen before, such as described in #2605. The stacking of the "Export Completed" pop-ups make it such that every export after the first is prone to seeing the pop-up from a prior successful export and thinking the one it just initiated has already finished. I believe this can explain why the check for the expected file size can be attempted on a file that's only been partially been written and hence fail the test.
Unlike in #2605, in this case the pop-up has enough specific text (the file extension) that we can uniquely wait on the pop-up that references each format.
Fixes #2734
> Make the Export Completed check more strict

- src/app/query-home/results/alert-view.ts
- src/panes/results-pane/inspector.tsx
- src/panes/results-pane/table.tsx
I don't have sample data where we have alert-2 and alert-1s, but the colors should change from yellow to orange to red based on the severity.
I didn't re-order the columns like we used to. It's not clear how to do it in a clean way. Maybe we can revisit if the need comes up again.
fixes: #2738
> Create Suricata Alert View

- src/app/query-home/search-area/editor/query-editor.tsx
Fixes #2763
I tested this out on macOS, Linux, and Windows using the dev artifacts from https://github.com/brimdata/zui/actions/runs/4889204739.
> Have Shift+Enter run queries when "Run Query on Enter" is unchecked

- package.json
- packages/e2e-tests/tests/export.spec.ts
- yarn.lock
https://github.com/brimdata/zed/pull/4638 changed the size of VNG files, presumably since the dictionaries are now included. That broke one of the CI tests in Zui. I manually confirmed that the VNG sizes before/after the Zed change turn back into equivalent ZSON, so it seems to safe to just change the test to treat the new size as what's expected going forward.
> Change size of VNG file expected in Export test

- CONTRIBUTING.md
Since working on #2779 confirmed that we've already been using `notarytool` for some time and will be using it exclusively going forward due to the deprecation of `altool` for notarization, here I'm switching over the "check notarization status" command line we show in the CONTRIBUTING doc.
> Show notarytool instead of altool in CONTRIBUTING

- package.json
- yarn.lock
This version includes a fix for CVE-2022-1365.
> Upgrade cross-fetch to 3.1.6

- .github/actions/setup-zui/action.yml
This parallels brimdata/zed#4690, which upgrades Zed to Go 1.20.
> Upgrade to Go 1.20

- CODE.md
- src/electron/initializers/commands.ts
- src/electron/initializers/index.ts
- src/electron/initializers/menus.ts
- src/electron/run-main/run-initializers.ts
The auto update initializer was not running because it did not alias itself when exporting its symbols in the src/electron/initializers/index.ts file. When initializers are run, they check if the name has a function called "initialize". Since the auto update export had no name, its name was "initialize". Then when the code checked if "initialize" had an "initialize" function, it was false.
The changes here are:
1. Now if that check returns false, we will throw an error.
2. The auto-update.ts initializer is now exported with an alias so that it works when called by src/electron/run-main/run-initializers.ts.
3. I added documentation of all this in CODE.md for my future self.
Fixes #2778
> Ensure all initializers export a function called initialize.

- src/domain/pools/messages.ts
- src/domain/pools/operations.ts
- src/plugins/core-pool/index.ts
Fixes #2792
Before "updating" settings, we need to "create" the settings with the default values. The problem here was we were creating things without the defaults.
> Create settings with defaults when a pool is created

- src/core/query/run.ts
When we put things in our Redux store, it "for our convenience" makes objects and arrays non-extensible. The problem here was that while that object was frozen, the zealot lib tried to add to it. If we make a copy before putting it in the store, our problems get solved.
This appeared with the s3 backed lake because of the latency. Also, this does not happen in production I don't think.
Error "Cannot add property" when accessing pool on S3-backed Zed service
Fixes #2798
> Clone array before storing in redux

- src/pages/pools/show.tsx
- src/panes/histogram-pane/d3-stacked-histogram.tsx
- src/panes/histogram-pane/pane.tsx
Initialize the width and height variables when they are undefined.
Fixes #2800
> Remove NaN-related errors when rendering historgram

- src/panes/histogram-pane/run-query.ts
The issue in #2819 looks to be a revisit of what we first saw in #2452. Like that issue, it seems the fix is as simple as adding a newline after the user's base query so that way the additional Zed that app tacks on will still be active even if the user's program ended with a comment.
Regarding coding style, I wasn't sure if indents were necessary to make it obvious that these string literals spanned multiple lines. However, the prior fix in #2519 didn't have indents and what I've got in this branch seems to pass the linter.
I've put down @nwt as an additional reviewer just to double check that there's no negative side effects we can think of from these newlines being added.
Here's the video evidence on this branch of the fix working for the three variations laid out in #2819 …
> Add newlines to histogram queries

- docs/advanced/Remote-Zed-Lakes.md
- docs/support/Filesystem-Paths.md
- docs/support/Troubleshooting.md
Recent changes to the organization of the Zed docs and the move of some filesystem paths in #2759 made a couple things go stale in the Zui docs as of when I put out the new releases yesterday. I'm fixing all that here. I've seen a build of this run clean in a broken link checker on a personal staging deploy based on this branch. I also ran through the updated Remote Lakes article on a scratch AWS VM to make sure it's all correct with the new GA releases.
> Fix links and paths

- apps/zui/src/plugins/brimcap/zeek/queries.ts
Fixes #2827, which has all the background.
The attached video shows the fix having the desired effect: Now when I have a `conn` log that lacks a `community_id` field that meets all the other requirements, the Packets button still lights up.
https://github.com/brimdata/zui/assets/5934157/163d9dfd-98b3-4a21-b323-dfc24253f62b
> Don't require Community ID on all pcap-eligible conn records

- .github/workflows/release-insiders.yml
Currently when the Zui Insiders release workflow finds the SHA has not changed since the last release, it exits as a red failure. Since PRs merge to `main` on Zui infrequently, this is likely to happen often, so I'm concerned this would get us out of the habit of checking the outputs when they "fail" and hence be at risk of missing legit failures. The changes in this PR make it so that the workflow will instead exit early as successful when the SHA hasn't changed.
FWIW, I first tested out the logic in a personal repo's workflow https://github.com/philrz/build-sha-test/blob/main/.github/workflows/foo.yml.
> If insiders release workflow finds same SHA, exit early with success

- apps/zui/src/app/query-home/search-area/zed-editor.tsx
- packages/e2e-tests/helpers/test-app.ts
- packages/e2e-tests/tests/queries.spec.ts
We just needed to target and fill in the new editor slightly differently.
> Interact with the editor correctly

- packages/e2e-tests/helpers/test-app.ts
The e2e tests recently started showing consistent failures in Actions with this symptom:
```
3) queries.spec.ts:18:3 › Query tests › session queries are the default and ordered properly in history 
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 2
+ Received  + 2
Array [
-   "from 'sample.tsv' | 3 now",
-   "from 'sample.tsv' | 2 now",
+   "from 'sample.tsv' | 123 now",
+   "from 'sample.tsv' | 12 now",
"from 'sample.tsv' | 1 now",
]
31 |       "from 'sample.tsv' | 1 now",
32 |     ];
> 33 |     expect(entries).toEqual(expected);
|                     ^
34 |   });
35 |
36 |   test("named queries' creation, modification, update/save, proper outdated status display", async () => {
at /home/runner/work/zui/zui/packages/e2e-tests/tests/queries.spec.ts:33:21
at …
```
> Only use Meta+KeyA combo to Select All on macOS

- packages/e2e-tests/tests/pool-loads.spec.ts
In a recent group discussion about some of the approaches proposed to address #2843, @jameskerr expressed a preference for the 2nd proposal that "tagged" queries and their results. However, since implementing that would require @jameskerr to interrupt his other priorities, I went ahead and tested the changes in this PR that are what's described in the 3rd proposal. I tested it out using my Linux VM with the config/script described in https://github.com/brimdata/zui/issues/2843#issuecomment-1694016932. The tests confirmed that these changes do indeed greatly improve reliability of the test, as a baseline run of the `cycle.sh` at Zui commit 3d3b66d saw 18 failures out of 200 runs, whereas f9fc137 running the `cycle.sh` at Zui commit f9fc137 from this branch saw 0 failures out of 200 runs.
I …
> Wait for Load Successful to disappear first in pool-loads e2e test

- apps/zui/package.json
- yarn.lock
We recently became aware of some CVEs that been addressed in more recent versions of Electron, so here we're advancing the dependency to take advantage of those fixes.
> Advance Electron dependency to 22.3.25

- .github/workflows/release-insiders.yml
In the days right before publishing the GA Zui v1.3.0 release, I realized that Zui Insiders releases had not been getting published for a while. A peek at [a recent attempted release](https://github.com/brimdata/zui/actions/runs/6341276778) seemed to show what was going on: The "Check If Release Is Needed" seemed to be finding tag `1.2.1-9` as the "latest" even though `1.2.1-10` had been published for weeks. The "Build Zui" would therefore proceed as if it was building `1.2.1-10`, then it would bail on actually uploading any artifacts, saying:
```
• GitHub release not created  reason=existing release published more than 2 hours ago tag=v1.2.1-10 version=1.2.1-10 date=Tue Aug 29 2023 03:27:05 GMT+0000 (Coordinated Universal Time)
• skipped publishing  file=zui-insiders_1.2.1-10_amd64.deb …
```
> Use a different action to get latest Zui Insiders release

- apps/zui/src/js/lib/date.ts
A console debug message indicated that when the crash in #2853 was occurring, the `d` value returned from `chrono.casual.parse()` was the empty array `[]`. As shown in the attached video based on this branch, it therefore looks like just checking that this array is non-empty is enough to avoid the crash.
https://github.com/brimdata/zui/assets/5934157/e11d24aa-1c22-43f7-9a1d-7bdfb41ae321
Fixes #2853
> Check array is non-empty before referencing 0th element

- apps/zui/scripts/download-zdeps/index.js
When investigating the reports linked from #2857, one of the high-level patterns observed was reference to the Suricata rules that ship with Zui as part of Brimcap. Thinking these might be a root cause of the many evidence-of-malware flaggings found in the reports, one of our community members that works in the cybercrime team at Mandiant/Google confirmed our suspicion that this might be a root cause of some/all of the problems.
> the sandbox detections on the rulesets makes sense to me, ive seen that problem with other rulesets in the past where AV sigs are too loose and hit on detections for malware instead of the malware itself. 
The shipped fallback rule sets have always been "nice to have" because they'd potentially allow some initial alerts even when installing Zui in an airgapped …
> Filter out Suricata rules when assembling zdeps on Windows

- apps/zui/CHANGELOG.md
- apps/zui/package.json
- apps/zui/scripts/download-zdeps/index.js
Ordinarily I'd make changes like the CHANGELOG updates and advancing the `version` string in a  "prep" branch that's merged to `main`, then base the `release/` branch on `main` after that merges. However, since my goal here is to create a true patch release that only contains the fix in #2858, I'm approaching things in reverse.
In this branch I've cherry-picked the changes from #2858 and then made the necessary CHANGELOG and `version` changes. The draft release artifacts are at https://github.com/brimdata/zui/releases/tag/untagged-edbac20bc65f91d4104d, which I've smoke tested and confirmed run [clean on VirusTotal](https://www.virustotal.com/gui/file/9c5d3c3510eb1ac1bc5f9cbf1f4fe113c1b9d0c117861ed08f0385ca11c64c7b) and also [clean on Record Future …
> Patch release v1.3.1

- packages/zui-player/README.md
Looks like someone leaned on the enter key and broke this link by accident. 😛
> Fix broken link

- .github/workflows/build-insiders.yml
I tried to use this workflow for the first time in a while and it failed (https://github.com/brimdata/zui/actions/runs/6630692331). I dug into the history a bit and it looks like some changes to the regular Insiders Release workflow in #2833 and #2818 didn't make their way into this workflow. I've made what I think are the necessary changes to get it running again and have successfully built/installed/used an artifact based on this branch (https://github.com/brimdata/zui/actions/runs/6632098539).
> Fix Zui Insiders dev builds

- apps/insiders/jest.config.ts
- apps/zui/src/domain/loads/handlers/choose-files.ts
- apps/zui/src/domain/loads/messages.ts
- apps/zui/src/domain/messages.ts
- apps/zui/src/electron/windows/search/app-menu.ts
- packages/sample-data/jest.config.ts
- packages/zed-node/src/zq.test.ts
- packages/zui-test-data/jest.config.ts
https://github.com/brimdata/zui/assets/3460638/19c87399-84b2-4868-ab5d-7d889c6dec49
> Add Menu Option with Shortcut for Opening File

- package.json
I recently noticed when running tests locally that I'd often see output like this:
```
$ yarn test
✔  nx run zed-js:test  [existing outputs match the cache, left as is]
✔  nx run sample-data:test  [existing outputs match the cache, left as is]
✔  nx run zui-test-data:test  [existing outputs match the cache, left as is
✔  nx run zed-node:test  [existing outputs match the cache, left as is]
✔  nx run zui:test  [existing outputs match the cache, left as is]
✔  nx run insiders:test  [existing outputs match the cache, left as is]
——————————————————————————————————————————————————————————————————————————————
>  NX   Successfully ran target test for 6 projects (319ms)
Nx read the output from the cache instead of running the command for 6 out of 6 tasks.
```
@jameskerr explained that I could just …
> Add --skip-nx-cache when running "yarn test"

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
The automation at https://github.com/brimdata/zui/actions/runs/6726418931 triggered by the merge of https://github.com/brimdata/zed/pull/4834 saw a test failure because the exported VNG file size changed slightly due to the changes in that PR. Based on the description in that PR I'm assuming this was expected and indeed the size change is reproducible with just `zq`. @nwt since you reviewed that PR I'll merge this change if you'd agree this seems to be in line with your expectations.
(I'm guessing the VNG format may change repeatedly in the weeks ahead as more work is being done on the vector engine. I therefore assume a case could be made for dropping the automation that checks the size of the VNG file and treats it as an error when it doesn't match. Personally, though, I like knowing we …
> Adapt to change in VNG format from zed/4834

- apps/zui/src/app/features/inspector/views/null-view.ts
- apps/zui/src/app/features/inspector/views/record-view.ts
- apps/zui/src/app/query-home/loader.ts
- packages/zed-js/src/types/type-map.ts
- packages/zed-js/src/types/type-record.ts
- packages/zed-js/src/values/record.ts
- Records can have null fields.
- Fix More Nulls
That emties file now looks like this:
> Fix More Nulls

- .github/actions/build-zui/action.yml
- .github/actions/setup-zui/action.yml
https://github.com/brimdata/zui/issues/2882#issuecomment-1796838240 has background.
At first I tried the workaround `python3 -m pip install packaging` that's discussed most frequently at https://github.com/nodejs/node-gyp/issues/2869. My [first Dev build](https://github.com/brimdata/zui/actions/runs/6776425490) with that workaround came out fine on macOS. I then thought it'd be good to add a comment in the Actions YAML mentioning it's a workaround for this issue. Out of pure paranoia, I made [yet another Dev build](https://github.com/brimdata/zui/actions/runs/6777254187) and that one failed with the same `No module named 'distutils'` on macOS that started this all. I can't explain what was going on there since the run log shows it successfully running the `python3 -m pip install …
> Pin Python to 3.11 to work around zui/2882

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
The Zed pointer hasn't advanced successfully for a while due to the `node-pipe` build breakages tracked in #2882. But now that's fixed, we've got legit failures like the one adapted to here which I've traced to the changes in https://github.com/brimdata/zed/pull/4862. Please approve if the VNG file size change is expected.
> Expect slightly larger VNG export

- apps/zui/docs/advanced/README.md
- apps/zui/docs/developer/README.md
- apps/zui/docs/features/Preview-Load.md
- apps/zui/docs/features/README.md
I've made a video showing off the new Preview & Load feature that's due to go out with the upcoming GA Zui v1.4 release. To give it a home, here I've made a new "Features" section of the Zui docs site and a entry there that links to the video along with supporting materials.
I hope to make similar videos soon to touch on some other features in the app that users tell us they discovered late, e.g., the right-click menu.
> Add new "Features" docs section and Preview & Load video

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- apps/zui/package.json
When trying to build the GA Zui v1.4.0 release candidates it became apparent that the move from `nx` `15.8.7` to `16.10.0` as part of #2834 caused an unexpected problem: Somewhere between those versions they introduced an [`nx release`](https://nx.dev/nx-api/nx/documents/release) command that happened to clash with our use of `release` as a target in Zui's `package.json`. Once that was understood, the workaround of changing the target name as shown in this PR got me up & running again quickly.
Since we already had `release-insiders` I opted to call the new target `release-zui` for symmetry. Then I did similar treatment turning the adjacent `package` target into `package-zui` for consistency, plus it insulates us against the possibility that the verb `package` gets claimed one day by `nx` …
> Rename "release" target to avoid clash with "nx release"

- apps/zui/src/app/core/links.ts
The motivation for creating the recent Zui [v1.4.1](https://github.com/brimdata/zui/releases/tag/v1.4.1) patch release was to make sure app users had the corresponding Zed [v1.11.1](https://github.com/brimdata/zed/releases/tag/v1.11.1) patch release. We've not traditionally tagged new sets of Zed docs on https://zed.brimdata.io for each patch release since there's usually not something doc-worthy, extra docs tags for no reason would clutter the "versions" drop-down, and it would add bulk to the zed-docs-site repo. However, Zui has traditionally been wired up to tie the Zed docs URL in the **Help** pull-down to whatever tagged Zed release it shipped with, so when that patch release was built the assembled docs URL was a broken link. Our CI caught this and I was easily able to work around …
> Assume Zed docs are not made for Zed patch releases

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
I've confirmed that this change in VNG file size came with https://github.com/brimdata/zed/pull/4881 which disclosed up front that it was a "breaking change to VNG" hence no surprise.
> Advance Zed pointer and adjust to new VNG size

- apps/zui/docs/support/Filesystem-Paths.md
There once was a time when the pull-down menu for changing app config was called **Preferences** on macOS and **Settings** on Windows/Linux. This led to it being referenced inconsistently in the docs. Between changes in #2866 and general macOS trends, we've now standardized on **Settings**, so here I'm switching the one place in the Zui docs that still called it by the other.
> Reference Settings, not Preferences

- apps/zui/electron-builder.json
#2914 has the background and repro. The change in this PR is based on what I found in https://github.com/vector-im/element-web/issues/17188 and how they fixed it via https://github.com/vector-im/element-desktop/pull/337/files, since their symptom looks exactly like ours.
I made a Dev build https://github.com/brimdata/zui/actions/runs/7064639612 using the change on this branch and it tested out fine. I used it to repeat the same repro steps shown in the video in https://github.com/brimdata/zui/issues/2914#issuecomment-1834932637 and none of the `.org.chromium.Chromium.*` accumulated this time. The app also ran otherwise healthy, and in particular, I was able to import/query data, which is a sign that `node-pipe` (one of the modules now subject to different packaging) was still working …
> Prevent packing of native modules

- apps/zui/docs/support/Supported-Platforms.md
Some additional notes on the testing to provide context for what went into the article updates:
1. The loaner Brim MacBook that I've traditionally used for testing that Zui still runs on super old macOS releases won't even install Big Sur (macOS 11) anymore. I have every reason to assume Zui still runs on there, but I don't feel confident claiming it does unless I can repro issues on it in a pinch. Based on my web searches, Apple's support for Big Sur may be wrapping up right about now anyway, so I figure it's no big loss.
2. I definitely saw Zui work on Windows 8.1 in the past, but for whatever reason this time went I went to repeat the smoke test I couldn't get Wireshark to work. That's when I noticed that Microsoft has officially announced EOS on Windows 8.1 overall, so I was happy to …
> Update Supported Platforms article for Fall of 2023

- apps/zui/src/electron/meta.ts
- apps/zui/src/electron/windows/search/app-menu.ts
- apps/zui/src/views/update-window/index.tsx
While verifying #1211, I noticed that in the Zui Insider's pull-down menu options for:
* **Help > GitHub Repository**, and,
* the **View Releases** link that's shown when a **Check for Updates** finds nothing newer available
...the repository URL for "regular" Zui is provided instead of the one for Zui Insiders. This PR fixes that.
The following video shows the new functionality using a [Zui Insiders Dev Build](https://github.com/brimdata/zui/actions/runs/7269738279) based on this branch.
https://github.com/brimdata/zui/assets/5934157/89269fb5-b37c-4cef-b5ec-d659f941cc76
> Point to repository setting in package.json

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
The changes in https://github.com/brimdata/zed/pull/4960 dropped the size of the exported VNG file by a byte. Assuming that's unsurprising, this PR moves the Zed dependency forward and adjusts the test to expect that as the new normal.
> Adjust expected VNG export size due to zed/4960

- apps/zui/package.json
- apps/zui/scripts/esbuild.mjs
- packages/zed-node/src/lake.ts
- yarn.lock
Rely on child_process.spawn() to create a pipe instead.
Closes #1165.
> Remove node-pipe dependency

- .github/actions/setup-zui/action.yml
This reverts commit d29e6744b1cac6733dd47973c79843058d165bbb.
Reason for revert: #2956 removed the node-pipe dependency so this workaround for #2882 is no longer necessary.
> Revert "Pin Python to 3.11 to work around zui/2882 (#2883)"

- .github/workflows/advance-zed.yml
- .github/workflows/e2e.yml
- package.json
- packages/zui-player/ci.config.js
- packages/zui-player/package.json
For the "Advance Zed" workflow, this PR proposes trimming the set of e2e tests to only those that have a history of running reliably in GitHub Actions.
To test it, I created a separate workflow that just runs the e2e tests. Rather than scrapping it, I'd propose keeping it around since exercises like this have come up a couple times in the past and it seems a little silly to keep recreating it every time.
The `title-bar-buttons.spec.ts` test that was just added as part of #2953 seems to run reliably locally on macOS, but in [first attempts to run in Actions](https://github.com/brimdata/zui/actions/runs/7425676367) it failed 5 times out of 5 (`Test timeout of 30000ms exceeded. / Error: locator.click: Application exited`). While we could invest cycles into seeing why this particular test …
> On GitHub Actions, run only the e2e tests that are reliable there

- packages/zed-node/src/zq.test.ts
One of our tests that does _not_ typically fail in CI failed twice close together this morning:
* https://github.com/brimdata/zui/actions/runs/7463628055/job/20308754610
* https://github.com/brimdata/zui/actions/runs/7465184326/job/20313785582
The failure looks like:
```
FAIL zed-node packages/zed-node/src/zq.test.ts (5.579 s)
● head 100 on guns 
expect(received).rejects.toThrowError()
Received promise resolved instead of rejected
Resolved to value: []
112 |   });
113 |
> 114 |   expect(promise).rejects.toThrowError('error parsing Zed');
|   ^
115 | });
116 |
117 | test('head 100 on guns ', async () => {
at expect (../../node_modules/expect/build/index.js:105:15)
at Object.expect (src/zq.test.ts:114:3)
```
What sticks out about this is that the `head 100 on guns` is from the test _after_ …
> Wait on rejected promise in "bad zed" test

- .github/workflows/e2e.yml
I'm hoping to invest some time to better understand and hopefully fix some of the problems we have with e2e test reliability in GitHub Actions CI. As a step toward that, in this PR I've added some flexible Inputs to the "Run e2e tests" Workflow. After this change, if the Workflow is invoked with all inputs at their defaults, it'll still run the e2e tests the same way they are in the "Advance Zed" workflow. But those inputs can now be varied to run any command line (e.g., `yarn e2e` ...) on any set of OS platforms, which makes it easier to repro specific problems and confirm fixes.
For instance, in [this run](https://github.com/brimdata/zui/actions/runs/7483368374) I ran only the `copy-paste` tests and did it across all OSes.
> Add flexible inputs to Actions Workflow for running e2e tests

- .github/workflows/advance-zed.yml
- .github/workflows/e2e.yml
I started looking into using artifacts to debug our e2e test failures in CI, and that's when it became apparent that we need to update the paths to reflect the new paths in the monorepo.
As part of that I also wanted to start looking at [Playwright traces](https://playwright.dev/docs/trace-viewer) that are now easy to enable due to the changes in #2961, but they land in a different path so I've added that too.
Also, some of our recent test failures have scary-sounding "Application exited" messages that have sometimes had me wondering if out-of-memory killers have been shooting our software in the middle of test runs. My research thus far indicates that's _not_ the case, but just to be sure, I've added some system log paths to the artifact gathering to make that easy to rule out. I logged …
> Adjust paths for finding artifacts

- .github/workflows/advance-zed.yml
- .github/workflows/e2e.yml
The new `right-click-menus.spec.ts` e2e test set that was added as part of #2895 has failed 100% of the time in CI due to a problem with the `who is` test case. A recent example failure from [this run](https://github.com/brimdata/zui/actions/runs/7492874104):
```
2) right-click-menus.spec.ts:56:3 › right-click-menus › who is ───────────────────────────────────
Test timeout of 30000ms exceeded.
Error: locator.click: Application exited
Call log:
- waiting for getByRole('button', { name: 'Done', exact: true }).first()
-   locator resolved to <button type="button">Done</button>
- attempting click action
-   waiting for element to be visible, enabled and stable
-     element is not stable - waiting...
- element was detached from the DOM, retrying
at ../helpers/test-app.ts:162
160 |
161 | …
```
> Install whois in CI so right-click test can succeed

- .github/workflows/e2e.yml
Since I plan to make ample use of Inputs in this "Run e2e tests" Workflow, I went looking for the best way to log the inputs that were used for a given run. Of the ideas batted around [here](https://stackoverflow.com/questions/71155641/github-actions-how-to-view-inputs-for-workflow-dispatch) I chose one for this PR. When in use it looks like:
> Output the "Inputs" used for e2e run

- .github/workflows/e2e.yml
- packages/zui-player/README.md
- packages/zui-player/helpers/test-app.ts
I've been trying out Playwright's ability to capture videos during tests. It's been a little tricky getting the full story (https://github.com/microsoft/playwright/issues/8208 points to some of the work-in-progress), but based on what I've tried thus far it seems that the [top-level `use.video` config](https://playwright.dev/docs/videos) does _not_ work for Electron apps. This is a mild bummer since that has some nice granular options like `retain-on-failure` so you don't bother storing video for all successful runs. But in the spirit of "better than nothing", I _have_ had some success with the [Electron-specific `recordVideo` config](https://playwright.dev/docs/api/class-electron#electron-launch-option-record-video) I'm using in this PR's branch. Per the doc it "enables video recording …
> Playwright videos

- packages/zui-player/ci.config.js
The e2e tests in [packets.spec.ts](https://github.com/brimdata/zui/blob/main/packages/zui-player/tests/packets.spec.ts) that were recently added unfortunately fail consistently in CI. I'm using it as one to study in my mission to become better at debugging Playwright and fixing up our tests to make them CI-friendly. But in the interim we should exclude it and let the Zed pointer advance do its thing.
https://github.com/brimdata/zui/actions/runs/7531833080 is proof that the e2e tests run fine once the exclusion is in place.
> Don't run the e2e packets tests in CI for now

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
This adapts to the changes from https://github.com/brimdata/zed/pull/4984.
Since I now have an easy way to run e2e tests a la carte, I verified the change in Actions run https://github.com/brimdata/zui/actions/runs/7532990716 which ran fine for VNG but also saw a failure on a _different_ export format. The good news is that #2967 should fix that one too. 😛
> Expect smaller VNG file size

- .github/workflows/e2e.yml
When I started gathering system logs in #2962, this awakened an unfortunate behavior of the `upload-artifact` Action: Once I start asking it to include a root level path in the artifacts bundle, it uses root-based paths for _all_ the artifacts. So for instance on macOS the unpacked artifacts bundle was starting to look like:
This just creates lots of extra clicks to get to the good stuff. Therefore in this PR I make a directory alongside the other Playwright artifacts and put the system logs there so now I get the more sane hierarchy:
> Copy from /var/log into folder alongside Playwright artifacts

- packages/zui-player/tests/export.spec.ts
Now that I can capture Playwright test failures on video (#2966) I've been reproducing them and trying to figure out where we can make improvements.
While we run our e2e tests for "Advance Zed" only on Ubuntu, one thing I've noticed is that it seems I can reproduce problems with some of our tests more frequently by using alternate Actions Runners such as macOS. I'm not 100% certain _why_ this is the case, but since the intermittent failures often come down to timing issues, it seems like fixing them where they happen most often could reduce the (rarer) failures on Ubuntu runners or our own laptops and maybe lead us to a future where we actually run e2e tests regularly on all OSes to get better coverage.
The one I've been studying most recently and am attempting to improve in this PR is …
> Improve timing in e2e Export test

- apps/zui/electron-builder.json
- apps/zui/package.json
- yarn.lock
[v6.0.2-brim3](https://github.com/brimdata/build-zeek/releases/tag/v6.0.2-brim3) is a new Zeek artifact that's included in the [Brimcap v1.6.0-beta1](https://github.com/brimdata/brimcap/releases/tag/v1.6.0-beta1) pre-release artifact pointed at by this branch. I propose merging this PR to allow us to start using the new Zeek in our own internal Zui testing and also encourage community users to start trying it out via Zui Insiders.
Assuming that all goes well, when prepping the next set of GA release, I'll make a GA Brimcap `v1.6.0` that points to the same [v6.0.2-brim3](https://github.com/brimdata/build-zeek/releases/tag/v6.0.2-brim3) Zeek, and Zui can start pointing at that GA Brimcap+Zeek combo.
I've made a [Zui dev build](https://github.com/brimdata/zui/actions/runs/7547974747) based …
> Point to Brimcap that uses new build-zeek artifact

- .github/workflows/e2e.yml
Sometimes when I'm debugging e2e tests I want to see the uploaded artifacts (Playwright videos, etc.) even if the run is not a failure. This change adds an Actions Input toggle to allow for that.
I tested out that the new checkbox works as intended with [this run](https://github.com/brimdata/zui/actions/runs/7550945571) and also confirmed in [this run](https://github.com/brimdata/zui/actions/runs/7552033865) that it maintains its default behavior of always uploading artifacts if the run is a failure.
> CI e2e option to always upload artifacts even for non-failures

- .github/workflows/e2e.yml
- packages/zui-player/helpers/test-app.ts
- packages/zui-player/tests/export.spec.ts
Per https://github.com/microsoft/playwright/issues/8208, one of the general Playwright features that's not quite there yet for Playwright-on-electron is fancy screenshot options such as top-level config that would capture them automatically in the event of test failures. However, it's quite easy to take them during debug iterations using a helper function like the one I'm adding in this PR. https://github.com/brimdata/zui/commit/a71fbad9f1a1c46dbd9dfd139086b56c97f5b171 shows an example where I used this helper function in [this Actions run](https://github.com/brimdata/zui/actions/runs/7562784692) to take screenshots during the Exports test right after each export succeeds.
> Playwright screenshots for e2e tests

- .github/workflows/advance-zed.yml
- .github/workflows/e2e.yml
While working on the e2e tests I saw notification that the [`GabrielBB/xvfb-action`](https://github.com/marketplace/actions/gabrielbb-xvfb-action) we've been using to run Zui inside X11 in CI has been deprecated. While they point to a maintained replacement [`coactions/setup-xvfb`](https://github.com/coactions/setup-xvfb), someone points out in https://github.com/coactions/setup-xvfb/issues/21 that `xvfb` is now built right into the hosted GitHub Actions Ubuntu Runners. This PR switches us using the built-in `xvfb` instead.
One of the features of the Action was:
> If it detects you're not using linux then your tests still run, but without xvfb, which is very practical for multi-platform workflows.
This is why there's a conditional now in `e2e.yml`. …
> Non-Action xvfb

- .github/workflows/e2e.yml
- packages/zui-player/tests/packets.spec.ts
Data shows that loading pcaps in CI can take a long time. Therefore this PR proposes increasing timeouts for tests that load pcaps.
Some additional Playwright debug logging was useful in crafting this PR, so I'm also proposing keeping that around.
I've been on a mission to understand why the e2e `packets.spec.ts` test consistently fails in CI on Ubuntu. During my research, I also found that the test actually runs fine on both Windows and macOS, but the variance on the time to load the pcap test data is significant, with observed load times sometimes getting above 1-minute. If we hit the default 30-second test timeout in CI, that does little more than interrupt us to examine the failure, conclude that our run got landed on an Actions Runner that's having a bad day, and click re-run. …
> Increase timeouts for e2e Packets tests

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
Given the scope of the changes in https://github.com/brimdata/zed/pull/5001 I assume the change in the VNG file size is expected.
> Adjust to new expected size for VNG export

- apps/zui/package.json
- yarn.lock
Companion to https://github.com/brimdata/build-zeek/pull/8.
> Point to Brimcap that uses Zeek v6.0.3-based artifact

- .github/workflows/advance-zed.yml
- .github/workflows/e2e.yml
- packages/zui-player/ci.config.js
Ever since the e2e `packets.spec.ts` test was added, we've seen it fail consistently in CI. The failure always happens during the `afterAll` step, such as during [this Actions run](https://github.com/brimdata/zui/actions/runs/7620273940):
```
1) packets.spec.ts:26:3 › packets.spec › loading a bad pcap displays an error message ────────────
"afterAll" hook timeout of 30000ms exceeded.
at ../index.ts:14
12 |     });
13 |
> 14 |     test.afterAll(async () => {
|          ^
15 |       await app.shutdown();
16 |     });
17 |     body(app, test);
at /home/runner/work/zui/zui/packages/zui-player/index.ts:14:10
```
Things I learned through hacking:
1. The failure did not occur on Actions Runners for macOS or Windows.
2. While I'd only observed the failure on the Actions Runner for Ubuntu, I …
> Fix packets e2e test in CI

- apps/zui/src/plugins/brimcap/zeek/correlations.ts
- apps/zui/src/plugins/brimcap/zeek/queries.ts
- apps/zui/src/plugins/brimcap/zeek/util.ts
- apps/zui/src/ppl/detail/models/Correlation.ts
- apps/zui/src/ppl/zeek/descriptions.ts
Fixes #2980
When #2971 merged, Zui went from using a Zeek artifact based on Zeek v3.2.1 to an artifact based on Zeek v6.0.2. This exposed Zui to a "breaking change" as part of Zeek [v5.1.0](https://github.com/zeek/zeek/releases/tag/v5.1.0) that broke the **Download Packets** feature in some circumstances as shown in #2980. From the Zeek release notes:
> By default, `files.log` does not have the fields `tx_hosts`, `rx_hosts` and `conn_uids` anymore. These have been replaced with the more commonly used `uid` and `id` fields.
Here's the affected code as it stands on the tip of `main`:
https://github.com/brimdata/zui/blob/e275ddd2040b5843d68609afb29648d2f5b7e781/apps/zui/src/plugins/brimcap/zeek/queries.ts#L21-L34
https://github.com/brimdata/zui/blob/e275ddd2040b5843d68609afb29648d2f5b7e781/ap …
> Adapt to Zeek "files" log losing conn_uids+tx_hosts+rx_hosts and gaining uid+id

- apps/zui/src/app/features/inspector/views/type-record-view.ts
- apps/zui/src/core/query/run.ts
- apps/zui/src/js/api/zui-api.ts
- apps/zui/src/views/histogram-pane/run-query.ts
- packages/zed-js/src/query/channel.ts
- packages/zed-js/src/query/result-stream.ts
1. Fix presentation of null record types.
2. Properly abort queries.
3. Provide shallow copies of objects in the collect callback.
**Details**
We were not catching the abort error properly when issuing a query before the previous query finished.
We also were not aborting all of the histogram queries when re-issuing a search.
This stuff is really hard to write tests for. There are no tests in this PR. 🤷‍♂️
To test this, re-issue the search with a large pool over and over again rapidly. Open the network tab and view all the in-flight requests properly cancelling when a new search is issued.
Fixes #2997
Fixes #2999
> Fix Bugs Discovered by Steve

- apps/zui/package.json
- yarn.lock
This points Zui at a Brimcap commit that includes the fix from https://github.com/brimdata/brimcap/pull/336. By merging this into Zui ASAP we can get it into a Zui Insiders release so the community user that reported the problem can benefit immediately.
The attached video is run with this branch to show the symptom shown in https://github.com/brimdata/brimcap/issues/19#issuecomment-1939379105 has been addressed.
https://github.com/brimdata/zui/assets/5934157/d204ddd9-f2f2-436b-b851-933f9aa35252
> Point to Brimcap that has the cooked/SLL fix

- apps/zui/src/plugins/brimcap/zeek/correlations.ts
A recent [Zeek community Slack thread](https://zeekorg.slack.com/archives/CSZBXF6TH/p1706728046628519?thread_ts=1706727605.964379&cid=CSZBXF6TH) educated me about the `is_orig` field of Zeek [`files`](https://docs.zeek.org/en/master/scripts/base/frameworks/files/main.zeek.html#type-Files::Info) logs. As those docs explain:
> If the source of this file is a network connection, this field indicates if the file is being sent by the originator of the connection or the responder.
In the changes I pushed in #2981 I wasn't yet aware of this so for the result in the Correlation view I'd just set the `tx_host` to be the `id.resp_h` of the `files` event and likewise set the `rx_host` to be the `id.orig_h`. This all makes sense for the common case of a file download, but it's incorrect for file …
> Use the Zeek is_orig field to set files tx_host/rx_host

- packages/zed-node/src/lake.ts
Now that https://github.com/brimdata/zed/pull/5017 has merged, it's easy to have Zui start leveraging the approach to periodically run compaction to improve performance.
There's a few fancy ideas we could pursue that I'm not currently advocating.
1. As noted in #2847, we could enable a user-configurable **Setting** to enable/disable whether `manage` is run at all, e.g., if we wanted to start with it disabled have this be an "opt in" feature at first, or if we wanted to start with it enabled but wanted to give users an easy way to turn it off. However, since compaction allows for best case lake performance, we'll generally want all users to be running it continuously. In the event a bug makes users want to opt out while we work on a fix, they could always reinstall the prior Zui release …
> Enable compaction by having the Zed service run "manage" every 5 minutes

- apps/zui/src/views/export-modal/index.tsx
As I was making the screen cast to share on twitter, I noticed the export modal changes it's width when you change export destinations between file and pool. This PR gives the export modal a consistent width.
> Give the export modal a max width

- apps/zui/src/domain/loads/file-loader.ts
The "auto-detect failure messages" described in the 4th bullet at #3025 were not something I expected to see. As far as I can tell the `zq`-based shaper is always present in Zui's "file loader" pipeline (but this is something I'm hoping can be confirmed via review!) By default `zq` will always output binary ZNG in such a pipeline. Normally a `load` operation to the Zed lake will always happily auto-detect binary ZNG input so this has not generally been a problem. However my repro details in https://github.com/brimdata/zed/issues/3865#issuecomment-1995839362 show that this `mun.json` test data from #3025 seems to pose a unique challenge because `zq`'s ZNG output from reading that particular JSON happens to fail `load` via auto-detect.
While that Zed issue remains a mystery for the moment, …
> Specify explicit ZNG format from file loader

- apps/zui/package.json
- yarn.lock
https://github.com/brimdata/brimcap/pull/338 includes an artifact based on the latest Zeek release. When I next prep GA releases I'll tag a proper Brimcap release, but as early prep for that, I'd like to get Zui pointing at that new Brimcap ASAP so I can push a Zui Insiders release to the community for testing before those GA releases get assembled.
> Point to Brimcap that uses Zeek v6.2.0 artifact

- apps/zui/package.json
- apps/zui/src/components/zed-editor.tsx
- apps/zui/src/electron/protocols/asset-server.ts
- apps/zui/src/electron/protocols/asset-url.test.ts
- apps/zui/src/electron/protocols/asset-url.ts
- apps/zui/src/electron/run-main/run-protocol-handlers.ts
- apps/zui/src/electron/windows/zui-window.ts
- apps/zui/src/js/initializers/init-monaco.ts
- yarn.lock
Fixes #2915
The editor now loads without an internet connection. Instead of reaching out to a CDN, electron intercepts the request and serves it from node modules.
Here is the editor loaded.
And here is the sources tab revealing no network requests.
In order to get this working properly in development, I had to disable web security in the browser windows to allow for cross-origin javascript requests. This is only needed in development because we serve the html from a dev server. In production we serve the files from the same origin that we serve the monaco files, so they are on the same origin already.
I would love to test this in a release to make sure I stitched all the paths together correctly in a release environment.
> Load Monaco Files From Node Modules Folder

- README.md
- apps/zui/CONTRIBUTING.md
- apps/zui/README.md
In the time since #2818 merged, the top-level README for the repo has been incomplete/inaccurate. In this PR I propose moving the Zui app README detail to the top-level README and including a section that describes it all being a monorepo and what other packages are available. I've included a few other clean-ups along the way, which is mostly just adding/fixing hyperlinks.
> README adjustments

- apps/zui/src/models/browser-tab.ts
- packages/zui-player/tests/queries.spec.ts
**Context**
When a tab history object is created, it already contains a single entry with the root pathname "/". In a previous PR, I changed the order of creating session tabs to 1) create the tab, 2) load the url in that tab. This made the code much easier to reason about, but it left this dangling "/" entry in the tab history. The meant the back button was enabled on a newly created session tab. If clicked, the tab would go back to the "/" url which renders a blank page without any buttons. You could not get back to your session if you ended up in this state. Could be very irritating if you needed those session history queries.
**Changes**
So this PR changes the BrowserTab#load function. It checks if the tab history entries equals ["/"]. If it does, it resets the entries to [] and the …
> Replace the tab entries on first load

- apps/zui/package.json
- apps/zui/src/app/core/models/zed-expr.ts
- yarn.lock
Upgrade the logic of zed AST to support the newly added IndexExpr node.
> models.Zed: Support IndexExpr

- packages/zui-player/ci.config.js
This was supposed to be taken care of by the changes in #3033, but a [recent CI failure in Actions](https://github.com/brimdata/zui/actions/runs/8652204264) made me aware that I'd made a mistake in my prior change and the test was still being run in CI. I confirmed in [this Actions run based on this branch from this PR](https://github.com/brimdata/zui/actions/runs/8652951958/job/23727018507) that I made the correct change this time, since it shows 50 e2e tests being run rather than the prior 51.
> Skip running e2e pool-load-fail test in CI

- apps/zui/src/domain/configurations/plugin-api.ts
- apps/zui/src/plugins/brimcap/config.ts
- apps/zui/src/plugins/brimcap/configurations.ts
- apps/zui/src/plugins/brimcap/suricata/update.ts
- apps/zui/src/views/settings-modal/input.tsx
We've had a couple community issues recently where users mistakenly thought Zui's **Brimcap YAML Config File** setting may have been intended for loading additional local Suricata rules (#3047, #2949). We've never intended to expose UX in Zui to control all the possible customizations in bundled tools like Suricata and instead of tried to maintain a set of sensible defaults to which we've added modest enhancements over time when resources allow. When users ask for customizations that are more ambitious than we can easily offer, our catch-all/fallback answer is to refer them to the [Custom Brimcap Config](https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config) article that guides them through how they can point Zui at their own installs of pcap analyzers like Suricata that they've …
> Add Setting for pointing at local Suricata rules

- apps/zui/src/domain/configurations/plugin-api.ts
- apps/zui/src/plugins/brimcap/config.ts
- apps/zui/src/plugins/brimcap/configurations.ts
- apps/zui/src/plugins/brimcap/packets/download.ts
- apps/zui/src/views/settings-modal/input.tsx
As described in #1423, we've recognized that a user might find it useful to specify a specific directory to hold extracted pcap slices, e.g., if they're gathering them up as part of an investigation. The changes in #3049 made me realize how easy it would be to add this as a **Setting**, so that's what I've done here.
The attached video shows the feature working as intended using the branch from this PR at commit 651e403. As a baseline I show the default app behavior of extracting to `$TMPDIR`. Then I apply the new setting and show the pcap going to the selected directory. Then I clear out the setting and show the pcaps going back to `$TMPDIR` again.
https://github.com/brimdata/zui/assets/5934157/ea524209-183a-4231-8a0b-0e772ad1cd96
Closes #1423
> Add Setting for folder to store extracted pcap slices

- apps/zui/CONTRIBUTING.md
The changes in #3050 make this part of the CONTRIBUTING doc out-of-date and in need of update.
I'm a little hand-wavy in terms of what I've written here since manual signing is surely still possible but I've never attempted it in this new world order since it would require purchasing the special FIPS/YubiKey hardware. Likewise I'm sure other signing services could be made to work just like we did with eSigner, but I have no clue if they're similar/easy/hard. Therefore I've chosen to effectively point at what we've done with eSigner as a reference, leave it up to the reader to make it work for their alternatives, and invite them to share what they learned since it might help others (or us if we need to switch approaches in the future).
Ultimately I'm guessing most community members aren't …
> Update CONTRIBUTING with new Windows code signing info

- packages/zui-player/package.json
- yarn.lock
In brainstorming ideas of how to address #3063, one idea @jameskerr thought of was to upgrade to the latest Playwright release. Alas, in my testing with this branch it didn't improve on the failure rate of the symptom reproduced using the looped test in #3063 (30 successes and 8 failures before I stopped it, to be precise). But I also confirmed that the e2e tests can all pass successfully using this newer version, so since that much checks out I figure it probably doesn't hurt to upgrade just in case it helps us avoid some other problem down the road or gives us access to a new feature we didn't know we wanted.
> Pin Playwright dependencies to 1.43.1

- apps/zui/src/electron/run-main/before-boot.ts
- packages/zui-player/helpers/test-app.ts
While starting to debug #3063, I tried adding some `console.log()` debug statements to `packages/zed-node/src/lake.ts`, but the messages weren't visible in the shell window from which I ran `yarn e2e` nor in the `packages/zui-player/run/playwright-itest/Pool Loads (succeeses)/1/logs/main.log`. @jameskerr hacked at this with me a bit over Zoom and came up with these two improvements that make the messages show up in both locations. I'll put comments inline that explain which does what.
> Make console logs more accessible during Playwright e2e test runs

- apps/zui/src/core/renderer.ts
While on a Zoom showing @jameskerr some of my #3063 debug, he spotted that the change here should be in the code and was missing. We'd briefly hoped that this might address the #3063 symptom, but alas, a loop of the repro steps shown in that issue did not improve the failure rate (79 successful test runs and 14 failed before I stopped it, to be precise.) Nevertheless, since @jameskerr seemed confident the absence of this code was an oversight, I'm proposing the change in hopes it'll help us avoid some other problem in the future.
> Add a "close" at beforeunload

- packages/zed-wasm/package.json
- packages/zui-player/package.json
- yarn.lock
This fixes a problem that I've determined via binary search showed up at commit 4b851d8 that's associated with the changes in #2972.
Starting at that commit, when locally running `yarn test`, I'm finding it only gets this far and then hangs:
```
$ yarn test
✔  nx run zui-test-data:test (2s)
✔  nx run sample-data:test (2s)
✔  nx run zed-js:test (6s)
✔  nx run zed-node:test (10s)
✔  nx run insiders:test (3s)
✔  nx run zui:test (34s)
——————————————————————————————————————————————————————————————————————————————
>  NX   Running target test for 7 projects
→    Executing 1/1 remaining tasks...
⠹    nx run zed-wasm:test
✔    6/6 succeeded [0 read from cache]
```
At that point a tab opens up on my browser to http://localhost:9323/ that looks like this:
If I click the top error it expands to:
``` …
```
> Pin Playwright dependencies to 1.44.0

- apps/zui/package.json
- yarn.lock
https://github.com/brimdata/brimcap/pull/342 brought the latest Zeek artifact into Brimcap. Here I'm pointing Zui at that latest Brimcap so we can get some early testing of the new Zeek in Zui Insiders.
> Point at Brimcap 65795e3 to get latest Zeek

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
While #3062 addressed one of our recent failures in Zui CI due to a Zed change, [this recent Actions run](https://github.com/brimdata/zui/actions/runs/9086663026) shows that the very next Zed change at commit `ce9626e` was ready to cause a CI failure next. Assuming it's no surprise that the changes in https://github.com/brimdata/zed/pull/5118 would cause a change in the VNG file size, this PR adjusts the test to expect the new size.
```
$ zq -version
Version: v1.15.0-16-g183e432f
$ zq -f vng 'sort ts, _path' ./apps/zui/src/test/shared/data/sample.zeektsv | wc -c
7983
$ zq -version
Version: v1.15.0-17-gce9626eb
$ zq -f vng 'sort ts, _path' ./apps/zui/src/test/shared/data/sample.zeektsv | wc -c
7972
```
> Adjust expected VNG size in export test

- apps/zui/src/views/results-pane/errors/missing-pool-error.tsx
While #3078 fixed the first test breakage that appeared from recent advanced in the Zed dependency, it turns out the e2e test failure shown in [this run](https://github.com/brimdata/zui/actions/runs/9340425556) was waiting in line behind that one. The root cause is what's captured in #3079. While the details in #3079 advocate fixing a wider user-facing issue, here I've made the smaller adjustment necessary for the test to start passing again such as shown in [this run](https://github.com/brimdata/zui/actions/runs/9340505035).
> Fix e2e test for query when no pool specified

- apps/zui/src/css/_utilities.scss
- apps/zui/src/views/update-window/index.tsx
The buttons need to be stacked horizontally on one row.
fixes #3074
> Update Page Buttons

- .github/actions/build-zui/action.yml
- .github/actions/setup-zui/action.yml
- .github/actions/upload-build-artifacts/action.yml
- .github/workflows/advance-zed.yml
- .github/workflows/build-insiders.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/markdown-link-check.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
Node 16 actions are deprecated so upgrade to the Node 20 versions.
> Upgrade Node 16 actions in .github/workflows

- apps/zui/src/js/state/QueryInfo/selectors.ts
- apps/zui/src/models/browser-tab.ts
- apps/zui/src/views/histogram-pane/index.tsx
- apps/zui/src/views/histogram-pane/run-query.ts
- apps/zui/src/views/results-pane/errors/missing-pool-error.tsx
- apps/zui/src/views/session-page/handler.ts
fixes #3081 by not showing the histogram if there is a parse error
- Handle Error Case Differently
- Handle missing properties in query info
- Do not show the histogram if there is a parse error
- Loosen missing pool error detection
Here are the screenshots of the various "pool missing" stats. I also improved the error message of the histogram when the pool has no data in it.
> Parse Error UI Improvement

- apps/zui/package.json
- yarn.lock
Fixes #3089, which has all the background.
Here I'm just advancing the Electron dependency to `30.0.5` so we can have the benefit of the fix to https://github.com/electron/electron/issues/41839. I see there's an Electron `31.0.0` release also available, but since jumping to a major release is how we bumped into this bug in the first place, and I hope to put out a Zui release very soon and hence am nervous about hitting new bugs, I'm going the conservative route of jumping only as far as we need to get things working again.
Here's the proof of the fix being effective when I'm maximizing the window while running this branch at commit cbccd1b.
https://github.com/brimdata/zui/assets/5934157/08aff1c0-e023-49c4-9332-f6f6c687a2b9
> Advance to Electron 30.0.5 to get fix for electron#41839

- packages/zed-node/src/lake.ts
Fixes #3056, which has lots of background.
Now that the changes in #3069 have brought us to the the "use Electron's `net.fetch()`" state foretold in https://github.com/brimdata/zui/issues/3056#issuecomment-2086492607, here I'm restoring the prior behavior where the Zed service launched by Zui listens only on `localhost:9867` and therefore will no longer be open to connections from remote hosts.
```
$ ps auxww | grep -i zed
phil             52388   0.0  0.1 35563004  21380 s000  S+    6:17PM   0:00.05 /Users/phil/work/zui/apps/zui/zdeps/zed serve -l localhost:9867 -lake /Users/phil/work/zui/apps/zui/run/lake -manage=5m -log.level=info -log.filemode=rotate -log.path /Users/phil/work/zui/apps/zui/run/logs/zlake.log --cors.origin=* -brimfd=3
```
At some point after this merges, I'll introduce …
> Zed lake service should listen only on localhost by default

- apps/insiders/src/insiders-packager.ts
- apps/zui/package.json
- apps/zui/src/domain/updates/linux-updater.ts
- apps/zui/src/domain/updates/mac-win-updater.ts
- yarn.lock
Fixes #3082, which has detailed background on what's being fixed here and what else we expect to gain by moving to a newer `electron-updater`.
Starting from the code on this branch, I've done an exhaustive set of successful upgrade tests in personal fork repos of Zui and Zui Insiders on both macOS and Ubuntu (`.deb`). If this PR should get approved, after having updated the branch with any suggestions from reviewers, I'll catch it up with `main` and repeat the tests one last time including both Windows and Rocky Linux (`.rpm`) as well for completeness. I happened to skip those on the first pass since in the past I've found update behavior on Windows closely tracks what we see on macOS and likewise between the different Linux installers, so I figured I'd save a little time on the first …
> New electron-updater

- apps/zui/src/components/zed-editor-handler.ts
- apps/zui/src/components/zed-editor.tsx
- apps/zui/src/domain/session/handlers/navigation.ts
- apps/zui/src/domain/session/messages.ts
- apps/zui/src/electron/windows/search/app-menu.ts
- apps/zui/src/js/state/Histogram/reducer.ts
- apps/zui/src/js/state/Histogram/selectors.ts
- apps/zui/src/views/histogram-pane/index.tsx
- apps/zui/src/views/histogram-pane/run-query.ts
- apps/zui/src/views/session-page/editor.tsx
Hello! 
These changes will improve a few things.
1. If there is no pool name present in the query, this histogram will not render.
2. If you press Cmd+L (on macOS) or Ctrl+L (on Linux/Windows), the editor will receive focus.
3. If you switch tabs to a query session, the editor will receive focus automatically.
fixes #3093
> Only Render Histogram if you Can

- apps/zui/src/test/unit/setup/after-env.ts
Since the merge of #3084, I've noticed that in the "Zui CI" Actions workflow on the Ubuntu runner there's warnings in the `yarn test` step, such as those in [this recent run](https://github.com/brimdata/zui/actions/runs/9523130204):
```
PASS apps/zui/src/electron/start.test.ts
● Console
console.warn
Unable to detect 'package-type' for autoUpdater (beta rpm/deb support). If you'd like to expand support, please consider contributing to electron-builder The "path" argument must be of type string. Received undefined
7 | import pkg from "src/electron/pkg"
8 |
>  9 | autoUpdater.autoDownload = false
|            ^
10 | autoUpdater.autoInstallOnAppQuit = false
11 | autoUpdater.forceDevUpdateConfig = true
12 |
at doLoadAutoUpdater (../../node_modules/electron-updater/src/main.ts:52:15)
at …
```
> Set process.resourcesPath to quiet electron-updater during Linux tests

- apps/zui/src/js/zed-script/toZedScript.ts
Fixes #3098, which has more background.
The video below shows the change having the intended benefit on the original repro shown in #3098, and also with this simpler input file `foo.ndjson`:
```
{"_path": "http", "foo": "bar"}
{"_path": 1, "foo": "baz"}
{"_path": true, "foo": "bonk"}
```
https://github.com/brimdata/zui/assets/5934157/651cffc8-13e4-48ed-9582-c0d16e1ca24f
> Handle unions in toZedScript

- apps/zui/src/views/detail-pane/Fields.tsx
Since my approach in #3099 passed muster, that made me recall another open, union-centric issue #2938. Sure enough, as shown in the attached video, it seems a similar small change allows these union values to start being output where they weren't before.
https://github.com/brimdata/zui/assets/5934157/9e6ea525-51d7-46b0-bf68-1e30a0a37f23
Fixes #2938
> Output union values in Detail panel/window

- apps/zui/docs/Installation.md
With the Apple silicon builds for macOS coming in the next GA Zui release, I wanted to make sure this is explicitly called out in the install & update docs.
If approved, I intend to hold off on merging this until right before tagging the next GA Zui release.
The broken link flagged by CI is expected since I'm making a forward-looking reference to the `v1.8.0` release page that doesn't exist yet on GitHub.
> Mention Apple silicon installers and updates in docs

- apps/zui/src/css/_zed-table.scss
The padding added in the blamed PR caused the icons to be pushed off the buttons.]
Fixes #3108
> Show Table Header Menu Icons

- apps/zui/CHANGELOG.md
- apps/zui/package.json
- yarn.lock
https://github.com/brimdata/zui/compare/v1.7.0...b5987c1
The link checker failure in CI is expected because there's a forward-looking link in one of the docs to the `v1.8.0` release that I plan to tag once this PR gets approved.
> Update zed to v1.16.0, Brimcap to v1.8.0, and prep Zui v1.8.0

- apps/zui/src/core/invoke.ts
- apps/zui/src/css/global/_forms.scss
- apps/zui/src/domain/results/handlers/export.ts
- apps/zui/src/domain/results/operations.ts
- packages/zed-js/src/client/base-client.ts
- packages/zed-js/src/query/result-stream.ts
- packages/zui-player/helpers/test-app.ts
- packages/zui-player/tests/export.spec.ts
A toast error will now appear if there was a problem with the export.
Fixes #2751
> Surface Export Errors

- apps/zui/src/components/format.ts
- apps/zui/src/views/detail-pane/Fields.tsx
The changes in #3103 made it possible to smuggle a `null` union value into the Detail output formatter that was not prepared to handle them. After walking the code with @jameskerr, his suggestion was to back out the change from #3103 and instead add code in the Detail output formatter to handle unions in a way that's tolerant of `null` values. The attached video shows the fix working as intended with this PR's branch at commit 7807deb.
https://github.com/brimdata/zui/assets/5934157/a3353339-552c-4036-aa7d-f54843624667
As it turns out, @jameskerr already had work underway to sunset this particular code in the Detail view in favor of what we do with Inspector, and he's already confirmed that new code is immune to this problem. However, since we took the time to fully understand what's wrong …
> Handle zed.Union types in format.ts

- apps/zui/src/ppl/detail/models/ZeekEvent.ts
- apps/zui/src/ppl/detail/util/formatDur.test.ts
- apps/zui/src/ppl/detail/util/formatDur.ts
Fixes #3101 
With this fix:
If the duration is less than 1 second, it will display "xxxmilliseconds"
If it is less than 1 millisecond, it will display "less than one millisecond"
> Tiny Duration Fix

- apps/zui/src/plugins/brimcap/packets/download.ts
Per #1379, we've had problems on some platforms when a user clicks **Download Packets** and there's no application installed to open the extracted slice, e.g., Wireshark. Though we've merged some changes over time that have helped us improve in this area, this change covers us for Linux where the problem is still significant.
Fixes #1379
As of the most recent update in https://github.com/brimdata/zui/issues/1379#issuecomment-2187902520, Zui actually gets decent help here from the OS on both macOS and Windows since in those cases the OS pops up a notification about the lack of a helper app for pcaps. However, on Linux the user would still see just the **Packets extracted. Opening...** message from Zui, no launched pcap app, and no other guidance, so there was still room for improvement …
> Show an error message when pcap slices can't be opened

- apps/zui/src/domain/results/handlers/export.ts
- apps/zui/src/views/format-select/options.ts
- packages/zed-js/src/client/types.ts
- packages/zed-js/src/client/utils.ts
- packages/zui-player/helpers/test-app.ts
- packages/zui-player/tests/export.spec.ts
I've been holding off on adding Parquet as an Export format in Zui until #2751 was fixed, since there's so many Parquet limitations that can prevent the export from succeeding (e.g., lack of support for multiple types, lack of duration support, poor union support, etc.) But now that #2751 has been fixed and users will see the errors when exports fail, here I'm adding support for Parquet as an Export format.
Due to those same Parquet limitations, I could not just extend the existing loop-through-all-formats approach in the existing Export e2e test because an attempted export of that same test data file would fail. I saw a few ways this could be addressed:
1. I could rework the existing test to use a different, Parquet-eligible test data file for export in all formats and change all the …
> Parquet export

- apps/zui/package.json
- apps/zui/src/views/right-pane/index.tsx
- yarn.lock
The change in this branch ensures that when the right panel is closed its contents are unloaded.
Fixes #3128
I traced the root cause of the failures described in #3128 to these two lines, which are in the `table show details` test.
https://github.com/brimdata/zui/blob/a32bb549ecba530a190bdd7f73ba3246337572dd/packages/zui-player/tests/right-click-menus.spec.ts#L87-L88
At that spot in the test, it's intending to right-click on the `conn` tile in the query results with intent to select the **Show In Detail Pane** option from the drop-down menu. However, the changes in #3127 caused a problem with this because, now that we have Inspector-style results in the right panel, that made a `conn` gridcell appear in the right panel that wasn't there previously (specifically, the one brought up in the …
> Ensure right panel contents are unloaded when closed

- apps/zui/package.json
- yarn.lock
https://github.com/brimdata/brimcap/pull/353 brought the Zeek v7.0.0 artifact into Brimcap. Here I'm pointing Zui at that latest Brimcap so we can get some early testing of the new Zeek in Zui Insiders.
> Point at Brimcap 0c3a564 to get Zeek v7.0.0

- apps/zui/src/components/format.ts
- apps/zui/src/electron/run-main/run-configurations.ts
- apps/zui/src/views/detail-pane/handler.ts
- apps/zui/src/views/export-modal/index.tsx
- apps/zui/src/views/results-pane/index.tsx
- apps/zui/src/views/results-pane/inspector.tsx
- apps/zui/src/views/results-pane/table.tsx
- apps/zui/src/views/settings-modal/input.tsx
- apps/zui/src/zui-kit/react/table-view.tsx
- apps/zui/src/zui-kit/react/types.ts
- packages/zed-js/jest.config.ts
- packages/zed-js/package.json
- packages/zed-js/src/query/result-stream.ts
- packages/zed-js/src/values/primitive.ts
- packages/zed-js/src/values/record.ts
- packages/zed-js/src/values/time.test.ts
- packages/zed-js/src/values/time.ts
- packages/zed-js/src/values/types.ts
- packages/zed-js/tsconfig.json
- yarn.lock
- Add timezone and format support to Zui
- Results view works
- Time zone and format supported again
Fixes #1057
> Timezone Support

- apps/zui/src/views/results-pane/inspector.tsx
- apps/zui/src/zui-kit/core/list-view/list-view-api.ts
- apps/zui/src/zui-kit/core/list-view/types.ts
- apps/zui/src/zui-kit/react/list-view.tsx
Fixes #2742
The previous version of the code was relying on the rendered visible index, which didn't get updated fast enough. So now the code relies on the scrollTop and the height to determine if we are near the bottom of the scrollable area.
> Use scrolltop and height to determine if we should load more

- apps/zui/src/views/preview-load-modal/shaper.module.css
- apps/zui/src/views/preview-load-modal/sidebar.module.css
Previously, it was not possible to drag zui when the preview and load modal was open. This fixes that.
Fix Demo
https://github.com/user-attachments/assets/ae8d0381-ab05-4052-84cf-b3c2d325670a
> Make preview and load draggable

- apps/zui/src/core/view-handler.ts
- apps/zui/src/views/new-pool-modal/controller.ts
Trying to create a pool that already exists will now display the error instead of crashing with a runtime error.
https://github.com/user-attachments/assets/ef1bc6d6-c5c5-41b8-b334-e4895ecc75b0
> Handle Pool Error

- apps/zui/src/js/flows/viewLogDetail.ts
- apps/zui/src/js/state/LogDetails/actions.ts
- apps/zui/src/plugins/brimcap/zeek/correlations.ts
- apps/zui/src/views/correlations-pane/index.tsx
- apps/zui/src/views/results-pane/context.tsx
- apps/zui/src/views/results-pane/index.tsx
- apps/zui/src/views/results-pane/inspector.tsx
- apps/zui/src/views/results-pane/table-inspector.tsx
- apps/zui/src/zui-kit/table/table-view.tsx
- packages/zui-player/helpers/test-app.ts
- packages/zui-player/tests/copy-paste.spec.ts
- packages/zui-player/tests/pool-load-success.spec.ts
Steve pointed out the confusion that comes when the app wraps a non-record in a record to display it in a table format. Now we just display in the inspector view. 
The meaning of the "table view" button is now "table view preferred when possible". 
**Before**
**After**
> Don't Wrap Values in Records

- apps/zui/src/views/results-pane/table-inspector.tsx
When results contain multiple shapes, I'm proposing changing the wording of the guidance in the default Table view to:
> N Shapes — Filter or `fuse` to view results as one shape.
This is one that hit me when I was testing the changes in #3145.
Right now when the results contain multiple shapes, the default Table view shows the guidance:
> N Shapes — Filter to one shape or `fuse` results to view as a table.
This guidance is accurate if the data happens to be records, which it often is. However (and maybe this is spitting hairs), if the data contains one or more primitive values, such as this ZSON test data:
```
1
"hello"
3.14
```
the guidance becomes inaccurate because even if the user _does_ apply `fuse`, the data shown is still not in a "table" in the traditional sense because there's no …
> Change guidance that mentions fuse when there's multiple shapes

- apps/zui/package.json
- packages/zui-player/tests/export.spec.ts
- yarn.lock
The Zui CI started failing when https://github.com/brimdata/zed/pull/5320 merged because the exported VNG file size had increased by a byte. From the Zed PR it looks like this is all quite expected so this adjusts the test to run successfully again.
> Increase expected VNG file size due to zed#5320 change

- .github/workflows/build-insiders.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
- apps/zui/docs/support/Supported-Platforms.md
Our GitHub Actions Workflows that previously used the Intel-based `macos-12` runners will now use the Intel-based `macos-13` runners.
GitHub notified:
> GitHub Actions: The macOS 12 runner image will be removed by 12/3/2024
The full text of the notification email:
I've tended toward always using the oldest available runners for each target platform since we expect at least _some_ users are running older OS versions (conservative corporate environments, etc.) and this gives us a better chance of knowing if something unexpected has caused us to lose the ability to run on the older OSes such that we'd need to update our [Supported Platforms](https://zui.brimdata.io/docs/support/Supported-Platforms) statement. Since GitHub has given us this early notice, I figure we might as well make the …
> Have Actions Workflows use macos-13 rather than macos-12

- apps/zui/src/config/links.ts
The zed->super transition is well underway on the super side of things, so the super docs tagged "Next" are starting to have some totally new paths. Zui is holding still in the interim. Because of link checks, this has started to cause failures in Zui's CI like [this one](https://github.com/brimdata/zui/actions/runs/11619491225). To avoid this while still being able to put out Zui Insiders releases with bug fixes, here I'm proposing that we just point Zui's docs links at the last GA release for now. When there's a mass zed->super transition when Zui turns into Super Desktop, we can put this back.
> Always point to last GA Zed docs for now

- apps/zui/src/models/snapshot.ts
Fixes #3161 
The bug was caused by the nextjs build step obfuscating all the names of the symbols in the code. Some code introspects itself to get the name of its class, then lowercases and pluralizes it to become the key in the state object.
The snapshots slice in dev mode looks like this.
```
{
snapshots: {...}
}
```
That key is derived from the class called `Snapshot`.
But when we build for production, that class becomes the single letter `p`.
So on zui insiders, the state object looks like.
```
{
ps: {...}
}
```
There is other code that relies on there being a "snapshots" key in the state and that is where the error occurs.
This fix introduces a static, explicit name for the key, instead of the derived one. Looks like we will need to do this each time we introduce a new slice of state …
> Explicit Slice Names Required

- .github/workflows/advance-zed.yml
- .github/workflows/build-insiders.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/markdown-link-check.yml
- .github/workflows/notify-docs-update.yaml
- .github/workflows/notify-main-failure.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
In our Actions workflows, this moves us from using `ubuntu-20.04` to `ubuntu-22.04`.
Per https://github.com/actions/runner-images/issues/11101, `ubuntu-20.04` is set to be deprecated soon. This includes planned "brownouts" in March in which they'll intentionally cause failure of some jobs still using `ubuntu-20.04` to alert users of the change. The changes in this PR get ahead of that.
I've always been a fan of pointing at specific/old runner versions (as opposed to `-latest`) so that way we can have more confidence in a support statement that says we can run on platforms older than the very latest. However, this requires moving the pointers periodically. Thankfully they give us plenty of advance warning.
> In Actions workflows, move from ubuntu-20.04 to ubuntu-22.04

- apps/zui/src/zui-kit/core/list-view/list-view-api.ts
It's still slow on the deeply nested data, but it does not crash anymore!
Array.slice was not working for us. Changing to an array copy algorithm allowed the operation to succeed.
> Fix Deeply Nested Data Crash

- .github/workflows/advance-super.yml
Back in October, 2024 via https://github.com/brimdata/super/pull/5347 I disabled the auto-update of the Zed dependency in the Zui repo because changes in super were starting to happen that would break the app. We were focused on other things at the time so we didn't prioritize getting them back in sync and keeping them that way. Now that @jameskerr has recently done the work to start turning Zui into SuperDB Desktop and we've got the app working again with a recent super commit, it seems like it's time to get this auto-update workflow running again so the app will always have the benefit of the latest super changes and we'll know immediately when something breaks it.
While we're at it, here I've done some de-Zed-ing of the workflow in question. Once this is merged and it's prepared to …
> Change "advance-zed" workflow to "advance-super"

- .github/workflows/advance-super.yml
- packages/zui-player/ci.config.js
I've made the zui-player repo a "ESModule" instead of a "commonjs" module. So we need to use this module syntax when importing files.
> Convert to ESM

- .github/workflows/advance-super.yml
- packages/superdb-node-client/package.json
- yarn.lock
This change enables the automatic advancing of the Node client's `super` dependency via Actions workflow, just like we do for the app's `super` dependency.
https://github.com/brimdata/zui/pull/3187 illustrated how we'll sometimes need to advance the Node client's dependency, and so I ended up doing a one-shot advance of the dependency in that PR with intent to follow up and make it automatic in a separate PR, and that's what this PR is.
When I set out to make the change, I had some struggles. At first I tried to just repeat the same `yarn workspace ... add ...` approach that's already used for the app's dependency, but this caused some errors related to how superdb-node-client had `super` listed as both a `devDependency` and a `peerDependency`. The relevant docs online didn't 100% make …
> Advance Node client's super dependency automatically (regular dep)

- apps/superdb-desktop/package.json
- packages/superdb-node-client/package.json
- yarn.lock
It looks like in #3190 I made a mistake of not running `yarn` a final time and committing the resulting `yarn.lock`, since right now at tip-of-`main` if I run `yarn` it does indeed produce a diff to `yarn.lock`. A couple times now the automation has tried to automatically advance the pointer and that's causing a failure like the one shown below. I'm attempting to fix that in this PR via one more manual update get the super commit pointers in current & in sync and commit the resulting `yarn.lock`.
```
Post-resolution validation
➤ YN0000: │ @@ -11908,8 +11908,14 @@
➤ YN0000: │    checksum: 31ba7a62c889236b5b07f75b5c250d481158a1ca061b8f234fca0457bdbe48a20e5011c12c715343dc577e111463dc3d9e721b98015a445a2a88c35e0c9f0f91
➤ YN0000: │    languageName: node
➤ YN0000: │    linkType: hard
➤ YN0000: │ …
```
> Sync up the super dependency between the app and Node client

- .github/workflows/advance-super.yml
- .github/workflows/build-insiders.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/markdown-link-check.yml
- .github/workflows/notify-docs-update.yaml
- .github/workflows/notify-main-failure.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
Use `ubuntu-24.04` runners instead of `ubuntu-22.04` to work around an Actions problem.
It's normally my preference to stay pinned on older CI runners until there's a deprecation notice or some other compelling reason to jump to the newer. But for over a week our jobs have been failing intermittently due to the problem described in https://github.com/actions/runner-images/issues/11988. Their one change they thought might fix it has not panned out, and the ongoing problem doesn't seem to be getting treated with much urgency. I've already done the work to confirm that our jobs should run fine on the Ubuntu 24.04 runners and other folks who chimed into https://github.com/actions/runner-images/issues/11988 have said the same. I'm getting sick of the failures so I'm ready to just make the jump …
> Use ubuntu-24.04 runners to work around actions/runner-images#11988

- apps/superdb-desktop/CHANGELOG.md
- apps/superdb-desktop/docs/support/Filesystem-Paths.md
The removal of the Zed-era tags from the super repo caused some hyperlinks to start failing in the markdown link checker.
While I was in the CHANGELOG I also saw some links still pointing at this repo by its old "brim" name so I updated those to "zui".
> Update links to Zed releases

- .github/workflows/advance-super.yml
- .github/workflows/e2e.yml
These changes get the e2e tests running again on Ubuntu 24.04. I've got some uncertainty about if it's the best possible "fix", but it may be good enough.
Closes #3194
#3194 has the background on the symptom, and [this successful job](https://github.com/brimdata/zui/actions/runs/14584692958) shows the `sysctl` workaround is effective in getting the e2e tests running again.
After initially trying _just_ the `sysctl` setting change it still failed on the Action Runner, and further debug showed a `yarn start` still failing with this message:
```
$ yarn start
> nx run superdb-desktop:start
‣ Compiling...
‣ Launching...
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): dist/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node …
```
> Make sysctl setting and install libsecret-1-0 before starting e2e tests on Linux

- .github/workflows/build-insiders.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
GitHub sent out their notice that the Windows Server 2019 runner image will be fully unsupported by June 30, 2025 and so they're about to start doing scheduled brownouts of jobs that still use the 2019 runner to make people aware. To get ahead of this, here I modify the workflows to use the 2022 runner instead. I did a test run of the CI workflow on this branch and it ran fine.
> Use windows-2022 Actions runners since windows-2019 is going EOS

- apps/superdb-desktop/package.json
- packages/superdb-node-client/package.json
- packages/superdb-node-client/src/lake.ts
- yarn.lock
The app's SuperDB backend will now be launched with the `-db` flag instead of the `-lake` flag as it had been previously.
https://github.com/brimdata/super/pull/5966 changed the flag, and CI surfaced the problem because the app could no longer start the persistent storage to run tests.
I'm only attempting here to make the app functional again so CI will continue passing. That is, I'm not attempting to de-lake the entire UX or docs.
> Launch SuperDB backend with -db instead of -lake

- apps/superdb-desktop/package.json
- apps/superdb-desktop/src/js/state/LoadDataForm/reducer.ts
- packages/superdb-node-client/package.json
- yarn.lock
https://github.com/brimdata/super/pull/5989 enabled `/* */`-style multi-line comments and https://github.com/brimdata/super/pull/5990 removed the `//`style single-line comments altogether. The remaining use of `//` in this one spot in the app was causing CI to break, so, fixing that here.
> Stop using // for comments

- apps/superdb-desktop/package.json
- apps/superdb-desktop/src/test/shared/data/sample.sup
- packages/sample-data/data/sample.sup
- packages/superdb-node-client/package.json
- yarn.lock
This adapts to the changes in https://github.com/brimdata/super/pull/6000 so Zui tests will pass in CI again.
> Change SUP union syntax to use pipe(|) instead of comma separator

- apps/superdb-desktop/package.json
- packages/superdb-node-client/package.json
- packages/superdb-node-client/src/zq.test.ts
- yarn.lock
This adapts to the changes in https://github.com/brimdata/super/pull/6021 so the tests will succeed in CI again.
> Use "unnest" instead of "over"

- apps/superdb-desktop/package.json
- apps/superdb-desktop/src/domain/loads/query-loader.ts
- packages/superdb-node-client/package.json
- yarn.lock
This adapts to the changes in https://github.com/brimdata/super/pull/6059 so the Zui tests in CI will pass again.
> Adapt to changes in the SuperSQL load operator

- apps/superdb-desktop/package.json
- packages/app-player/tests/pool-load-success.spec.ts
- packages/superdb-node-client/package.json
- yarn.lock
The merge of the changes in https://github.com/brimdata/super/pull/6156 are correlated with the e2e test `pool-load-success.spec.ts` starting to consistently fail. It seems likely that the SuperDB change aggravated an existing timing problem with the test, so here I make the test more deterministic. I'm not in love with the fix, but the overall Zui test suite is in need of improvements and I'm not in a position to fix all of it right now.
An example failure can be seen in [this Actions run](https://github.com/brimdata/zui/actions/runs/17272369886). Here's a local repro of the same failure by just running that specific test:
```
$ yarn e2e pool-load-success.spec.ts
> nx run app-player:test pool-load-success.spec.ts
Running 2 tests using 1 worker
✓  1 pool-load-success.spec.ts:17:3 › Pool …
```
> Address timing issue in e2e pool-load-success and advance super dependency
