brimdata/zui

scripts/download-zdeps/index.js

To pull in:
https://github.com/brimsec/zeek/pull/7

bump zeek to v3.0.2-brim2

---

package.json
src/js/electron/menu/__snapshots__/appMenu.test.js.snap
src/js/electron/menu/appMenu.js
src/js/initializers/initShortcuts.js

Added the following menu items:
* File => Close Tab
* File => Close Window
* File => Exit (windows only)

PROD-1691 Add ability to quit app from Menu bar

---

scripts/download-zdeps/index.js

This includes the new launcher utility from:
https://github.com/brimsec/zeek/pull/9

windows: use zeek-20200403 artifact

---

.github/workflows/ci.yml
itest/lib/app.js

Use deb package installer in integration tests

---

src/js/components/ZQModal.js

Part of https://github.com/brimsec/zq/pull/544. 
I'll wait to merge this until the corresponding zq change is merged in https://github.com/brimsec/zq/pull/630

zq modal: change all.bzng to all.zng

---

itest/lib/app.js
itest/tests/query.test.js

harden clicks

---

.github/workflows/ci.yml
scripts/lib/common.bash

test fix: allow for possibility of dimg mounted volume to disappear

---

src/js/components/SavedSpacesList.js

fix delete text

---

src/js/components/TabWelcome.js

fixes #693 
depends on #716 merging
@alfred-landrum is that link the best source for zng documentation?

add zng file type

---

scripts/release/install.js

Fixes #724.
Test release at https://github.com/brimsec/brim/releases/tag/v0.9.0-dev
Release checks
- https://github.com/brimsec/brim/actions/runs/93379314
- https://github.com/brimsec/brim/actions/runs/93379306
- https://github.com/brimsec/brim/actions/runs/93379318

fix: move installer requires only to where needed

---

src/js/flows/ingestFiles.js

If incoming LogPostStatus messages have the "log_total_bytes" field, use it & and the log_read_bytes field to update the progress bar. The log_total_bytes field is added by https://github.com/brimsec/zq/pull/708 .
This is the UI side of https://github.com/brimsec/brim/issues/567 .

support logPostStatus progress reporting

---

src/css/_curl-modal.scss
src/css/_toolbar-button.scss
src/js/components/IngestWarningsModal.js
src/js/components/ModalBox/Buttons.js
src/js/components/ZQModal.test.js

Add ability to clear the warning messages

---

package-lock.json
package.json
src/js/brim/ast.js

Companion to PR https://github.com/brimsec/zq/pull/699

Update for GroupbyProc ast format change

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.8.0...d5b4478

Prep for v0.9.0

---

itest/lib/app.js
itest/tests/__snapshots__/contextMenu.test.js.snap
itest/tests/contextMenu.test.js
src/js/components/HTMLContextMenu.js
src/js/test/integration.js

@jameskerr Integration test for your experiment....

Right click experiment itest

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.9.0...55c826f

Prep for v0.9.1

---

package-lock.json
package.json
src/js/components/PacketsButton.js
src/js/electron/menu/detailFieldContextMenu.js
src/js/electron/menu/searchFieldContextMenu.js
src/js/flows/ingestFiles.js
src/js/flows/ingestFiles.test.js
src/js/flows/rightclick/cellMenu.test.js
src/js/flows/submitSearch.test.js
src/js/initializers/initPersistance.js
src/js/services/BoomClient/client/Packets.js
src/js/services/zealot/pcapsApi.js
src/js/services/zealot/test.js
src/js/services/zealot/types.js
src/js/state/Spaces/reducer.js
src/js/state/Spaces/test.js
src/js/state/Spaces/types.js
src/js/test/fixtures/index.js
src/js/test/mockZealot.js

Update client to reflect pcap api name change

---

package-lock.json
package.json

My last pr changed the package version to 0.9.0 when we are really
at 0.9.1. Fix this.

Add back current version to package.json

---

itest/lib/app.js

run CI without requiring installed releases

---

src/js/components/SpacePicker.js
src/js/flows/ingestFiles.js
src/js/flows/ingestFiles.test.js

Fixes two bugs I found in my testing of the 705-space-ids branch.

705 space ids review

---

package-lock.json
package.json
src/js/initializers/initPersistance.js

reset state and fix package lock

---

.github/workflows/advance-zq.yml

rewrite bare PR references as zq PR references

---

src/js/brim/form.js
src/js/brim/form.test.js
src/js/components/Preferences/usePreferencesForm.js

In the happy case when the file existed and was json, the form
check returned undefined instead of an array. This pr fixes that
and adds a better error message for the future.
Fixes #792

JSON Config Validation Bug

---

acknowledgments.txt

Added to the windows zeek artifact in https://github.com/brimsec/zeek/pull/29

Add acknowledgment for brimsec/zeek/src/windows/strptime.c

---

src/js/electron/tron/session.js

If appState does not exist, don't throw a crazy error in the main process logs about NOENT. 
```
{
constructor: 'Error',
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/Users/mikeb/git/brim/run/appState.json',
stack: "Error: ENOENT: no such file or directory, open '/Users/mikeb/git/brim/run/appState.json'"
}
```
fixes: #805

No error if appState.json does not exist

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.9.1...0a15799

Update zq to v0.14.0 and prep for v0.10.0

---

package-lock.json
package.json

I left out a step when starting to combine two steps in the release process.

Advance Brim version to v0.10.0

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.10.0...241fb98

Update zq to v0.15.0 and prep v0.11.0

---

itest/lib/appStep/api/reload.js

fix: retry browser window reload

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.11.0...be52684

Update zq to v0.16.0 and prep v0.12.0

---

src/css/_filter-tree.scss
src/css/_finding-card.scss
src/js/components/FilterTree.js
src/js/components/Investigation/FindingCard.js
src/js/components/hooks/usePopupMenu.js

fixes #885 
Some cleanup as suggested in the ticket

Polish history

---

src/css/_search-page.scss
src/css/_tab-bar.scss
src/css/_tab-welcome.scss
src/css/_tab.scss
src/js/components/LeftPane.js
src/js/components/common/EmptySection.js
src/js/state/Layout/reducer.js

I just wanted to make a few css color updates for the tabs and the welcome backgrounds. I also make the sidebar sections overflow: auto so that scrollbars do not appear if they are not needed.
And the welcome screen looks like this:

Color fixes and default pane size

---

src/js/components/IngestRefresh.js
src/js/components/hooks/useThrottle.js

fixes #904 
...Or is another attempt at it. Highly encourage folks to check this out and follow the repro steps in the ticket. So far it has been working for me!

excess refresh fix part 2

---

CONTRIBUTING.md
docs/Code-Base-Walkthrough.md

The video is up from today's webinar, so, linking to it from a couple places so future generations may benefit.
While I was at it, I added a table of contents and a pointer to Slack.

Link to "developer overview" YouTube video

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.12.0...5d04cdf

Update zq to v0.17.0 and prep v0.13.0

---

src/js/state/migrations/202007091803_forceLeftSidebarDefaultOpen.js
src/js/state/migrations/202007091803_forceLeftSidebarDefaultOpen.test.js

add migration to force leftSidebar defaults

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.13.0...0670fac

Update zq to v0.17.0 and prep v0.13.1

---

CONTRIBUTING.md

@alfred-landrum: We'd talked about putting text like this in the "contributing" guide to lessen the risk that someone spends their time on a PR that we'd be unlikely to accept. Rather than repeat all the "Why?" I found what I thought was a decent article that covered the topic, then linked to it. Let me know what you think. Once we settle on an approach I can give the same treatment to the "contributing" doc in the `zq` repo.

Ask for open issues before PRs

---

src/js/components/LogRow.js
src/js/components/SearchResults/ResultsTable.js
src/js/components/hooks/useDoubleClick.js

fixes #966 
Track previously selected index, and compare on double click

Fix double click bug

---

src/js/components/LoadFilesInput.js
src/js/components/TabImport.js
src/js/components/common/Link.js
src/js/lib/cssVar.js

A quick clean up of some code for the import view. Also make the link's "tabbable".

Tabbable Links on Import Page

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.14.0...63aaecf

Update zq to v0.19.0 and prep v0.15.0

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.15.0...93fec24

Update zq to v0.19.1 and prep v0.15.1

---

src/js/components/Investigation/FindingCard.js

Thought this issue was more complex. But turned out to be a tiny change. @jameskerr can you confirm this is working as expected?
Fixes #928.

Fix history investigation interaction

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.15.1...4e23510

Update zq to v0.16.0 and prep v0.20.0

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.16.0...107f35c

Update zq to v0.21.0 and prep v0.17.0

---

src/js/components/ModalBox/Buttons.tsx
src/js/components/ModalBox/ModalBox.tsx
src/js/components/ModalBox/types.ts
src/js/components/NewConnectionModal.tsx
src/js/components/TabSearch.tsx

fixes #1080 
I added some more context in ticket ^^

fix modal close

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.17.0...0b26536

Update zq to v0.22.0 and prep v0.18.0

---

.github/workflows/markdown-link-check.yml

@nwt had me make some adjustments to the Workflow name & filename when I opened https://github.com/brimsec/zq/pull/1510 for similar functionality on the zq side, so here I'm making the Brim side look the same also.

Make link checker Action config look like zq's

---

src/js/electron/main.ts
src/js/electron/tron/window.ts
src/js/electron/tron/windowManager.ts
src/js/electron/userTasks.ts
src/js/electron/window/SearchWindow.ts
src/js/electron/window/dimens.test.ts
src/js/electron/window/dimens.ts
src/js/test/setup.ts

Fixes #1041 
The ticket requests a new task be added to the “[Jump List](https://www.electronjs.org/docs/tutorial/windows-taskbar)” on a Windows OS. 
Clicking these tasks re-executes the brim exe file with specified arguments. By default this creates more than one instance of the Brim app, meaning there are multiple main processes and multiple “global” stores. I didn’t know this, since I develop on a Mac which maintains a single instance for us. However, if you open a new terminal and manually run the brim executable again, it will indeed start a new instance, even on Mac.
Electron provides the “[instanceLock](https://www.electronjs.org/docs/api/app#apprequestsingleinstancelock)” api to help with this. Only one instance of the app can have the lock, so any other instances will immediately …

Keep Brim on Screen

---

package-lock.json
package.json

Maybe upgrading WebDriver and electron will help with our intermittent test failures. 🤞

Update electron and webdriverio

---

src/js/flows/initCurrentTab.ts

fixes #1161 
needed to update status globally

update status globally

---

src/js/components/ConnectionModals/ConnectionForm.tsx
src/js/components/ConnectionModals/EditConnectionModal.tsx
src/js/components/ConnectionModals/NewConnectionModal.tsx
src/js/components/ConnectionModals/ViewConnectionModal.tsx
src/js/components/ModalDialog/ModalDialog.tsx
src/js/style-theme/index.ts

Styles tweeks to the edit, show, and new connection modals. They look like this now after these tweeks:

1022 Style Tweeks

---

src/js/components/ConnectionModals/EditConnectionModal.tsx
src/js/components/ConnectionModals/ViewConnectionModal.tsx

Keep edit on same modal as show

---

CHANGELOG.md
docs/Troubleshooting.md

Updating links due to https://github.com/brimsec/zq/pull/1546

update links to zqd in zq repo

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.18.0...216a702

Update zq to v0.23.0 and prep v0.19.0

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.18.0...43101c7
As Daft Punk might say in this situation... 🎶  one more time! 🎶

Update zq to v0.23.0 and prep v0.19.0 (one more time!)

---

zealot/src/zng/types/record.test.ts
zealot/src/zng/types/record.ts

Handle unset records in zealot

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.19.0...c9f3615

Prep v0.20.0

---

docs/Home.md
docs/Installation.md
docs/_Sidebar.md

While it's under review, you can see the rendered version of this article as it will look in the Brim wiki at my scratch personal repo: https://github.com/philrz/scratchwiki/wiki/Installation
In a comment from one of @orochford's recent Medium articles, a user asked to be pointed at an article for how to install Brim. We know the install procedure is super simple, but users who have never heard of us before have no way of knowing that, so I'm putting up this article we can link to as necessary.
The only basic installation problem that's ever come up in the community was with one Windows user I spoke with who mistakenly thought they had to run the `Brim-Setup.exe` every single time they wanted to launch Brim. I think this was made worse by the fact that the Windows installer gives so …

Installation article

---

.github/workflows/ci.yml
itest/tests/__snapshots__/ingest.test.ts.snap
itest/tests/ingest.test.ts

It looks like the PowerTools repo was renamed to lowercase "powertools".

Fix Centos CI "PowerTools repo not found"

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.20.0...5fa7df6

Update zq to v0.25.0 and prep v0.21.0

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.21.0...841244c

Update zq to v0.26.0 and prep v0.21.1

---

src/js/components/ExportModal.tsx

now that https://github.com/brimsec/zq/issues/1271 closed, we don't need this!

remove csv guard

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.21.1...b3fffd4

Update zq to v0.27.0 and prep v0.22.0

---

package-lock.json
package.json
ppl/zqd/zqd.ts

Accomodating the changes from brimsec/zq#1972

Adjust zqd logging config

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.22.0...240d441

Update zq to v0.28.0 and prep v0.23.0

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.22.0...4da1791

Update zq to v0.28.0 and prep v0.23.0 (redux)

---

ppl/summary/flows/initial-state.ts
src/js/state/Boards/index.ts
src/js/state/Boards/test.ts
src/js/state/Tiles/index.ts
src/js/state/Tiles/test.ts
src/js/state/globalReducer.ts
src/js/state/rootReducer.ts
src/js/state/types.ts

Similar to the previous PR. Also based of the Previous one.

Tiles State to go along with the Boards

---

CHANGELOG.md

I found and fixed a couple mistakes in the changelog as I was pasting it onto the GitHub Releases page and announcing on public Slack, so I'm circling back and correcting them here as well. As long as I'm circling back, I've also included the notice about the custom entires in the Query Library, for completeness.

Fixes to the v0.23.0 changelog

---

package-lock.json
package.json
ppl/summary/bar-chart.tsx
ppl/summary/flows/update-tile-layout.ts
ppl/summary/grid.tsx
ppl/summary/horizontal-bar-chart.tsx
ppl/summary/number.tsx
ppl/summary/summary.tsx
ppl/summary/table.tsx
ppl/summary/tile.tsx
src/css/main.scss
src/js/components/TabSearch.tsx
src/js/flows/submitSearch/mod.ts
src/js/initializers/initStore.ts
src/js/state/Tiles/index.ts
src/js/state/Tiles/test.ts
src/js/style-theme/index.ts
src/js/test/initTestStore.ts

This builds off #1373 and #1374 
closes #1325 
This is the first prototype of the security summary.
It updates when the spaces changes or when the time span changes.
The layout of the tiles is saved to the global state and persisted.
There is much more that will need to be done before releasing this feature, but having this in master can at least get some early eyes on it and generate ideas/find bugs.

Security Summary Prototype

---

src/js/components/SearchBar/mod.tsx

disable target select for now

---

.github/workflows/markdown-link-check.yml

Details are the same as described in https://github.com/brimsec/zq/pull/2074.

Add scheduled link check in place of push: master

---

src/js/electron/menu/actions/detailActions.ts

fixes #1362 
This wasn't being accessed properly

fix getter to direct get

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimsec/brim/compare/v0.23.0...8f062fa

Update zq to v0.29.0 and prep v0.24.0

---

.github/workflows/advance-zq.yml
.github/workflows/ci.yml
.github/workflows/linux-release-candidate.yml
.github/workflows/macos-release-candidate.yml
.github/workflows/win-release-candidate.yml

This helps us avoid some CI flakiness.

Pin deno to 1.7.2

---

.github/workflows/advance-zq.yml
.github/workflows/ci.yml
.github/workflows/linux-release-candidate.yml
.github/workflows/macos-release-candidate.yml
.github/workflows/win-release-candidate.yml

Maybe this fixes the test failures?

Update actions/cache to v2

---

ppl/queries/initial.ts
src/js/state/migrations/202103011928_adjustWindowsNetworkingActivityQuery.test.ts
src/js/state/migrations/202103011928_adjustWindowsNetworkingActivityQuery.ts

update Windows Networking Activity query

---

.github/workflows/advance-zq.yml
.github/workflows/ci.yml
.github/workflows/linux-release-candidate.yml
.github/workflows/macos-release-candidate.yml
.github/workflows/win-release-candidate.yml

In keeping with brimsec/zq#2328.

update to Go 1.16

---

package-lock.json
package.json
src/js/brim/ast.ts
src/js/brim/program.ts
src/js/lib/Program.ts

I just merged the zq `uniform-ast` branch and this is passing tests and ready to go...

sync with zq uniform-ast

---

CHANGELOG.md
CONTRIBUTING.md
app/lakes/import.tsx
docs/Joining-Data.md
docs/Zeek-Customization.md
src/js/components/SearchBar/MenuAction.tsx
src/js/electron/menu/appMenu.ts

update links for brimdata/zed#2455

---

.github/workflows/advance-zed.yml
.github/workflows/ci.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
app/lakes/import.tsx
docs/Joining-Data.md
docs/Query-Library-Transfer.md
docs/Remote-zqd.md
docs/Troubleshooting.md
docs/Zeek-Customization.md
docs/Zeek-JSON-Import.md
itest/README.md
itest/lib/env.ts
itest/tests/zar.test.ts
package-lock.json
package.json
scripts/download-zdeps/index.js
src/js/components/SearchBar/MenuAction.tsx
src/js/electron/menu/appMenu.ts
zealot/parser.ts

This reflects the change from brimdata/zq to brimdata/zed in brimdata/zed#2460.

change brimdata/zq to brimdata/zed

---

itest/tests/lake.test.ts
package-lock.json
package.json
scripts/download-zdeps/index.js

The "zed lake" command replaces zar in brimdata/zed#2463.

change zar to zed lake

---

.github/workflows/ci.yml
.github/workflows/linux-release-candidate.yml
.github/workflows/macos-release-candidate.yml
.github/workflows/win-release-candidate.yml
electron-builder.json

I've been doing some hacking in a personal fork based on the branch from #1508 to see what it takes for the artifacts to build via Actions. With the changes in this branch I've at least gotten to the point where I'm reliably getting artifacts on all three platforms. I've got more testing to do, but I'd like to see about getting these changes merged to @mason-fish's branch so I can start over with a fresh fork for the next round to clear my head. :sweat\_smile:

electron-builder improvements from testing fork

---

zealot/enhancers/zngToZeek.ts

A quick fix for #1576
Fixes #1576

Check if 'of' is null

---

package-lock.json
package.json
scripts/download-zdeps/index.js

Brimcap includes the Brim builds of Suricata and Zeek.
Depends on brimdata/brimcap#47.
Closes #1574.

add brimcap to zdeps

---

app/lakes/new.tsx
src/js/flows/createPool.ts
test/api/ingest_test.ts
test/api/search_test.ts
zealot/api/pools.ts
zealot/types.ts

pools: Set default order to desc

---

src/js/zql/toZql.ts
zealot/zed/values/duration.test.ts
zealot/zed/values/duration.ts

Copied tests and code from the zed duration class: https://github.com/brimdata/zed/blob/e28c017a25624ec2754482efa6faf7f4b1d7f2cc/pkg/nano/duration_test.go

Copied duration code into app

---

src/js/electron/menu/__snapshots__/appMenu.test.ts.snap
src/js/electron/menu/appMenu.ts

Update wording in help menu

---

app/lakes/import.tsx
src/js/components/SearchHeaderChart.tsx
src/js/components/charts/MainHistogram/useMainHistogram.tsx

Import wording

---

package-lock.json
package.json

Looking to get the latest fixes all in one place so I can do the next round of end-to-end testing.

Advance Brimcap to c00eb28

---

plugins/brimcap/brimcap-plugin.ts

fixes #1595 
Runs on app load, and also on refresh. If we only wanted this to run on app load then I could add some api plumbing so that plugins can listen for a brim load event (i.e. `this.api.onAppLoaded()`) but this seemed simpler and better.

invoke suricata-updater on app load

---

app/core/utils/get-repo.test.ts
app/core/utils/get-repo.ts
app/core/utils/package-json.test.ts
app/core/utils/package-json.ts
app/ipc/paths.ts
app/release-notes/release-notes.tsx
app/release-notes/use-release-notes.ts

Whatever repo is listed in package.json will be used when fetching the release notes.

Use repo in the package.json for fetching release notes

---

src/js/components/common/Link.tsx

Allow for normal anchor links

---

package-lock.json
package.json
src/js/brim/interop.ts
src/js/brim/time.ts
src/js/flows/ingestFiles.test.ts
src/js/flows/ingestFiles.ts
src/js/flows/refreshPoolInfo.ts
src/js/flows/refreshPoolNames.ts
src/js/flows/workspace/buildAndAuthenticateWorkspace.test.ts
src/js/lib/is.ts
src/js/state/Pools/test.ts
test/api/ingest_test.ts
test/api/pools_test.ts
zealot/api/logs.ts
zealot/api/pools.ts
zealot/fetcher/contentType.ts
zealot/types.ts
zealot/zealot.ts
zealot/zed/values/int64.ts
zealot/zed/values/time.ts

Update client to reflect changes to the zed lake api reflected in
brimdata/zed#2741

Update zed lake endpoints

---

src/js/electron/tron/windowManager.ts

linux hidden window cleanup

---

src/js/electron/tron/windowManager.ts

fixes #1707 
...or attempts to! 😅 
I had actually suspected we needed this for Linux AND Windows in the first place but was under the impression Windows wasn't experiencing the same issue somehow. Turns out it was but in a sneakier way!

Windows shutdown fix

---

src/js/components/ModalBox/ModalContents.tsx
src/js/components/Preferences/DataDirInput.tsx
src/js/components/Preferences/Preferences.test.tsx
src/js/components/Preferences/Preferences.tsx
src/js/components/Preferences/TimeFormat.tsx
src/js/components/Preferences/Timezone.tsx
src/js/components/common/forms/FileInput.tsx
src/js/state/Prefs/reducer.ts
src/js/state/View/reducer.ts
test/unit/__mocks__/electron.ts
test/unit/helpers/setup-brim.ts

A component test to test the existing functionality of the preferences modal with plans to refactor and extend it.

Add preferences component test

---

zealot/zed/values/type.ts

Remove parens from type values

---

package-lock.json
package.json
plugins/brimcap/brimcap-cli.ts

depends on: brimdata/brimcap#148

brimcap: support config changes

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimdata/brim/compare/v0.25.0...a56cddf

Update zed to v0.31.0 and prep v0.26.0

---

package-lock.json
package.json
src/js/flows/exportResults.ts
test/integration/tests/exportZngResults.test.ts
zealot/zealot.ts

Add missing the header property for zealot the query request. Also use
node-fetch for simplicity.
Closes #1905

Fix http request for export result

---

app/search/flows/histogram-search.test.ts
src/js/brim/time.test.ts
src/js/brim/time.ts

fixes #1929 
The date constructor was being given a relative string time which it should be able to handle.

Relative date bug

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimdata/brim/compare/v0.26.0..c756671

prepare v0.27.0

---

package-lock.json
package.json
zealot/zealot.ts

Support changes to lake service events endpoint.
Depends on brimdata/zed#3246

lake service events endpoint changes

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/brimdata/brim/compare/v0.27.0..abf81cc

prepare v0.28.0

---

.github/workflows/advance-zed.yml
.github/workflows/linux-release-candidate.yml
.github/workflows/macos-release-candidate.yml
.github/workflows/win-release-candidate.yml

bump node for CI release actions

---

app/pools/flows/show-pool-context-menu.ts
app/router/routes.ts
src/js/components/LeftPane/index.tsx
src/js/components/Login.tsx
src/js/components/WorkspaceModals/ViewWorkspaceModal.tsx
src/js/components/WorkspaceModals/WorkspaceForm.tsx
src/js/electron/menu/appMenu.ts
src/js/flows/initCurrentTab.ts
src/js/flows/workspace/buildAndAuthenticateWorkspace.ts
src/js/flows/workspace/getAuthCredentials.ts
src/js/flows/workspace/removeWorkspace.ts
src/js/state/Current/selectors.ts

finish changing workspace to lake in text

---

CHANGELOG.md
CONTRIBUTING.md
docs/Filesystem-Paths.md
docs/Importing-CSV,-Parquet,-and-ZST.md
docs/Joining-Data.md
docs/Remote-Workspaces.md

Also update outdated zapi links.

Fix broken doc links

---

.github/workflows/advance-zed.yml

advance-zed.yml has drifted a bit from ci.yml.  Bring it back into
alignment.

align .github/workflows/advance-zed.yml with ci.yml

---

src/js/components/LeftPane/QueriesSection.tsx
src/js/state/Queries/flows.ts

The brim folder itself should be allowed to live anywhere the user wants in the tree.
Closes #1927

Be able to drag brim folder

---

packages/zealot/src/client/client.ts

The load endpoint needs to not have a timeout since we may send
a very large file to the backend. Closes #2181

no timeout for load

---

app/features/sidebar/flows/remote-queries.ts
src/js/components/LeftPane/remote-queries.ts

Fix split stragglers

---

src/js/initializers/initDetail.ts

Fix detail window span bug

---

app/search/flows/next-page-viewer-search.ts

Next Page Search with No Span

---

.github/workflows/ci.yml
app/features/inspector/inspect-list.ts
app/features/inspector/inspector.tsx
app/features/inspector/render.tsx
app/features/inspector/types.ts
app/query-home/results/main-inspector.tsx
app/routes/search/main-inspector.tsx
package.json
yarn.lock

When the inspector is open and a user clicks on a line, open that log in the log detail pane﻿

View Log Detail with Inspector

---

app/search/flows/histogram-search.ts

Fixes #2197
First clear, then set to fetching.

Fix histogram loading

---

app/lakes/root.tsx
src/js/electron/main.ts

Need the same number of hooks for every render.

---

src/app/features/inspector/row.tsx
src/app/features/sidebar/common.tsx
src/app/features/sidebar/index.tsx
src/app/features/sidebar/queries-section/query-item.tsx
src/app/query-home/index.tsx
src/app/query-home/results/results.styled.tsx
src/app/query-home/toolbar/action-buttons.tsx
src/app/query-home/toolbar/button.tsx
src/css/settings/_colors.scss

I improved some color and spacing styles.
I have been wondering about how to organize colors for a long time now. We use color names at the moment. However, I propose we move to descriptions of where the color will be used. The reason for this is that it's easier to understand what color you are changing, and where it is used.
This is how Slack and VSCode create custom themes, they give names to all the colors based on where they are used. I think this is what we'll do going forward. This will be easier to manage in a design tool as well.
https://code.visualstudio.com/api/references/theme-color
https://slack.com/help/articles/205166337-Change-your-Slack-theme

Query Flow Style Polish

---

.swcrc

Fix base url for windows

---

src/js/components/Preferences/Preferences.test.tsx
src/test/shared/__mocks__/electron.ts
src/test/system/boot-brim.tsx
src/test/system/system-test.tsx

- Set the timeout higher for system tests
- Fix run dir
Hopefully that gets the tests on main working again.

Fix Windows Test

---

src/js/flows/exportResults.ts

fixes #2239 
Get poolId from query source instead of location during query-flow

fix export for query-flow

---

src/css/settings/_fonts.scss

This might have been prevent the fonts from loading in the released app.

lowercase font name

---

docs/Migration-for-Version-0.29.md

I did another proofreading pass on the article and found a few more possible improvements.

A few more changes to the v0.29 Migration article

---

src/app/features/sidebar/menu.tsx
src/app/query-home/results/results.styled.tsx

Change tab label styles

---

.github/workflows/linux-release-candidate.yml
.github/workflows/linux-release-promotion.yml
.github/workflows/macos-release-candidate.yml
.github/workflows/macos-release-promotion.yml
.github/workflows/win-release-candidate.yml
.github/workflows/win-release-promotion.yml

This is the way you need to authenticate with google now: https://github.com/google-github-actions/setup-gcloud#service-account-key-json
The error was spotted in this action: https://github.com/brimdata/brim/actions/runs/2067307551

Update gcloud action

---

package.json
yarn.lock

This fixes an issue with use zson duration values in brimcap search.

bump brimcap

---

src/js/about.tsx

The about window was not working because we were looking for the wrong div id in the html.
Fixes  #2332

Fix about window

---

CHANGELOG.md
package.json
yarn.lock

Prettier needed to run on the changelog markdown file, so the diff under the new section is just formatting.

Prepare Brim Version 0.30.0

---

src/app/features/sidebar/pools-section/pool-item.tsx
src/app/lakes/root.tsx
src/app/query-home/flows/submit-search.ts
src/app/query-home/index.tsx
src/app/query-home/loader.ts
src/app/query-home/route.tsx
src/app/query-home/utils/brim-query.ts
src/app/routes/search/data-hook.ts

Make a new draft query when you click the pools

Fetch the results when the location changes

---

src/app/query-home/results/results.styled.tsx
src/app/query-home/search-area/Input.tsx
src/app/query-home/search-area/editor/query-editor.tsx
src/app/query-home/search-area/editor/theme.ts
src/app/query-home/search-area/editor/use-extensions.ts
src/app/query-home/search-area/pins/form-helpers.tsx
src/app/query-home/search-area/pins/pins.tsx
src/app/query-home/search-area/submit-button.tsx
src/app/query-home/toolbar/button.tsx
src/app/query-home/toolbar/index.tsx
src/app/query-home/toolbar/query-header.tsx
src/app/routes/search/results.styled.tsx
src/app/toolbar/toolbar.tsx
src/css/_about-window.scss
src/css/_pane.scss
src/css/_status-bar.scss
src/css/settings/_colors.scss
src/js/state/Layout/reducer.ts
src/js/style-theme/index.ts

editor style fix

---

src/app/query-home/results/results-error.tsx
src/app/query-home/results/results.styled.tsx

Center results view picker

---

src/app/features/sidebar/queries-section/index.tsx
src/js/state/Queries/flows.ts
src/js/state/Queries/helpers.test.ts
src/js/state/Queries/helpers.ts

fixes #2375 
new counter function that determines next default query name's next count based on existing queries

Default query name count func

---

src/app/query-home/search-area/pins/pin-context-menu.ts
src/app/query-home/toolbar/hooks/use-pins.tsx
src/js/initializers/initIpcListeners.ts
src/js/state/Editor/reducer.ts

Also fixed a bug in deleting pins.

Submit Search After Pin Changes

---

src/app/features/inspector/list.styled.tsx
src/app/features/inspector/templates/opening.ts

Remove the type name

---

src/app/query-home/results/results.styled.tsx

Fix columns overflowing into sidebar

---

src/app/ipc/meta.test.ts
src/app/release-notes/test.tsx
src/js/api/core/get-path.test.ts
src/js/api/core/get-path.ts
src/js/components/Login.test.tsx
src/js/electron/autoUpdater.test.ts
src/js/electron/brim-boot.test.ts
src/js/electron/brim-quit.test.ts
src/js/electron/brim-reset-state.test.ts
src/js/electron/brim-start.test.ts
src/js/electron/menu/appMenu.test.ts
src/js/electron/menu/appMenu.ts
src/plugins/brimcap/brimcap-plugin.test.ts
src/plugins/brimcap/brimcap-plugin.ts
src/test/shared/__mocks__/electron.ts
src/test/system/boot-brim.tsx
src/test/system/index.ts
src/test/system/real-paths.ts
src/test/system/system-test-class.tsx
src/test/unit/helpers/setup-api.ts
src/test/unit/helpers/setup-brim.ts

- Only use real paths when needed
- Fix the bug and add a test

Fix Brimcap Path

---

src/app/detail/Pane.tsx
src/app/features/inspector/views/error-view.ts
src/app/features/right-pane/detail-section.tsx
src/app/query-home/results/index.tsx
src/js/components/AppErrorBoundary.tsx
src/js/models/TableColumns.ts
src/js/state/getPersistable.ts

Fix results bug

---

.github/workflows/ci.yml
packages/e2e-tests/helpers/env.ts
packages/e2e-tests/helpers/test-app.ts
packages/e2e-tests/package.json
packages/e2e-tests/playwright.config.js
packages/e2e-tests/tests/ingest.spec.ts
src/app/features/sidebar/plus-button.tsx
src/app/pools/home.tsx
src/app/query-home/search-area/editor/query-editor.tsx
src/js/components/BrimToaster.tsx
src/js/components/HTMLContextMenu.tsx
src/js/components/status-bar/query-progress.tsx
src/js/components/status-bar/type-count.tsx
src/js/lib/System.ts
yarn.lock

Brings back the ingest flow integration tests. While I've modified them to be more stable, the plan moving forward is still to run these locally as a part of the release process and not in CI's inconsistent environment.

Ingest flow integration tests

---

package.json
yarn.lock

See https://github.com/brimdata/brimcap/pull/274#issue-1357923591 for motivation.

Upgrade Brimcap to 0bcc312

---

src/app/commands/flash-element.ts
src/app/commands/show-history-pane.ts
src/app/features/right-pane/common.tsx
src/app/features/right-pane/history/section.tsx
src/app/features/right-pane/index.tsx
src/app/features/right-pane/versions-section.tsx
src/app/query-home/title-bar/nav-actions.tsx
src/css/_animations.scss

Fixes #2476 
The video tells it all!
https://user-images.githubusercontent.com/3460638/188738069-0792c0c2-ee78-47ff-b3e7-a186154853f3.mp4

Make the history button purpose more clear

---

.github/workflows/ci.yml
package.json
src/app/core/models/zed-ast.ts
yarn.lock

This includes an update to src/app/core/models/zed-ast for the AST change in brimdata/zed#4072.

upgrade Zed to 480d4fa97c072b3f53fea7dc906aed651f22c408

---

packages/e2e-tests/helpers/test-app.ts
src/js/state/Queries/create.test.ts
src/js/state/Queries/flows.ts
src/test/unit/helpers/initTestStore.ts
src/test/unit/helpers/setup-store.ts
src/test/unit/index.ts

I was overwriting the provided pins with the default. Face palm. I've added a test that will break if that happens again.
Fixes #2528

Pin Problem

---

electron-builder-insiders.json
electron-builder.json

This reverts commit c0e24d1cd3f7c5f724b540d6f7989c906d84fe32.

Revert "Unique App Ids for Zui (#2547)"

---

packages/zealot/src/client/client.ts

Send no content type for load method.

Blank Content Type

---

.github/actions/setup-zui/action.yml
.github/workflows/advance-zed.yml

Follow-up to the same upgrade in brimdata/zed#4219.

upgrade to Go 1.19

---

.github/workflows/markdown-link-check-config.json

See https://github.com/brimdata/zed/pull/4288 for details.

Skip https://suricata.io link check

---

src/components/zed-table/create-columns.tsx
src/js/api/pools/pools-api.ts

- Remove a console.log
- Type fields can be null
Fixes #2640

App State Data Bug Fix

---

README.md

Zui README Update

---

packages/zealot/src/zed/utils/is-container.ts
src/app/features/inspector/templates/closing.ts
src/app/features/inspector/templates/field.tsx
src/app/features/inspector/templates/typename.tsx
src/app/features/inspector/views/array-view.ts
src/app/features/inspector/views/create.ts
src/app/features/inspector/views/int-view.ts
src/app/features/inspector/views/map-view.ts
src/app/features/inspector/views/set-view.ts
src/app/features/inspector/views/type-record-view.ts
src/app/features/inspector/views/type-union-view.ts
src/app/features/inspector/views/type-value-view.ts
src/app/features/inspector/views/view.ts
src/app/features/sidebar/drop-overlay.tsx
src/css/shared/_type-colors.scss

This PR closes some gaps that were found in the rendering of values in the inspector.
We added a type union view, a type value view, an integer view, and tweaked when the decorators should appear.
Closes #2655
Closes #2656

Inspector Bugs

---

src/app/features/inspector/views/string-view.ts
src/app/query-home/results/bare-string-view.ts

Escape new lines in the inspector and table

---

package.json
packages/e2e-tests/tests/pool-loads.spec.ts
yarn.lock

Adjusts some e2e tests to the changes in https://github.com/brimdata/zed/pull/4420.

Advance Zed pointer and fix tests

---

CHANGELOG.md
package.json
yarn.lock

https://github.com/brimdata/brim/compare/v0.30.0...1d5cd15

Update zed to v1.6.0 and prep v1.0.0

---

package.json
yarn.lock

See https://github.com/brimdata/brimcap/pull/305 for motivation.

Advance Brimcap dependency to 41f21af

---

src/pages/welcome/index.tsx

Closes #2704
https://user-images.githubusercontent.com/5934157/224106558-e3ac2b9c-a28a-4b86-a3c0-9f0dfbfde57a.mp4

Add a Documentation link from the Welcome page

---

CHANGELOG.md
package.json
yarn.lock

https://github.com/brimdata/zui/compare/b80ce29...76707da

Update zed to v1.7.0, brimcap to v1.4.1, and prep v1.0.1

---

package.json
yarn.lock

This will get the change in https://github.com/brimdata/brimcap/pull/308 out in Zui Insiders.

Advance Brimcap dependency to 1b7cbaa

---

src/js/electron/zui-main.ts
src/test/shared/__mocks__/electron.ts

Exit the app after relaunch

---

package.json
yarn.lock

This version includes a fix for CVE-2022-25883.

Upgrade semver to 7.5.3

---

src/app/core/models/zed-ast.ts

Try to parse the ast but don't throw an exception if it doesn't work.

---

src/core/menu/use-menu-instance.ts

Update Result Menu Items Whenever the Tab Changes

---

src/panes/histogram-pane/pane.tsx
src/panes/histogram-pane/resizer.tsx

Passing the element won't work.
Fixes #2807

Pass the Ref to the Histogram Resizer

---

src/app/core/components/switch-button.tsx
src/app/features/sidebar/item.tsx
src/app/features/sidebar/lake-picker.tsx
src/app/query-home/flows/submit-search.ts
src/components/section-tabs.tsx
src/css/settings/_colors.scss
src/js/state/Inspector/reducer.ts
src/js/state/Table/reducer.ts
src/panes/results-pane/context.tsx
src/panes/results-pane/inspector.tsx
src/panes/results-pane/table.tsx
src/zui-kit/core/list-view/list-view-api.ts
src/zui-kit/core/table-view/table-view-api.ts
src/zui-kit/react/list-view.tsx

Reset Scroll Position During Search Submission

---

CHANGELOG.md
package.json
yarn.lock

https://github.com/brimdata/zui/compare/v1.1.0...3d22e61

Update zed to v1.9.0, brimcap to v1.5.1, and prep v1.2.0

---

apps/zui/docs/developer/README.md

Fixing a link breakage from #2818.

Fix broken link to CONTRIBUTING doc

---

.github/workflows/release-insiders.yml

@jameskerr and I were chatting and agreed that it would be good to have these Insiders releases being created in the middle of (our Pacific Time) night.

Create Insiders releases in the middle of the night

---

packages/e2e-tests/README.md

@jameskerr recently showed me how to run a single e2e test in the new monorepo, so I'm adding that to the README. I made a couple other small improvements while I was in there.

Mention single e2e test runs in README

---

apps/zui/CHANGELOG.md
apps/zui/package.json
yarn.lock

https://github.com/brimdata/zui/compare/v1.2.0...5597a25

Update zed to v1.10.0, brimcap to v1.5.2, and prep v1.3.0

---

packages/zui-player/tests/export.spec.ts

See https://github.com/brimdata/zed/issues/4821

Expect VNG export to be smaller (zed/4821)

---

apps/zui/src/app/query-home/search-area/pins/generic-pin/form.tsx
apps/zui/src/app/query-home/search-area/pins/time-range-pin/form.tsx
apps/zui/src/app/query-home/title-bar/heading-form.tsx
apps/zui/src/components/forms.module.css
apps/zui/src/core/query/run.ts
apps/zui/src/core/zq.ts
apps/zui/src/domain/loads/default-loader.ts
apps/zui/src/domain/loads/operations/preview.ts
apps/zui/src/electron/zdeps.ts
apps/zui/src/js/components/ExportModal.tsx
apps/zui/src/js/components/LakeModals/LakeForm.tsx
apps/zui/src/js/components/LakeModals/ViewLakeModal.tsx
apps/zui/src/views/histogram-pane/run-query.ts
apps/zui/src/views/histogram-pane/settings-form.tsx
apps/zui/src/views/load-pane/form.tsx
apps/zui/src/views/new-pool-modal/index.tsx
apps/zui/src/views/preferences-modal/index.tsx
packages/zed-js/src/query/result-stream.ts
packages/zed-node/src/zq.test.ts

Fix the zq path in the packaged app.
Fix the button styles on all forms.
Fix the Github Warnings
This should allow us to release Zui Insiders.

Fix Button Styles and Zq Path

---

apps/zui/src/css/settings/_fonts.scss

OMG Fix the monospace fonts!

---

apps/zui/CHANGELOG.md
apps/zui/package.json
apps/zui/src/app/core/links.ts
yarn.lock

https://github.com/brimdata/zui/compare/v1.4.0...202a21e

Update zed to v1.11.1, brimcap to v1.5.4, and prep v1.4.1

---

apps/zui/CHANGELOG.md
apps/zui/package.json
yarn.lock

https://github.com/brimdata/zui/compare/719d262...4caf78e

Update zed to v1.12.0, brimcap to v1.5.5, and prep v1.5.0

---

apps/zui/src/domain/loads/operations/create.ts

I returned the promise to make a unit test that doesn't exist now. I've added a note to that file that says not to return that promise.
fixes #2989

Fix Waiting for Load

---

apps/zui/CHANGELOG.md
apps/zui/package.json
yarn.lock

https://github.com/brimdata/zui/compare/v1.5.0...6dfae2b

Update zed to v1.13.0, brimcap to v1.6.0, and prep Zui v1.6.0

---

apps/zui/src/app/features/sidebar/item.tsx

Fix Colors on Sidebar Inputs

---

apps/zui/CHANGELOG.md
apps/zui/package.json
yarn.lock

https://github.com/brimdata/zui/compare/v1.6.0...308ed3c

Update zed to v1.15.0, brimcap to v1.7.0, and prep Zui v1.7.0

---

apps/zui/CHANGELOG.md
apps/zui/package.json
yarn.lock

https://github.com/brimdata/zui/compare/v1.8.0...256ecfd

Update zed and brimcap to v1.17.0 and prep Zui v1.17.0

---

apps/zui/CHANGELOG.md
apps/zui/package.json
yarn.lock

https://github.com/brimdata/zui/compare/v1.17.0...bd95fbb

Update zed and brimcap to v1.18.0 and prep Zui v1.18.0

---

.github/actions/setup-zui/action.yml
packages/zed-wasm/go.mod

Upgrade to Go 1.23

---

apps/zui/package.json
apps/zui/src/core/main/main-object.ts
apps/zui/src/initializers/default-lake.ts
apps/zui/src/js/initializers/initLakeParams.ts
apps/zui/src/js/state/Lakes/index.ts

Name the default lake "Local Server" instead of "users's Zed Lake"

Local Server

---

apps/insiders/package.json
apps/zui/package.json
yarn.lock

This just silenced a few warnings that appear when you run "yarn". The rest will require some changes that might break things. Plan to do that at a later time.

Fix some yarn peer requirement warnings

---

apps/superdb-desktop/package.json
apps/superdb-desktop/src/core/zed-syntax.ts
apps/superdb-desktop/src/js/state/Results/paginate.test.ts
apps/superdb-desktop/src/js/state/Results/paginate.ts
packages/app-player/tests/export.spec.ts
packages/app-player/tests/table.spec.ts
packages/superdb-node-client/package.json
yarn.lock

This is to adapt to the change in https://github.com/brimdata/super/pull/5986.

Use "values" operator instead of "yield"
